-- build_seed.py が作るファイル。手で直さないこと。
insert into public.shops (slug,name,kana,opened_on,zone,town,category,genre,instagram) values
('s7fbd8215','Cafe&Bar まっしろ','cafe bar まっしろ',null,'ekimae','中央','night','バー','mashiro_cafeandbar'),
('s8441afb1','Mon Somme(モンソム)','mon somme もんそむ','2026-08-25'::date,'ekimae','中央','gourmet','その他','mon.somme'),
('s31dcadd0','cafe はな','cafe はな',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s4f811d32','や台ずし 福井駅東口町','やだいずし ふくいえきひがしぐちまち',null,'ekimae','日之出','gourmet','その他','yataizushi_official'),
('s691f731e','わおん書房','わおんしょぼう',null,'ekimae','中央','gourmet','その他','waonbooks'),
('s69411869','エノバル','えのばる',null,'ekimae','中央','gourmet','居酒屋','enobar_fukui'),
('s54c3c504','エンジョeat!!! CAFE','えんじょeat cafe',null,'ekimae','中央','gourmet','カフェ・スイーツ','enjoyeat_fukui'),
('s44dd52a3','クレープ&バル FUKU NOTE','くれーぷ ばる fuku note',null,'ekimae','中央','gourmet','居酒屋',''),
('s5be27486','スローベリィ くるふ福井駅福井店/高井屋','すろーべりぃ くるふふくいえきふくいてん たかいや',null,'ekimae','中央','gourmet','その他',''),
('s9bf2cb0a','ハピリン総合受付','はぴりんそうごううけつけ',null,'ekimae','中央','gourmet','その他','happiring_fukui'),
('sad3393df','マルノウチ フクラ','まるのうち ふくら','2026-02-09'::date,'ekimae','中央','gourmet','その他',''),
('s7d7bd31f','小籠包ダイニング 鼎''s by JIN DIN ROU','しょうかごつつみだいにんぐ かなえ s by jin din rou',null,'ekimae','中央','gourmet','その他',''),
('s7896880c','椿宗善 日之出店','つばきしゅうぜん ひのでてん',null,'ekimae','日之出','gourmet','その他','tsubakisozen'),
('s5cb95492','焼きそば専門店 金波','やきそばせんもんてん きんぱ',null,'ekimae','中央','gourmet','そば・うどん','yakisoba_kinpa'),
('scc87d452','焼肉 牛成','やきにく うしせい',null,'ekimae','中央','gourmet','焼肉・肉料理','ushinari_yakiniku'),
('s96304935','爽茶','そうちゃ',null,'ekimae','中央','gourmet','その他','socha_cafe'),
('s09c213ea','若廣(くるふ福井駅店)','じゃくこう くるふふくいえきみせ',null,'ekimae','中央','gourmet','その他','wakahiro_jp'),
('saec8252a','茶屋cafe あたらしや','ちゃやcafe あたらしや',null,'ekimae','中央','gourmet','カフェ・スイーツ','atarashiyaasuwayama'),
('s2c635ca0','越前あて巻き デリアテール','えちぜんあてまき でりあてーる',null,'ekimae','中央','gourmet','その他','deliaterre_minie'),
('s0ed71686','開花亭 BIS','かいかてい bis',null,'ekimae','中央','gourmet','その他',''),
('sabcab050','韓国厨房 崔家','かんこくちゅうぼう さいいえ',null,'ekimae','中央','gourmet','アジア・各国料理','saike_fukui'),
('s1a91596b','食べる本屋さん','たべるほんやさん',null,'ekimae','中央','gourmet','その他','taberuhonyasan_fukuiseibu'),
('sd2740f86','駅前中華そば だるまや','えきまえちゅうかそば だるまや',null,'ekimae','中央','gourmet','そば・うどん',''),
('s7616aa93','麺匠 麦之助(MINIE店)','めんたくみ むぎゆきすけ minieみせ',null,'ekimae','中央','gourmet','ラーメン','mensho_muginosuke'),
('s36ea945b','お好み焼たなか','おこのみやきたなか',null,'ekimae','照手','gourmet','その他',''),
('s268c7b8a','さくら茶屋you‐canビル店','さくらちゃやyou canびるてん',null,'ekimae','中央','gourmet','その他',''),
('sb72278fe','たけや','たけや',null,'ekimae','照手','gourmet','その他',''),
('s4ed8240c','ひらい','ひらい',null,'ekimae','大手','gourmet','その他',''),
('sbab28a94','小次郎','こじろう',null,'ekimae','大手','gourmet','その他',''),
('s4d076cd8','金ちゃん','きんちゃん',null,'ekimae','中央','gourmet','その他',''),
('s1c7e5b4b','PLAYCE(プレイス)','playce ぷれいす',null,'ekimae','中央','gourmet','その他','playce_fukui'),
('sd011f4ae','ラニーピクニック','らにーぴくにっく',null,'ekimae','中央','gourmet','その他',''),
('s7ed82504','日々色々(ヒビイロイロ)','ひびいろいろ ひびいろいろ',null,'ekimae','大手','gourmet','その他','hibiiroiro291'),
('sfb0971c5','越前蕎麦倶楽部','えちぜんそばくらぶ',null,'ekimae','中央','gourmet','そば・うどん','echizensobaclub'),
('s482ab95b','TRAU VANG 88 FOODS','trau vang 88 foods',null,'ekimae','中央','gourmet','その他',''),
('s3d3c6143','Bear’sBar','bear sbar',null,'ekimae','照手','gourmet','その他',''),
('se66b1d1d','Swing’n‐Base','swing n base',null,'ekimae','中央','gourmet','その他',''),
('s08b6d000','fukui cafe Chadou','fukui cafe chadou',null,'ekimae','手寄','gourmet','カフェ・スイーツ',''),
('s281bf00b','あすわ','あすわ',null,'ekimae','大手','gourmet','その他',''),
('s5ce0e5b0','かりゆし','かりゆし',null,'ekimae','日之出','gourmet','その他',''),
('s2d75effd','きぬ','きぬ',null,'ekimae','中央','gourmet','その他',''),
('s272fb962','さつき','さつき',null,'ekimae','中央','gourmet','その他',''),
('s2e9f2fb6','とらや','とらや',null,'ekimae','大手','gourmet','その他',''),
('s8003c885','のみすけ','のみすけ',null,'ekimae','中央','gourmet','その他',''),
('scc329f9e','まると','まると',null,'ekimae','日之出','gourmet','その他',''),
('s1f0b3df9','むらさき','むらさき',null,'ekimae','大手','gourmet','その他',''),
('s398e9bd3','オリーブの木','おりーぶのき',null,'ekimae','大手','gourmet','その他',''),
('s0091a48e','カントリ','かんとり',null,'ekimae','大手','gourmet','その他',''),
('sb32fb9cb','カーサ福井西武店','かーさふくいせいぶてん',null,'ekimae','中央','gourmet','その他',''),
('sa02f4751','カームタイム(CalmTime)','かーむたいむ calmtime',null,'ekimae','大手','gourmet','アジア・各国料理',''),
('sd08e56bb','サロン女湯','さろんおんなゆ',null,'ekimae','中央','gourmet','その他',''),
('sa4132b5b','シェ・サカイ','しぇ さかい',null,'ekimae','中央','gourmet','その他',''),
('s2e2c957c','ヤマシタパン','やましたぱん',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('sa871019f','七平','しちへい',null,'ekimae','手寄','gourmet','その他',''),
('sb1ac409e','今川焼本舗','いまがわやきほんぽ',null,'ekimae','中央','gourmet','その他',''),
('s2799f8eb','匠きし','たくみきし',null,'ekimae','中央','gourmet','その他',''),
('se800168c','印度','いんど',null,'ekimae','大手','gourmet','その他',''),
('s7822e51b','女子寮/福井駅前店','じょしりょう ふくいえきまえてん',null,'ekimae','大手','gourmet','その他',''),
('s6133a887','料理 仕出し 与志多','りょうり しだし よした',null,'ekimae','照手','gourmet','その他','tabakoya.yamamachi'),
('sd2851ea1','晴海','はるみ',null,'ekimae','中央','gourmet','その他',''),
('s2780b245','株式会社アンクル','かぶしきがいしゃあんくる',null,'ekimae','大手','gourmet','その他',''),
('s1598a124','桜むすび','さくらむすび',null,'ekimae','中央','gourmet','その他',''),
('s1edee58d','樅ノ木','しょうのき',null,'ekimae','中央','gourmet','その他',''),
('s03b15c52','海賊艇','かいぞくてい',null,'ekimae','中央','gourmet','その他',''),
('s81ab1c3d','熊五郎','くまごろう',null,'ekimae','中央','gourmet','その他',''),
('s55f3d432','甘露司 飛嶋','かんろつかさ とびしま',null,'ekimae','中央','gourmet','その他',''),
('sf5bfdba9','番匠本店 上りホーム店','ばんしょうほんてん のぼりほーむてん',null,'ekimae','中央','gourmet','その他',''),
('sd56ace3d','福井ワシントンホテル・バロン','ふくいわしんとんほてる ばろん',null,'ekimae','大手','gourmet','その他',''),
('s7d67dc69','福井大麦倶楽部','ふくいおおむぎくらぶ',null,'ekimae','日之出','gourmet','その他',''),
('s707b8afd','福井県庁食堂','ふくいけんちょうしょくどう',null,'ekimae','大手','gourmet','その他',''),
('s42e6e5a6','福井駅前フードホール MINIE','ふくいえきまえふーどほーる minie',null,'ekimae','中央','gourmet','その他',''),
('sf371dde9','秋吉 New秋吉','あきよし newあきよし',null,'ekimae','大手','gourmet','その他',''),
('sc17f4e42','芝寿し 福井店','しばすし ふくいてん',null,'ekimae','大手','gourmet','その他',''),
('sc0f5aa2d','越前市場','えちぜんしじょう',null,'ekimae','手寄','gourmet','その他',''),
('s20744fed','越前田村屋・プリズム福井店','えちぜんたむらや ぷりずむふくいてん',null,'ekimae','中央','gourmet','その他',''),
('sea986e8d','モンナリッサの森','もんなりっさのもり',null,'ekimae','中央','gourmet','アジア・各国料理',''),
('se5583b37','白菜美人','はくさいびじん',null,'ekimae','中央','gourmet','アジア・各国料理',''),
('s84142e3a','FanFan','fanfan',null,'ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s7f0b5db2','Italian Kitchen VANSAN','italian kitchen vansan',null,'ekimae','中央','gourmet','イタリアン・フレンチ',''),
('sd70a6325','イタリアスパゲティ','いたりあすぱげてぃ',null,'ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s02550abd','トレパーチェ・イタリアンレストラン','とれぱーちぇ いたりあんれすとらん',null,'ekimae','大手','gourmet','イタリアン・フレンチ',''),
('se14b3b3f','ドレッセ','どれっせ',null,'ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s90e001cc','侍パスタ','さむらいぱすた',null,'ekimae','手寄','gourmet','イタリアン・フレンチ',''),
('s76408c0a','Paleo Brew Cafe','paleo brew cafe',null,'ekimae','中央','gourmet','カフェ・スイーツ','brewcafe00'),
('sc3c80ac6','cafe ieme','cafe ieme',null,'ekimae','中央','gourmet','カフェ・スイーツ','cafe_ieme'),
('s3e58125e','あんカフェ','あんかふぇ',null,'ekimae','中央','gourmet','カフェ・スイーツ','an.cafe.oshima'),
('s4a2831ba','ごーる堂Do+','ごーるどうdo',null,'ekimae','中央','gourmet','カフェ・スイーツ','soysoftcream_goldo'),
('s9d624ce9','ヨリバ(YORIVER)','よりば yoriver',null,'ekimae','中央','gourmet','カフェ・スイーツ','yoriver_asuwa'),
('s276f99eb','抹茶庵 福井中央店','まっちゃあん ふくいちゅうおうてん',null,'ekimae','中央','gourmet','カフェ・スイーツ','matchaan_fukui'),
('s44b5276e','PUITS D’AMOUR','puits d amour',null,'ekimae','手寄','gourmet','カフェ・スイーツ',''),
('s8a3f24e9','UCC CAFE MERCADO 福井西武','ucc cafe mercado ふくいせいぶ',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s359812db','YEN','yen',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('sab0da53d','cafe maachar','cafe maachar',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('sf8e2058b','えがわ','えがわ',null,'ekimae','照手','gourmet','カフェ・スイーツ',''),
('s13905151','かがみ','かがみ',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('sbcb69889','きんつばの中田屋 プリズム福井水仙花店','きんつばのなかだや ぷりずむふくいすいせんはなてん',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s5fcc5b45','つゆ','つゆ',null,'ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s86e1194f','ぴえろはうす','ぴえろはうす',null,'ekimae','日之出','gourmet','カフェ・スイーツ',''),
('sad7e62bf','みるく茶庵','みるくちゃあん',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s91dea10e','るうぶる','るうぶる',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('s859b836c','れーるろーど','れーるろーど',null,'ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s478d54dc','カフェるん','かふぇるん',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s36103bc2','カフェ・カプチーナ','かふぇ かぷちーな',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('s2a1fd4c1','キルトカフェ・趣味工房','きるとかふぇ しゅみこうぼう',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s5cdbf379','クリーミードーナツ 福井駅前店','くりーみーどーなつ ふくいえきまえてん',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s67d9b1ae','コーヒー専門吉田','こーひーせんもんよしだ',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('sa20e3e11','サロンド・GO','さろんど go',null,'ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s1b88cf41','シークチョイスカフェ','しーくちょいすかふぇ',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s6f1aaa8f','ダーツカフェ Green Box','だーつかふぇ green box',null,'ekimae','手寄','gourmet','カフェ・スイーツ',''),
('sda7065aa','チャーム','ちゃーむ',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('s8e708fc9','トーヨー','とーよー',null,'ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s0f4e999b','ニシムラカフェ駅前店','にしむらかふぇえきまえてん',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s4c7ec2c3','ニッパー','にっぱー',null,'ekimae','照手','gourmet','カフェ・スイーツ',''),
('sbbce2c2f','ハシモト洋菓子店','はしもとようがしてん',null,'ekimae','つくも','gourmet','カフェ・スイーツ',''),
('sfae834e9','ハーフ','はーふ',null,'ekimae','手寄','gourmet','カフェ・スイーツ',''),
('s1b5bdc0b','ベーカリープラザ','べーかりーぷらざ',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s6bb5bc7f','ポニー純喫茶','ぽにーじゅんきっさ',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s539f12a1','マタリ','またり',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s567b4238','ムーラン','むーらん',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('sc8e51bff','モジカフェ','もじかふぇ',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('sb5d66038','モンターニュ','もんたーにゅ',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('sf06a7d20','ヤン・カフェ','やん かふぇ',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s57778317','ユトリ珈琲店 AOSSA店','ゆとりこーひーてん aossaてん',null,'ekimae','手寄','gourmet','カフェ・スイーツ',''),
('sf253ab07','ユミ','ゆみ',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s4d0b8d82','リトルマーメイドくるふ福井駅','りとるまーめいどくるふふくいえき',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('sa0155603','ルビー','るびー',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('sb76a8139','ル・ピュイ','る ぴゅい',null,'ekimae','手寄','gourmet','カフェ・スイーツ',''),
('scebf7e9b','ルーツカフェ(ROUTE’SCAFE)','るーつかふぇ route scafe',null,'ekimae','照手','gourmet','カフェ・スイーツ',''),
('sc0f77424','古城','こじょう',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('sf14bda3d','天秤座','てんびんざ',null,'ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s73548a07','奈々重','ななじゅう',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s98b47d7f','快活CLUB/福井駅前店','かいかつclub ふくいえきまえてん',null,'ekimae','大手','night','スナック・ラウンジ',''),
('s10e1f57f','森のフェスタおばさん','もりのふぇすたおばさん',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s5fa54a4e','森乃家','もりのいえ',null,'ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s5c294506','神戸ふう月堂福井店','こうべふうがつどうふくいてん',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s94386578','絵紋','えもん',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s61151c82','花','はな',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('s572583db','茶房談話室','さぼうだんわしつ',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('s6efdb81a','蒼山','あおやま',null,'ekimae','日之出','gourmet','カフェ・スイーツ',''),
('sbf0a4361','逢園','ほうその',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('s4d28e1e7','銀座茶廊','ぎんざさろう',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('s96ac50a1','Kisaki CAFE CENTRAL PARK','kisaki cafe central park',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('seff70599','とろけるクレープ MOMI&TOY’S 福井駅前店','とろけるくれーぷ momi toy s ふくいえきまえてん',null,'ekimae','中央','gourmet','カフェ・スイーツ','momitoy_fukuiekimae'),
('sbc9f8a54','カフェレストラン su_mu(スム)','かふぇれすとらん su mu すむ',null,'ekimae','中央','gourmet','カフェ・スイーツ','su_mu300567'),
('s1018b4c4','CAFÉ52(カフェ ゴジュウニ)','caf 52 かふぇ ごじゅうに',null,'ekimae','中央','gourmet','カフェ・スイーツ','cafebar52'),
('s0bd2f63c','HANDS COFFEE(ハンズコーヒー)','hands coffee はんずこーひー',null,'ekimae','中央','gourmet','カフェ・スイーツ','hands_coffee'),
('s1aafc2bb','Att kitchen( アットキッチン)','att kitchen あっときっちん',null,'ekimae','中央','gourmet','カフェ・スイーツ','att_kitchen_'),
('s33de1202','CAFÉ CON TE(カフェコンテ)','caf con te かふぇこんて',null,'ekimae','中央','gourmet','カフェ・スイーツ','cafe.conte2026'),
('s6f98adcc','Magari Coffee(マガリコーヒー)','magari coffee まがりこーひー',null,'ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s4098663f','カフェまてき','かふぇまてき',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('sb543236c','高級和栗モンブラン専門店 栗歩 福井駅前店(くりほ)','こうきゅうわくりもんぶらんせんもんてん くりほ ふくいえきまえてん くりほ',null,'ekimae','中央','gourmet','カフェ・スイーツ','waguri_montblanc_kuriho'),
('sc4ebbf42','Okazu&bread(オカズ アンド ブレッド)','okazu bread おかず あんど ぶれっど',null,'ekimae','手寄','gourmet','カフェ・スイーツ','okazu_and_bread'),
('s19efcdc4','エトワァル','えとわぁる',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('s83d42a65','マルサパン','まるさぱん',null,'ekimae','手寄','gourmet','カフェ・スイーツ',''),
('sa186b57e','AFTERGLOW CHOCOLATE(アフターグロウチョコレート)','afterglow chocolate あふたーぐろうちょこれーと',null,'ekimae','照手','gourmet','カフェ・スイーツ','afterglow_chocolate'),
('sb4ad068c','Good Smile Donut(グッドスマイルドーナツ)','good smile donut ぐっどすまいるどーなつ',null,'ekimae','日之出','gourmet','カフェ・スイーツ','goodsmile.donut'),
('sd546a9d9','スコーン専門店 肆 -よん-','すこーんせんもんてん し よん',null,'ekimae','中央','gourmet','カフェ・スイーツ','yon_scone'),
('s7ee907f6','サニーさんの農園マルシェ','さにーさんののうえんまるしぇ',null,'ekimae','中央','gourmet','カフェ・スイーツ','sunnysfarmmarche'),
('s0ac00f12','8番らーめん/くるふ福井駅店','8ばんらーめん くるふふくいえきてん',null,'ekimae','中央','gourmet','ラーメン',''),
('s75e3bf56','いちや福井駅前店','いちやふくいえきまえてん',null,'ekimae','中央','gourmet','ラーメン',''),
('s61d8b801','なん・なん亭 福井店','なん なんてい ふくいてん',null,'ekimae','大手','gourmet','ラーメン',''),
('s3370fd96','集集','しゅうしゅう',null,'ekimae','中央','gourmet','ラーメン',''),
('s30c78e0f','Bistro&Bar GLOUTONNE','bistro bar gloutonne',null,'ekimae','中央','night','バー',''),
('s8a28b280','キナリ','きなり',null,'ekimae','日之出','gourmet','洋食','_____kinari'),
('s0a856f1a','トラットリア チャオ','とらっとりあ ちゃお',null,'ekimae','中央','gourmet','イタリアン・フレンチ','trattoria_ciao_'),
('s6f5e18f4','西武福井店 ダイニングスクエア','せいぶふくいてん だいにんぐすくえあ',null,'ekimae','中央','gourmet','洋食',''),
('se64356d9','あみだそば はなれ','あみだそば はなれ',null,'ekimae','中央','gourmet','そば・うどん',''),
('s69243200','おそばだうどんだ越前','おそばだうどんだえちぜん',null,'ekimae','中央','gourmet','そば・うどん',''),
('s8ad103bd','三井屋','みついや',null,'ekimae','つくも','gourmet','そば・うどん',''),
('s9a8cb6ff','日ノ出西村屋','にちのしゅっさいむらや',null,'ekimae','日之出','gourmet','そば・うどん',''),
('s4583b225','蕎麦庵 sio(シオ)','そばあん sio しお',null,'ekimae','中央','gourmet','そば・うどん','sobaansio40'),
('s9c952b2d','Beer&Grill GRIOMAN(グリオマン)','beer grill grioman ぐりおまん',null,'ekimae','中央','gourmet','焼肉・肉料理','grioman_fukui'),
('s25796be9','U(ユー)','u ゆー',null,'ekimae','大手','gourmet','焼肉・肉料理','u__fukui'),
('sbebfde1a','パスタと珈琲とカヌレのお店','ぱすたとこーひーとかぬれのおてん',null,'ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s56b39f6a','RUNNY PICNIC(ラニーピクニック)','runny picnic らにーぴくにっく',null,'ekimae','中央','gourmet','洋食','runny.picnic'),
('s1c5b0523','日豪レストラン ゆめや','にちごうれすとらん ゆめや',null,'ekimae','中央','gourmet','洋食',''),
('s55e7c838','越山若水 行雲(えつざんじゃくすいこううん)','こしやまじゃくすい こううん えつざんじゃくすいこううん',null,'ekimae','中央','gourmet','洋食','etsuzanjyakusui_koun'),
('sd4e68c11','すし日竜(ひりゅう)','すしにちりゅう ひりゅう',null,'ekimae','中央','gourmet','寿司・海鮮','sushi_hiryu'),
('s03f8cc3e','大衆赤酢寿司 ぼんた','たいしゅうあかずすし ぼんた',null,'ekimae','中央','gourmet','寿司・海鮮',''),
('s0c2231f0','sake to ate(サケトアテ)','sake to ate さけとあて',null,'ekimae','日之出','gourmet','居酒屋','sake.to.ate'),
('s0f913aee','タコとハイボール','たことはいぼーる',null,'ekimae','中央','gourmet','居酒屋',''),
('s7668ab61','大衆酒場 れいわ 福井駅前店','たいしゅうさかば れいわ ふくいえきまえてん',null,'ekimae','中央','gourmet','居酒屋',''),
('se90bbb55','大衆酒場 ラドン','たいしゅうさかば らどん',null,'ekimae','中央','gourmet','居酒屋',''),
('see25b77f','手羽先番長 福井駅前店','てばさきばんちょう ふくいえきまえてん',null,'ekimae','中央','gourmet','居酒屋','tebasakibancho_fukui'),
('sb65f332e','酒と肴の旨い店 和華(わか)','さけとさかなのうまいてん のどか わか',null,'ekimae','照手','gourmet','居酒屋','izakaya__waka'),
('s9bc498e5','越前海鮮屋 福井駅前店','えちぜんかいせんや ふくいえきまえてん',null,'ekimae','中央','gourmet','寿司・海鮮',''),
('sc94c43ec','やきとり やすぎ家','やきとり やすぎいえ',null,'ekimae','中央','gourmet','焼鳥・串','yasugiya.tomomi'),
('sf61651e6','えがわ プリズム福井 水仙花店','えがわ ぷりずむふくい すいせんはなてん',null,'ekimae','中央','gourmet','中華',''),
('s0c6c7bbb','たごさく 福井西武','たごさく ふくいせいぶ',null,'ekimae','中央','gourmet','中華',''),
('s5c375ccf','ゴディバ 西武福井','ごでぃば せいぶふくい',null,'ekimae','中央','gourmet','中華',''),
('s0a5d3303','ドンク 西武福井店','どんく せいぶふくいてん',null,'ekimae','中央','gourmet','中華',''),
('s513f8ff4','ボノボノ プリズム福井店','ぼのぼの ぷりずむふくいてん',null,'ekimae','中央','gourmet','中華',''),
('sbd243964','万よし','まんよし',null,'ekimae','中央','gourmet','中華',''),
('sfc766a3a','御菓子司 栄太楼','おかしつかさ えいたろう',null,'ekimae','中央','gourmet','中華',''),
('sbaccabfb','悟空','ごくう',null,'ekimae','大手','gourmet','中華',''),
('s70b0f1a5','満堂紅福井店','まんどうくれないふくいてん',null,'ekimae','中央','gourmet','中華',''),
('s0e6cf074','白楽','はくらく',null,'ekimae','日之出','gourmet','中華',''),
('sc4b4e40b','目からうろこ 福井駅前本店','めからうろこ ふくいえきまえほんてん',null,'ekimae','中央','gourmet','中華',''),
('s6809818c','福林軒','ふくばやしけん',null,'ekimae','中央','gourmet','中華',''),
('s5e66ff80','羽二重餅の古里 マエダセイカ プリズム福井 水仙花店','はぶたえもちのふるさと まえだせいか ぷりずむふくい すいせんはなてん',null,'ekimae','中央','gourmet','中華',''),
('sd7ac3a10','鳳城酒家','ほうじょうしゅか',null,'ekimae','中央','gourmet','中華',''),
('s3fed0671','Cafe&Curry カレッテリア','cafe curry かれってりあ',null,'ekimae','大手','gourmet','アジア・各国料理','caletteria'),
('s2d8cb41e','Livin’ for green','livin for green',null,'ekimae','中央','gourmet','アジア・各国料理','livin_for_green'),
('s39bea949','モーニングトマト','もーにんぐとまと',null,'ekimae','中央','gourmet','アジア・各国料理',''),
('s26c0f87c','いちろくらーめん ふくい駅前店','いちろくらーめん ふくいえきまえてん',null,'ekimae','中央','gourmet','ラーメン','ichiroku_ramen'),
('sfa12c119','つけ麺 いちろく','つけめん いちろく',null,'ekimae','中央','gourmet','ラーメン','ichiroku_ramen'),
('s2caeb34f','とりで','とりで',null,'ekimae','日之出','gourmet','ラーメン',''),
('s6b9bcc45','五目亭の福井らーめん「かたいけの」','ごもくていのふくいらーめん かたいけの',null,'ekimae','中央','gourmet','ラーメン','fukui_ramen_gomokutei'),
('s8c4eebb6','屋台 てっちゃんラーメン 福井駅前店','やたい てっちゃんらーめん ふくいえきまえてん',null,'ekimae','中央','gourmet','ラーメン',''),
('sffb16825','屋台 岩ちゃんラーメン','やたい いわちゃんらーめん',null,'ekimae','中央','gourmet','ラーメン',''),
('s27343607','つくも橋 ピリケン 本店','つくもはし ぴりけん ほんてん',null,'ekimae','つくも','gourmet','中華','pilliken_honten'),
('s5fcbd905','ふ一 MINIE店','ふいち minieてん',null,'ekimae','中央','gourmet','中華','fuichi_fukui'),
('sdc3cbb64','中国料理 紅蘭','ちゅうごくりょうり こうらん',null,'ekimae','中央','gourmet','中華',''),
('sec11e85c','中華料理 ISSEI','ちゅうかりょうり issei',null,'ekimae','手寄','gourmet','中華',''),
('se710cfe5','四季彩中華 シノワ','しきさいちゅうか しのわ',null,'ekimae','大手','gourmet','中華',''),
('s890e7d23','四川料理 西遊記','しせんりょうり さいゆうき',null,'ekimae','中央','gourmet','中華',''),
('s6c838691','来々軒','らいらいけん',null,'ekimae','つくも','gourmet','中華',''),
('sd35a5578','茶荘・香蘭(ちゃそうこうらん)','ちゃそう こうらん ちゃそうこうらん',null,'ekimae','中央','gourmet','中華','chasoukouran2025111'),
('s1b359789','Dogs','dogs',null,'ekimae','大手','gourmet','アジア・各国料理','dogs_hotdog_fukui'),
('s67908d92','KOREA','korea',null,'ekimae','中央','gourmet','アジア・各国料理',''),
('s743e8c6c','TARY HOUSE','tary house',null,'ekimae','中央','gourmet','アジア・各国料理','taryhouse'),
('se1680e15','ベトナムレストラン Que Huong Quan','べとなむれすとらん que huong quan',null,'ekimae','中央','gourmet','アジア・各国料理',''),
('sc15721ee','居酒屋 しゃんがり。','いざかや しゃんがり',null,'ekimae','大手','gourmet','居酒屋','izakaya_shangari_fukui'),
('s8be5beb6','いっ福亭','いっふくてい',null,'ekimae','日之出','gourmet','焼肉・肉料理',''),
('s588dd8ac','ホルモン 焼肉 お食事処 はるや','ほるもん やきにく おしょくじどころ はるや',null,'ekimae','日之出','gourmet','焼肉・肉料理',''),
('s22bd026c','鉄板焼肉とジンギスカン ぼんた 福井駅前店','てっぱんやきにくとじんぎすかん ぼんた ふくいえきまえてん',null,'ekimae','大手','gourmet','焼肉・肉料理','jingisukanbonta'),
('s4aa386ab','おお田','おおた',null,'ekimae','大手','gourmet','和食',''),
('s3527a6ce','かわきん','かわきん',null,'ekimae','大手','gourmet','和食',''),
('s6cf33e3c','こんぴら亭三の丸店','こんぴらていさんのまるてん',null,'ekimae','大手','gourmet','和食',''),
('s9a9b6a54','さが良','さがりょう',null,'ekimae','照手','gourmet','和食',''),
('sb06737be','さくら茶屋くるふ福井駅店','さくらちゃやくるふふくいえきてん',null,'ekimae','中央','gourmet','和食',''),
('seda0e607','せいもん','せいもん',null,'ekimae','大手','gourmet','和食',''),
('sfe9342cb','そば勝アオッサ店','そばかちあおっさてん',null,'ekimae','手寄','gourmet','そば・うどん',''),
('s392c8643','そば勝本店','そばかちほんてん',null,'ekimae','中央','gourmet','そば・うどん',''),
('s977f9ab2','てらしま','てらしま',null,'ekimae','中央','gourmet','和食',''),
('s64a33e0b','はら田','はらた',null,'ekimae','照手','gourmet','和食',''),
('s470d2762','まわるすし中央店','まわるすしちゅうおうてん',null,'ekimae','中央','gourmet','寿司・海鮮',''),
('s7b9d37ca','やま田','やまた',null,'ekimae','中央','gourmet','和食',''),
('sc5d36fef','カルマ繊協ビル店','かるませんきょうびるてん',null,'ekimae','大手','gourmet','和食',''),
('s4a1313e4','ビックリ竹田屋総本店','びっくりたけだやそうほんてん',null,'ekimae','大手','gourmet','和食',''),
('s47175d3f','ミチ','みち',null,'ekimae','中央','gourmet','和食',''),
('s67b72d3c','ランチ屋 麦米','らんちや むぎこめ',null,'ekimae','大手','gourmet','和食',''),
('sb2683b78','三喜寿司','さんきすし',null,'ekimae','日之出','gourmet','寿司・海鮮',''),
('sd9c0a218','中清','なかきよ',null,'ekimae','中央','gourmet','和食',''),
('s508562d6','今庄そば','いまじょうそば',null,'ekimae','手寄','gourmet','そば・うどん',''),
('sa7c85c96','信濃','しなの',null,'ekimae','中央','gourmet','和食',''),
('sa30f648f','割烹敏','かっぽうとし',null,'ekimae','中央','gourmet','和食',''),
('s9c6c2422','呑喜','どんき',null,'ekimae','中央','gourmet','和食',''),
('sa33c83e7','和食料理 釜蔵','わしょくりょうり かまくら',null,'ekimae','中央','gourmet','和食',''),
('s0f7a740d','善甚','ぜんじん',null,'ekimae','大手','gourmet','和食',''),
('sc5a5aadf','城の橋','しろのはし',null,'ekimae','手寄','gourmet','和食',''),
('s8ea4c3b0','天新','てんしん',null,'ekimae','大手','gourmet','和食',''),
('sf7ee645e','太鼓寿し','たいこすし',null,'ekimae','大手','gourmet','和食',''),
('sfed1e0c1','宴会屋','えんかいや',null,'ekimae','大手','gourmet','和食',''),
('s089c89ef','富士','ふじ',null,'ekimae','日之出','gourmet','和食',''),
('s8fc8b4d9','山清','さんせい',null,'ekimae','中央','gourmet','和食',''),
('s878f6e02','新日本料理 桜ばし','しんにほんりょうり さくらばし',null,'ekimae','中央','gourmet','和食',''),
('sf4472555','昌冨ずし','まさとみずし',null,'ekimae','中央','gourmet','和食',''),
('s33a711ac','昭和寿司','しょうわすし',null,'ekimae','照手','gourmet','寿司・海鮮',''),
('s6fe70d3a','楽庵','らくあん',null,'ekimae','中央','gourmet','和食',''),
('se210380d','歌舞伎寿司本店','かぶきすしほんてん',null,'ekimae','中央','gourmet','寿司・海鮮',''),
('s8d2bdf59','満里邑','みちさとむら',null,'ekimae','中央','gourmet','和食',''),
('s9b10b23a','源治鮨','げんじすし',null,'ekimae','大手','gourmet','寿司・海鮮',''),
('s7ad15852','照寿し','しょうすし',null,'ekimae','中央','gourmet','和食',''),
('s3dd83a32','甘泉堂','かんせんどう',null,'ekimae','中央','gourmet','和食',''),
('s52fa3549','生簀海鮮 やまもとや','いけすかいせん やまもとや',null,'ekimae','大手','gourmet','寿司・海鮮',''),
('sea9725fc','町寿司いちもんめ 福井駅前','まちすしいちもんめ ふくいえきまえ',null,'ekimae','大手','gourmet','寿司・海鮮',''),
('s19600a96','異人館跡風琴亭','いじんかんあとふうきんてい',null,'ekimae','中央','gourmet','和食',''),
('sf71ab51f','福井山相撲料理','ふくいさんそうぼくりょうり',null,'ekimae','中央','gourmet','和食',''),
('sba6e73e6','笏谷そば だるまや西武店','しゃくだにそば だるまやせいぶてん',null,'ekimae','中央','gourmet','そば・うどん',''),
('s9c7f80f2','芝寿し 福井西武店','しばすし ふくいせいぶてん',null,'ekimae','中央','gourmet','和食',''),
('sdaf8623c','華家','はないえ',null,'ekimae','大手','gourmet','和食',''),
('s331b3393','葵納豆料理店','あおいなっとうりょうりてん',null,'ekimae','照手','gourmet','和食',''),
('sf92fe821','農協のおむすび大手町店','のうきょうのおむすびおおてまちてん',null,'ekimae','大手','gourmet','和食',''),
('sdcf3c594','野のや','ののや',null,'ekimae','中央','gourmet','和食',''),
('s897b57f1','鮨志乃介','すししのすけ',null,'ekimae','中央','gourmet','寿司・海鮮',''),
('sc9530b9a','あさひそば 本店','あさひそば ほんてん',null,'ekimae','中央','gourmet','そば・うどん',''),
('sa94353fd','越前つるきそば本店','えちぜんつるきそばほんてん',null,'ekimae','中央','gourmet','そば・うどん','tsurukisoba'),
('s80891f7c','お好み焼き エミ','おこのみやき えみ',null,'ekimae','大手','gourmet','和食',''),
('s23391263','広島風お好み焼き・つけ麺 一期一会','ひろしまかぜおこのみやき つけめん いちごいちえ',null,'ekimae','日之出','gourmet','ラーメン',''),
('s32b00400','とんかつ そば 吉ちょう','とんかつ そば きちちょう',null,'ekimae','大手','gourmet','そば・うどん',''),
('sf5ddf8e7','むろまち','むろまち',null,'ekimae','中央','gourmet','焼肉・肉料理',''),
('saf5a7fa3','富士喜 MINIE店','ふじき minieてん',null,'ekimae','中央','gourmet','焼肉・肉料理','fujiki_2020'),
('s1dfd4d1a','熟成かつ 天膳 ハピリン店','じゅくせいかつ てんぜん はぴりんてん',null,'ekimae','中央','gourmet','焼肉・肉料理','fukui.tonkatu.amazen'),
('s3257e875','RICE BAR CRAFT SAKE LABO','rice bar craft sake labo',null,'ekimae','中央','night','バー','bridgelabo_ricebar'),
('s447c7347','お食事処 飛彈','おしょくじどころ ひだ',null,'ekimae','中央','gourmet','和食','hida_fukui'),
('sb134d23b','しゃぶしゃぶ・鍋・割烹 銀座','しゃぶしゃぶ なべ かっぽう ぎんざ',null,'ekimae','大手','gourmet','和食',''),
('s68443c09','まちDeli かくれわ食堂','まちdeli かくれわしょくどう',null,'ekimae','中央','gourmet','和食','kakurewa2016'),
('sd2f23010','一品料理 四十萬','いっぴんりょうり しじま',null,'ekimae','大手','gourmet','和食',''),
('s00743a4b','旬魚とおでん 味美家','しゅんぎょとおでん あじよしいえ',null,'ekimae','日之出','gourmet','寿司・海鮮',''),
('s3f9381d5','浜町 かつき','はまちょう かつき',null,'ekimae','中央','gourmet','焼肉・肉料理',''),
('sa173db6f','福い','ふくい',null,'ekimae','中央','gourmet','和食','courtyard_by_marriott_fukui'),
('s304f9740','福井フェニックスホテル 和食・茶房 養浩館','ふくいふぇにっくすほてる わしょく さぼう ようこうかん',null,'ekimae','大手','gourmet','和食',''),
('sfa13ee3a','紋や','もんや',null,'ekimae','中央','gourmet','和食','monya_141117'),
('s027d4522','蟹と海鮮 ぼんた','かにとかいせん ぼんた',null,'ekimae','中央','gourmet','寿司・海鮮','kanibonta'),
('s11804aca','越前がに・旬のお料理 らでん','えちぜんがに じゅんのおりょうり らでん',null,'ekimae','中央','gourmet','和食','raden0428'),
('s37eaeae8','越前蕎麦・お食事処 花ひらく','えちぜんそば おしょくじどころ はなひらく',null,'ekimae','大手','gourmet','そば・うどん',''),
('sf813e082','魚善','うおぜん',null,'ekimae','大手','gourmet','寿司・海鮮',''),
('s87ba4420','ほまれ寿司','ほまれすし',null,'ekimae','中央','gourmet','寿司・海鮮','homaresushi'),
('s2ba55054','鮨 仲島','すし なかしま',null,'ekimae','中央','gourmet','寿司・海鮮','sushi_nakajima_fukui'),
('sf5f397ee','鮨清','すしきよし',null,'ekimae','中央','gourmet','寿司・海鮮','sei2025525'),
('s0c41fd45','割烹料亭 かき恭','かっぽうりょうてい かきやす',null,'ekimae','中央','gourmet','和食',''),
('sae63d11b','和の食 忠兵衛','わのしょく ちゅうべえ',null,'ekimae','中央','gourmet','和食',''),
('s5dd435e4','和心味NAGOMI たち花','わこころあじnagomi たちはな',null,'ekimae','大手','gourmet','和食',''),
('sb3b45b94','料亭 開花亭','りょうてい かいかてい',null,'ekimae','中央','gourmet','和食',''),
('sdb36d8c6','日本料理 越前がに 浜町 緒ばた','にっぽんりょうり えちぜんがに はまちょう おばた',null,'ekimae','中央','gourmet','和食','obata_hamamachi'),
('s9bee29d3','旬味 泰平','じゅんあじ たいへい',null,'ekimae','中央','gourmet','和食',''),
('s07d13a5e','楽tei なか田”','らくtei なかた',null,'ekimae','中央','gourmet','和食','rakutei_nakada'),
('se6f0dda9','美食 恵長庵 まんもと','びしょく めぐみちょうあん まんもと',null,'ekimae','日之出','gourmet','和食',''),
('se0f468ca','開花亭 sou-an','かいかてい sou an',null,'ekimae','中央','gourmet','和食',''),
('s641ed098','香爐園','こうろその',null,'ekimae','中央','gourmet','和食','fukui.kouroen'),
('s69749d6a','kitchen 和','kitchen わ',null,'ekimae','大手','gourmet','和食','kitchennagomi2023111'),
('sf0f71534','お食事処 ほていや','おしょくじどころ ほていや',null,'ekimae','中央','gourmet','和食',''),
('scf8cca10','ふくいのこめとだし まるしん','ふくいのこめとだし まるしん',null,'ekimae','中央','gourmet','和食','marushin_kometodashi'),
('s86f800ed','凸凹29ごはん 福井市役所地下','でこぼこ29ごはん ふくいしやくしょちか',null,'ekimae','大手','gourmet','和食',''),
('s1c1b7239','福井肉食堂','ふくいにくしょくどう',null,'ekimae','中央','gourmet','焼肉・肉料理','kurufu_nikusyokudo'),
('sa2a3ccc4','福福茶屋','ふくふくちゃや',null,'ekimae','中央','gourmet','和食','hukubuku2929'),
('s082726aa','BLUESTOCKING','bluestocking',null,'ekimae','中央','gourmet','カフェ・スイーツ','bluestocking.seibu'),
('s0e036df3','CTS(シータス)','cts しーたす',null,'ekimae','照手','gourmet','カフェ・スイーツ','cts_coffee_to_sand'),
('s437b3812','Cafe CoCotte','cafe cocotte',null,'ekimae','中央','gourmet','カフェ・スイーツ','cafecocotte420'),
('s40dd3cf5','Cafe リンデン','cafe りんでん',null,'ekimae','大手','gourmet','カフェ・スイーツ','echizen_fukui_artmuseum_'),
('s0068cc18','NIVI','nivi',null,'ekimae','中央','gourmet','カフェ・スイーツ','nivi_specialty_coffee'),
('se8ee5656','Organic Vegan cafe 深緑','organic vegan cafe しんりょく',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('sc7e29544','papillote','papillote',null,'ekimae','中央','gourmet','カフェ・スイーツ','papillote_fukui'),
('s72772f7f','さんじのおやつ 観光交流センター店','さんじのおやつ かんこうこうりゅうせんたーてん',null,'ekimae','手寄','gourmet','カフェ・スイーツ','sanjinooyatsu_fk1001'),
('sea1d495e','まンまや おちょkitchen','まんまや おちょkitchen',null,'ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s8f66dd35','イタリアン・トマト CafeJr. 福井西武店','いたりあん とまと cafejr ふくいせいぶてん',null,'ekimae','中央','gourmet','イタリアン・フレンチ',''),
('sd708f1b4','点 葉巻室 福井店','てん はまきしつ ふくいてん',null,'ekimae','中央','gourmet','カフェ・スイーツ','ten_cigar_room_fukui'),
('sdcaf3a90','紅茶のお店 RanaTea','こうちゃのおてん ranatea',null,'ekimae','中央','gourmet','カフェ・スイーツ','ranatea_fukui'),
('sb263c571','茶楽 かぐや 西武店','ちゃらく かぐや せいぶてん',null,'ekimae','中央','gourmet','カフェ・スイーツ','saraku_kaguya'),
('s2fdfd97e','カフェテラス','かふぇてらす',null,'ekimae','中央','gourmet','カフェ・スイーツ',''),
('s5338c029','カラオケ喫茶 笑','からおけきっさ わらい',null,'ekimae','日之出','gourmet','カフェ・スイーツ',''),
('sf16f84cd','フルーツパーラー 果樹園','ふるーつぱーらー かじゅえん',null,'ekimae','中央','gourmet','カフェ・スイーツ','fruit_no_umeda_official'),
('s196d83f4','マギーズファーム','まぎーずふぁーむ',null,'ekimae','中央','gourmet','カフェ・スイーツ','maggies_farm1986'),
('s0d9cf47f','喫茶 珈琲壺 〜コーヒーぽっと〜','きっさ こーひーつぼ こーひーぽっと',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('s8b76fe09','Churrascaria ban(シュラスカリア バン) 福井店','churrascaria ban ふくいてん しゅらすかりあ ばん',null,'ekimae','中央','gourmet','居酒屋',''),
('sb67ea96d','個室居酒屋 葵屋-あおいや- 福井駅前店','こしついざかや あおいや あおいや ふくいえきまえてん',null,'ekimae','中央','gourmet','居酒屋',''),
('s850722a5','おふくろの味こころ','おふくろのあじこころ',null,'ekimae','大手','gourmet','居酒屋',''),
('s67de7438','のんのん','のんのん',null,'ekimae','中央','gourmet','居酒屋',''),
('s65d5344b','のんべえよしき','のんべえよしき',null,'ekimae','大手','gourmet','居酒屋',''),
('sf95c753b','まごころ','まごころ',null,'ekimae','中央','gourmet','居酒屋',''),
('s333dfc62','みなり','みなり',null,'ekimae','大手','gourmet','居酒屋',''),
('s3cbdc57e','もみじ 福井駅前店','もみじ ふくいえきまえてん',null,'ekimae','中央','gourmet','居酒屋',''),
('sf1a7d4f6','ろ組 福井駅前店','ろくみ ふくいえきまえてん',null,'ekimae','中央','gourmet','居酒屋',''),
('sdefd9b7f','ブラスリー河合','ぶらすりーかわい',null,'ekimae','中央','gourmet','居酒屋',''),
('sd3cdde76','三代目 鳥メロ 福井駅前店','さんだいめ とりめろ ふくいえきまえてん',null,'ekimae','中央','gourmet','居酒屋',''),
('sd40f6f26','個室居酒屋 くいもの屋わん 福井駅前店','こしついざかや くいものやわん ふくいえきまえてん',null,'ekimae','中央','gourmet','居酒屋',''),
('s90c2ae57','六兵衛','ろくべえ',null,'ekimae','中央','gourmet','居酒屋',''),
('sd01dbf56','割烹 桝酒','かっぽう ますさけ',null,'ekimae','大手','gourmet','居酒屋',''),
('s098b101b','千本','せんぼん',null,'ekimae','中央','gourmet','居酒屋',''),
('sa4f16f4c','味の王様ガレリア店','あじのおうさまがれりあてん',null,'ekimae','中央','gourmet','居酒屋',''),
('safba9b18','土鍋ご飯《米と魚 たて涌》','どなべごめし こめとさかな たてゆう',null,'ekimae','中央','gourmet','寿司・海鮮','tatewaki_kometosakana'),
('s847b5112','大衆とり酒場 とりいちず 福井駅前店','たいしゅうとりさかば とりいちず ふくいえきまえてん',null,'ekimae','中央','gourmet','居酒屋','toriichizu_mania'),
('s8cc017e9','安楽','あんらく',null,'ekimae','大手','gourmet','居酒屋',''),
('s13a09f65','寿司・地酒 はやし','すし じざけ はやし',null,'ekimae','大手','gourmet','寿司・海鮮',''),
('s097c40a1','寿司和食処 わだつみ','すしわしょくどころ わだつみ',null,'ekimae','大手','gourmet','寿司・海鮮',''),
('s96ca45ee','小料理のむ喜 優','しょうりょうりのむき ゆう',null,'ekimae','中央','gourmet','居酒屋',''),
('sea741e8d','山がっちゃん家の台所','やまがっちゃんいえのだいどころ',null,'ekimae','大手','gourmet','居酒屋',''),
('s1853373d','横浜天下鳥 福井駅前店','よこはまてんかとり ふくいえきまえてん',null,'ekimae','中央','gourmet','居酒屋',''),
('s333a28c2','然の家 味彩','ぜんのいえ あじさい',null,'ekimae','中央','gourmet','居酒屋',''),
('s47fbad00','焼肉 肉鍋 肉吟 福井駅前店','やきにく にくなべ にくぎん ふくいえきまえてん',null,'ekimae','中央','gourmet','焼肉・肉料理',''),
('se04557f5','玄達市場','げんたつしじょう',null,'ekimae','手寄','gourmet','居酒屋',''),
('s04b85b8e','目利きの銀次 福井西口駅前店','めきききのぎんじ ふくいにしぐちえきまえてん',null,'ekimae','大手','gourmet','居酒屋',''),
('sa73580d4','福井名物お刺身&豚骨おでん 酒処JET','ふくいめいぶつおさしみ とんこつおでん さけどころjet',null,'ekimae','日之出','gourmet','居酒屋',''),
('s7cbf20df','菜香楼 くるふ福井駅店','なかおりろう くるふふくいえきてん',null,'ekimae','中央','gourmet','居酒屋',''),
('s21231265','越前地魚とおでん酒場 鮨とおでん','えちぜんじざかなとおでんさかば すしとおでん',null,'ekimae','中央','gourmet','寿司・海鮮',''),
('s583d78f9','越前若狭の旬と地酒 頂き枡 福井駅前東口店','えちぜんわかさのじゅんとじざけ いただきます ふくいえきまえひがしぐちてん',null,'ekimae','日之出','gourmet','居酒屋',''),
('s2298f9e8','越前魚酒 ほやほ家','えちぜんさかなさけ ほやほいえ',null,'ekimae','大手','gourmet','寿司・海鮮',''),
('s0000e279','酒菜夜','しゅさいよる',null,'ekimae','中央','gourmet','居酒屋',''),
('sf2a68918','魚河岸直営 いけす海鮮 ろ組くるふ福井駅店','うおがしちょくえい いけすかいせん ろくみくるふふくいえきてん',null,'ekimae','中央','gourmet','寿司・海鮮',''),
('s3ff73c5b','日本料理 橘','にっぽんりょうり たちばな',null,'ekimae','大手','gourmet','和食',''),
('sbfc0e5ca','とみや','とみや',null,'ekimae','中央','gourmet','洋食',''),
('s6831efc4','キンイロキッチンアオッサ店','きんいろきっちんあおっさてん',null,'ekimae','手寄','gourmet','洋食',''),
('s0ff080c0','シュバルージュ','しゅばるーじゅ',null,'ekimae','手寄','gourmet','居酒屋',''),
('s177662fe','ムサシノ軒','むさしのけん',null,'ekimae','手寄','gourmet','洋食',''),
('sdeccc578','ラッキー食堂1階レストラン部','らっきーしょくどう1かいれすとらんぶ',null,'ekimae','中央','gourmet','洋食',''),
('s6b8af86d','名産工房・旬','めいさんこうぼう じゅん',null,'ekimae','中央','gourmet','洋食',''),
('s1268ca15','日下部','くさかべ',null,'ekimae','中央','gourmet','洋食',''),
('seb4666bd','福井ワシントンホテル 銀座','ふくいわしんとんほてる ぎんざ',null,'ekimae','大手','gourmet','洋食',''),
('s47640b37','福井厚生年金会館','ふくいこうせいねんきんかいかん',null,'ekimae','手寄','gourmet','洋食',''),
('s3faa3277','赤茄子亭','あかなすてい',null,'ekimae','日之出','gourmet','洋食',''),
('s7daaf531','鉄板料理 薫風','てっぱんりょうり くんぷう',null,'ekimae','日之出','gourmet','洋食',''),
('s1fb95026','Alfredo','alfredo',null,'ekimae','中央','gourmet','イタリアン・フレンチ','alfredo_fukui'),
('s4bd2d309','Ristorante CUCINA','ristorante cucina',null,'ekimae','中央','gourmet','イタリアン・フレンチ','ristorante_cucina_1991'),
('s927e1e54','Sincere Lily','sincere lily',null,'ekimae','中央','gourmet','イタリアン・フレンチ','sincerelily.fukui'),
('s21cb020b','イタリア食堂ITSUKI','いたりあしょくどうitsuki',null,'ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s52f71c78','サイゼリヤ 福井駅前店','さいぜりや ふくいえきまえてん',null,'ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s4af0766e','石窯食堂 Tsumugi(つむぎ)','いしがましょくどう tsumugi つむぎ','2026-06-21'::date,'ekimae','大手','gourmet','イタリアン・フレンチ','tsumugi_fukui'),
('s83ecf4d0','粟樹楼','あわきろう',null,'ekimae','中央','gourmet','イタリアン・フレンチ',''),
('se32d8474','モンシェルトントンカトー','もんしぇるとんとんかとー',null,'ekimae','中央','gourmet','焼肉・肉料理',''),
('s4b6df614','石窯焼 時ノ鐘','いしがまやき ときのかね',null,'ekimae','中央','gourmet','焼肉・肉料理','tokinokane29'),
('s81e6bc1f','鉄板焼き 紡ぐ','てっぱんやきき つむぐ',null,'ekimae','大手','gourmet','焼肉・肉料理','tsumug_1116'),
('sd0520d08','Bistro & Bar GLOUTONNE','bistro bar gloutonne','2026-04-15'::date,'ekimae','中央','night','バー',''),
('sfbc6d733','Brasserie Lou','brasserie lou',null,'ekimae','中央','gourmet','イタリアン・フレンチ','brasserie_lou'),
('s30474fd0','Fukui French Aujus(オージュ)','fukui french aujus おーじゅ',null,'ekimae','中央','gourmet','イタリアン・フレンチ','aujus_fukui'),
('s8dd0e3c0','IRISER','iriser',null,'ekimae','大手','gourmet','イタリアン・フレンチ','iriser.fukui'),
('s35ee8df9','RESTAURANT OTSUKA','restaurant otsuka',null,'ekimae','大手','gourmet','イタリアン・フレンチ','restaurantotsuka'),
('sf09a0dcd','Salon De Chef  NAKAO','salon de chef nakao',null,'ekimae','大手','gourmet','イタリアン・フレンチ',''),
('s628e432e','ULO','ulo',null,'ekimae','中央','gourmet','イタリアン・フレンチ','ulo_fukui'),
('sfe2ad9a7','la table de Roche(ロッシュ)','la table de roche ろっしゅ',null,'ekimae','手寄','gourmet','イタリアン・フレンチ',''),
('s55478b75','グリル葵','ぐりるあおい',null,'ekimae','大手','gourmet','イタリアン・フレンチ',''),
('s76637454','サラマンジェフ','さらまんじぇふ',null,'ekimae','中央','gourmet','イタリアン・フレンチ','salle_a_mangerf'),
('sdb8de789','シェ・サカイ','しぇ さかい',null,'ekimae','日之出','gourmet','イタリアン・フレンチ',''),
('s57eb7bb2','ビストロ後藤','びすとろごとう',null,'ekimae','中央','gourmet','イタリアン・フレンチ','bistro_goto_goto510'),
('sb5b3b483','フランス酒場 Antique','ふらんすさかば antique',null,'ekimae','中央','gourmet','居酒屋','antique__fukui'),
('s514108e2','Substance','substance',null,'ekimae','中央','gourmet','洋食','courtyard_by_marriott_fukui'),
('s90da58ca','キッチントリアージュ','きっちんとりあーじゅ',null,'ekimae','中央','gourmet','洋食',''),
('sa5d3f7cc','二ノ丸グリル','にのまるぐりる',null,'ekimae','大手','gourmet','洋食',''),
('s7d628105','吉野寿司','よしのすし',null,'ekimae','中央','gourmet','寿司・海鮮','fukui_yoshinozushi'),
('sb5bcd9fa','焼肉ホルモン はらたん 福井駅前店','やきにくほるもん はらたん ふくいえきまえてん',null,'ekimae','中央','gourmet','焼肉・肉料理',''),
('sd63ab7c5','そば処 三国屋','そばどころ みくにや',null,'ekimae','大手','gourmet','そば・うどん',''),
('sb68ff2b6','今庄そば 福井駅コンコース店','いまじょうそば ふくいえきこんこーすてん',null,'ekimae','中央','gourmet','そば・うどん',''),
('s71f5a2b3','あみだそば 福の井','あみだそば ふくのい',null,'ekimae','中央','gourmet','そば・うどん',''),
('s6a9c9e23','あみだそば 遊歩庵','あみだそば ゆうほあん',null,'ekimae','中央','gourmet','そば・うどん','amidasoba'),
('sb13e7aef','福そば','ふくそば',null,'ekimae','中央','gourmet','そば・うどん',''),
('s9356b702','蕎麦Dining 一福','そばdining いちふく',null,'ekimae','中央','gourmet','そば・うどん','ippuku129'),
('sa2fb7beb','福井名物ずわい蟹料理 こまつや','ふくいめいぶつずわいかにりょうり こまつや',null,'ekimae','照手','gourmet','寿司・海鮮',''),
('sde46651d','御菓子司 あまとや','おかしつかさ あまとや',null,'ekimae','つくも','gourmet','カフェ・スイーツ',''),
('sc83ffc72','御菓子司 森八大名閣','おかしつかさ もりはちだいみょうかく',null,'ekimae','大手','gourmet','カフェ・スイーツ',''),
('sb541e4f7','村中甘泉堂本店/パティスリーKANSENDO','むらなかかんせんどうほんてん ぱてぃすりーkansendo',null,'ekimae','中央','gourmet','その他',''),
('sf217005b','羽二重餅總本舗 松岡軒','はぶたえもちそうほんぽ まつおかけん',null,'ekimae','中央','gourmet','その他','matsuokaken.habutaemochi'),
('s70885d63','KAKETUKE','kaketuke',null,'ekimae','中央','gourmet','居酒屋','kaketuke_fukui'),
('se183111c','お酒とおばんざい ななと実','おさけとおばんざい ななとみ',null,'ekimae','大手','gourmet','居酒屋','nanatomi_sachiko'),
('sbc95f6c8','きはちらくはち 駅前店','きはちらくはち えきまえてん',null,'ekimae','大手','gourmet','居酒屋','kihachirakuhachi'),
('s2ec1c847','ろばた焼 弥吉 駅前店','ろばたやき やきち えきまえてん',null,'ekimae','大手','gourmet','居酒屋',''),
('sf5065559','名古屋コーチンの 翠翔 福井駅前店','なごやこーちんの すいしょう ふくいえきまえてん',null,'ekimae','大手','gourmet','居酒屋','_suisyooo'),
('saadbc958','呑み処 たけうち','のみどころ たけうち',null,'ekimae','大手','gourmet','居酒屋',''),
('sf60bef90','居酒屋 竜の髭','いざかや りゅうのひげ',null,'ekimae','大手','gourmet','居酒屋',''),
('s4c30b710','旬香逎燈 煙や','しゅんこうしゅうとう けむりや',null,'ekimae','大手','gourmet','居酒屋','kemuri_ya'),
('s473083b7','沖縄料理 南風 ぱいかじ','おきなわりょうり はえ ぱいかじ',null,'ekimae','中央','gourmet','居酒屋','okinawaryouripaikazi'),
('s34c551c2','炭火焼の店 織々屋','すみびやきのてん しょく や',null,'ekimae','中央','gourmet','居酒屋',''),
('sa671fcff','石田屋','いしだや',null,'ekimae','大手','gourmet','居酒屋',''),
('sfa8fce77','越前鮮魚と炭火焼 炭と魚 福井駅前店','えちぜんせんぎょとすみびやき すみとさかな ふくいえきまえてん',null,'ekimae','中央','gourmet','寿司・海鮮','sumi.to.sakana'),
('s8942d76e','酒場 丸子','さかば まるこ',null,'ekimae','中央','gourmet','居酒屋','sakaba_maruko'),
('s568c1b8b','酒季織々 旨い肴と和み酒 錦輝','さけきしょく うまいさかなとなごみさけ きんき',null,'ekimae','大手','gourmet','居酒屋','nishikifukui'),
('s799a6b23','飲み喰い処 和楽路','のみくいどころ わがくみち',null,'ekimae','中央','gourmet','居酒屋',''),
('scc22d7b3','骨付鳥、からあげ、ハイボール がブリチキン。 福井駅前店','ほねつきとり からあげ はいぼーる がぶりちきん ふくいえきまえてん',null,'ekimae','中央','gourmet','居酒屋','gabukichi_gaburichicken'),
('s0e47f167','魚のうまい店 寿司居酒屋 かんきち 福井駅前店','さかなのうまいてん すしいざかや かんきち ふくいえきまえてん',null,'ekimae','大手','gourmet','寿司・海鮮','kankichi_291'),
('sf2bd41d7','魚六(ウオロック)','さかなろく うおろっく',null,'ekimae','中央','gourmet','寿司・海鮮','uorock291'),
('seb2a4480','鶏屋 塚田農場 福井駅前店','にわとりや つかだのうじょう ふくいえきまえてん',null,'ekimae','中央','gourmet','居酒屋','fukui_tsukadanojo'),
('sa9f71617','串カツ田中 福井駅前店','くしかつたなか ふくいえきまえてん',null,'ekimae','大手','gourmet','焼鳥・串','kushikatsu_tanaka'),
('sde4a6298','串カツ酒場 ナニワ屋 福井駅前店','くしかつさかば なにわや ふくいえきまえてん',null,'ekimae','中央','gourmet','焼鳥・串',''),
('se898d0cb','炭・串焼 べんがら屋','すみ くしやき べんがらや',null,'ekimae','中央','gourmet','焼鳥・串',''),
('s5a9ab9f2','焼き鳥 八穴','やきとり はちあな',null,'ekimae','大手','gourmet','焼鳥・串','hachinoana_yakitori'),
('sebc25d2d','スナックおすみ','すなっくおすみ',null,'ekimae','中央','night','スナック・ラウンジ',''),
('s2a51afb8','G’sBAR 0821','g sbar 0821',null,'ekimae','中央','night','スナック・ラウンジ',''),
('sdd4a89da','Santana','santana',null,'ekimae','中央','night','スナック・ラウンジ',''),
('sefb719c7','あずま','あずま',null,'ekimae','手寄','night','スナック・ラウンジ',''),
('sd09a9257','どんどん','どんどん',null,'ekimae','中央','night','スナック・ラウンジ',''),
('sc2625260','バレッタ','ばれった',null,'ekimae','中央','night','スナック・ラウンジ',''),
('s326db697','パリジェンヌ','ぱりじぇんぬ',null,'ekimae','中央','night','スナック・ラウンジ',''),
('s38f5773f','ミュージックスペース シューハウス','みゅーじっくすぺーす しゅーはうす',null,'ekimae','中央','night','スナック・ラウンジ',''),
('s8c4f966a','笑殿','わらいどの',null,'ekimae','中央','night','スナック・ラウンジ',''),
('sabb6da8c','紫苑','しおん',null,'ekimae','中央','night','スナック・ラウンジ',''),
('s263b15fb','BAR 月下(バーげっか)','bar げっか ばーげっか',null,'ekimae','中央','night','バー','gekka_fukui'),
('s3b14b9c6','Bistro&Bar Bono(ボーノ)','bistro bar bono ぼーの',null,'ekimae','中央','night','バー','foop.entertainment.service'),
('sd259ece0','バーこうみんかん','ばーこうみんかん',null,'ekimae','中央','night','バー','kominkan2.0'),
('s3322a85d','ダーツ&キッチン BAD BIRDY(バッド バーディ)','だーつ きっちん bad birdy ばっど ばーでぃ',null,'ekimae','大手','night','バー','bad_birdy_fukui'),
('s4c8c15d7','ミワンソン','みわんそん',null,'ekimae','中央','night','バー','miwanseong.cafe'),
('sba771388','浜町安文酒店','はまちょうやすぶみさけてん',null,'ekimae','中央','night','バー',''),
('s5e344923','ハイボール ビール おもてなし OSPITALITA(オスピタリタ)','はいぼーる びーる おもてなし ospitalita おすぴたりた',null,'ekimae','中央','night','バー','ospitalita_fukui'),
('sc9e51efe','たこ焼きバー たこパ','たこやきばー たこぱ',null,'ekimae','中央','night','バー','takopa_fukui'),
('s5301b782','炭と肉。','すみとにく',null,'ekimae','中央','gourmet','焼肉・肉料理','sumitoniku'),
('s49d8ac83','旬ふく食彩 よしな','じゅんふくしょくさい よしな',null,'ekimae','大手','gourmet','和食','yoshina_624'),
('s51b90fcf','くずし割烹 ぼんた','くずしかっぽう ぼんた',null,'ekimae','中央','gourmet','和食',''),
('s804d5364','釣り人しまちゃん','つりびとしまちゃん',null,'ekimae','中央','gourmet','寿司・海鮮','tsuribito_shimachan'),
('s0663cb88','日々','ひび',null,'ekimae','中央','gourmet','和食','hamamachi.hibi'),
('s4c9fd68e','味処 おたん','あじどころ おたん',null,'ekimae','中央','gourmet','和食',''),
('s5e1e30c7','CAFE & BAR PRONTO 福井駅前店','cafe bar pronto ふくいえきまえてん',null,'ekimae','中央','night','バー','pronto___official'),
('se36ce584','GINCHIYO','ginchiyo',null,'ekimae','中央','gourmet','居酒屋','ginchiyo_fukui'),
('s69548fc0','OUR BREWING TAPROOM','our brewing taproom',null,'ekimae','中央','gourmet','居酒屋','ourbrewing'),
('sbad2abeb','The best space BAR FUKU','the best space bar fuku',null,'ekimae','中央','night','バー','t.b.s.barfuku'),
('s1c709fa5','eclat(エクラ)','eclat えくら',null,'ekimae','大手','gourmet','居酒屋','eclat__2023'),
('s8962fe8f','なごとん','なごとん',null,'ekimae','中央','gourmet','居酒屋',''),
('s1b2f1de2','パブおいち・深夜食堂','ぱぶおいち しんやしょくどう',null,'ekimae','中央','night','スナック・ラウンジ','nishikou'),
('sedf01bb3','歌謡喫茶 ユミ','かようきっさ ゆみ',null,'ekimae','中央','gourmet','居酒屋','kayoukissa_yumi'),
('s8b4f09e0','福井屋台村','ふくいやたいむら',null,'ekimae','日之出','gourmet','居酒屋','fukui_yataimura'),
('sd22f874a','オステリア ダ シルバーノ','おすてりあ だ しるばーの',null,'ekimae','中央','night','バー','osteria_da_silvano_fukui'),
('s93af7e23','肉はナカノ','にくはなかの',null,'ekimae','中央','gourmet','焼肉・肉料理','nikuhanakano_minie'),
('s5f15823c','兄ん家','あにんいえ',null,'ekimae','大手','gourmet','寿司・海鮮','kaisen343'),
('s4d946582','八兆屋駅の蔵 福井駅店','はちちょうやえきのくら ふくいえきてん',null,'ekimae','中央','gourmet','寿司・海鮮',''),
('sad14b649','越前魚問屋 蟹ヱ門','えちぜんさかなとんや かにゑもん',null,'ekimae','中央','gourmet','寿司・海鮮','kaniemon_minie'),
('s4357786e','やきとりの名門 秋吉 福井駅前店','やきとりのめいもん あきよし ふくいえきまえてん',null,'ekimae','大手','gourmet','焼鳥・串',''),
('s4bb1b7bd','炭火焼鳥 鶏次','すみびやきとり にわとりつぎ',null,'ekimae','中央','gourmet','焼鳥・串','sumibiyakitori_keiji'),
('s443e8c43','SIERRA MADRE','sierra madre',null,'ekimae','中央','night','バー',''),
('s88f82896','WINE食堂 TAMAMIN13','wineしょくどう tamamin13',null,'ekimae','大手','night','バー','tamamisongjing'),
('s9d1bff03','ちょい呑み処 ババズ','ちょいのみどころ ばばず',null,'ekimae','中央','night','バー','ba__buzz'),
('sd5219586','BAR HIDING PLACE','bar hiding place',null,'ekimae','中央','night','バー','bar_hiding_place'),
('s2e74fe26','BAR 堀川','bar ほりかわ',null,'ekimae','中央','night','バー',''),
('scd433ac6','Bar & Restaurant Blue Light Cafe','bar restaurant blue light cafe',null,'ekimae','中央','night','バー',''),
('s0d5a9f96','Bar UNCLE(アンクル)','bar uncle あんくる',null,'ekimae','大手','night','バー',''),
('sbe1f85f1','CINEMA "street theater"','cinema street theater',null,'ekimae','中央','night','バー','cinema_fukui'),
('se76e2581','Craft Beer Bar アワタチ','craft beer bar あわたち',null,'ekimae','中央','night','バー','beer_awatachi'),
('s680aa43b','GIORNO Fukui,','giorno fukui',null,'ekimae','中央','night','バー','giorno_fukui'),
('s2f13d702','GOLF & DARTS BAR TRUMP','golf darts bar trump',null,'ekimae','大手','night','バー','trump_golfanddarts_bar'),
('s41006851','ODDS POKER ROOM','odds poker room',null,'ekimae','中央','night','バー','odds_poker'),
('sfaf58ccf','Rum Fire(ラムファイヤー)','rum fire らむふぁいやー',null,'ekimae','中央','night','バー','fumfirefukui'),
('s6b4b3c83','SHIMA(シマ)','shima しま',null,'ekimae','中央','night','バー','shima_coffee_sake'),
('s304392ca','THE BAR 灯火','the bar とうか',null,'ekimae','大手','night','バー','bar_tomoshibi_fukui'),
('se613d0f1','おさけとワイン みずもと','おさけとわいん みずもと',null,'ekimae','中央','night','バー','mizumoto_sake'),
('s8e6ca65b','アイリッシュバー Shelbourne(シェルボーン)','あいりっしゅばー shelbourne しぇるぼーん',null,'ekimae','中央','night','バー','shelbourne.ib'),
('s3f5afeee','アジアンランチビュッフェ','あじあんらんちびゅっふぇ',null,'ekimae','中央','night','バー','courtyard_by_marriott_fukui'),
('s59aa7397','ワインバル ヴェレゾン','わいんばる ゔぇれぞん',null,'ekimae','大手','night','バー',''),
('s678fdcab','屋上BAR BRIDGE','おくじょうbar bridge',null,'ekimae','中央','night','バー',''),
('s1652a223','日本酒BAR Room','にほんしゅbar room',null,'ekimae','中央','night','バー','beer_awatachi'),
('s2db8deed','わらび 福井駅前店','わらび ふくいえきまえてん',null,'ekimae','中央','gourmet','居酒屋','izakaya_warabi'),
('s7abd063e','味とら','あじとら',null,'ekimae','大手','gourmet','居酒屋',''),
('s3e27348c','味の王様','あじのおうさま',null,'ekimae','大手','gourmet','居酒屋','aji_ou'),
('s4fecae1c','味処 庄屋','あじどころ しょうや',null,'ekimae','中央','gourmet','居酒屋','ajidokoro_syoya'),
('s4b7cca49','松田屋','まつだや',null,'ekimae','日之出','gourmet','居酒屋',''),
('sc37eaa46','味の清八','あじのせいはち',null,'ekimae','中央','gourmet','焼鳥・串',''),
('s3005c9ff','焼肉ほるもんサンマルコ','やきにくほるもんさんまるこ',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('sbd3dd6a4','金福','きんぷく',null,'katamachi','順化','gourmet','その他',''),
('s43b636a5','ぼてじゃこ福井片町店','ぼてじゃこふくいかたまちてん',null,'katamachi','順化','gourmet','その他',''),
('s2ee77113','よしな片町店','よしなかたまちてん',null,'katamachi','順化','gourmet','その他',''),
('se99600ad','山中','さんちゅう',null,'katamachi','順化','gourmet','その他',''),
('s18e7a90b','&Room','room',null,'katamachi','順化','gourmet','その他',''),
('sa4f29e79','BANBAN','banban',null,'katamachi','順化','gourmet','その他',''),
('s317ffbcb','CLUB・Queen’s','club queen s',null,'katamachi','順化','night','スナック・ラウンジ',''),
('saa9ac2b9','CREAM','cream',null,'katamachi','順化','gourmet','その他',''),
('s91eefd77','ELAN','elan',null,'katamachi','順化','gourmet','その他',''),
('sc90cd7da','JagBAR','jagbar',null,'katamachi','順化','gourmet','その他',''),
('s65c28a30','JuGo','jugo',null,'katamachi','順化','gourmet','その他',''),
('s867c97ed','LeapDay','leapday',null,'katamachi','順化','gourmet','その他',''),
('s9e448f01','NewYork・ニューヨーク','newyork にゅーよーく',null,'katamachi','順化','gourmet','その他',''),
('s325178f0','RoseRed','rosered',null,'katamachi','順化','gourmet','その他',''),
('sb7f6f7c1','Startin’','startin',null,'katamachi','順化','gourmet','その他',''),
('s59952785','TOYSBOX','toysbox',null,'katamachi','順化','gourmet','その他',''),
('s13061b4a','Yダッシュ','yだっしゅ',null,'katamachi','順化','gourmet','その他',''),
('s14a917ce','abuku','abuku',null,'katamachi','順化','gourmet','その他',''),
('s69a04e29','きぶね','きぶね',null,'katamachi','順化','gourmet','その他',''),
('s3a58059c','さなえ','さなえ',null,'katamachi','順化','gourmet','その他',''),
('sc84a2afd','その字 弐','そのじ に',null,'katamachi','順化','gourmet','その他',''),
('s8c934cc7','そば茶屋まつき','そばちゃやまつき',null,'katamachi','順化','gourmet','そば・うどん',''),
('se63cf918','とび田','とびた',null,'katamachi','順化','gourmet','その他',''),
('s8486f4ff','どん茶屋御食事処','どんちゃやみけことどころ',null,'katamachi','順化','gourmet','その他',''),
('sbce0670a','みやぎ(宮妓)','みやぎ みやき',null,'katamachi','順化','gourmet','その他',''),
('s428d8297','アフロディーテ','あふろでぃーて',null,'katamachi','順化','gourmet','その他',''),
('sb6c24e6d','アミーチ','あみーち',null,'katamachi','順化','gourmet','その他',''),
('s8b37d3b4','アリーズバー','ありーずばー',null,'katamachi','順化','night','バー',''),
('s129ac94d','オー・ド・ヴィー','おー ど ゔぃー',null,'katamachi','順化','gourmet','その他',''),
('sd1150155','キュキュキュ','きゅきゅきゅ',null,'katamachi','順化','gourmet','その他',''),
('s331e2db6','キンヤ人情下町店','きんやにんじょうしたまちてん',null,'katamachi','順化','gourmet','その他',''),
('se2538d93','ゴードン','ごーどん',null,'katamachi','順化','gourmet','その他',''),
('s19a22213','サンクチュアリ','さんくちゅあり',null,'katamachi','順化','gourmet','その他',''),
('sa617f4a1','ジェイ‐グローブ(J-globe)','じぇい ぐろーぶ j globe',null,'katamachi','順化','gourmet','その他',''),
('sa0653b5f','ジェイ・グローブ','じぇい ぐろーぶ',null,'katamachi','順化','gourmet','その他',''),
('s048f70e3','スピークイージー','すぴーくいーじー',null,'katamachi','順化','gourmet','その他',''),
('s849179f9','スペイン酒場エル・スール','すぺいんさかばえる すーる',null,'katamachi','順化','gourmet','居酒屋',''),
('sa22c4fea','セナラ ジュテイ','せなら じゅてい',null,'katamachi','順化','gourmet','その他',''),
('s7046b5ce','セント・ジェームズ','せんと じぇーむず',null,'katamachi','順化','gourmet','その他',''),
('sd3549282','ゼット','ぜっと',null,'katamachi','順化','gourmet','その他',''),
('sc753a6df','ナイトイン季節風','ないといんきせつふう',null,'katamachi','順化','gourmet','その他',''),
('s18c1203f','ナフナフ','なふなふ',null,'katamachi','順化','gourmet','その他',''),
('s942993d8','ニュー淀','にゅーよど',null,'katamachi','順化','gourmet','その他',''),
('s73a7aa97','バッカス(BACCHUS)','ばっかす bacchus',null,'katamachi','順化','gourmet','その他',''),
('s529f286d','パインズ・バー','ぱいんず ばー',null,'katamachi','順化','night','バー',''),
('s537a8bd8','パラダイス','ぱらだいす',null,'katamachi','順化','gourmet','その他',''),
('s78ce1532','プラチナム(PLATINUM)','ぷらちなむ platinum',null,'katamachi','順化','gourmet','その他',''),
('sbc48c481','プロペラ','ぷろぺら',null,'katamachi','順化','gourmet','その他',''),
('s51a24057','ボギーズバー','ぼぎーずばー',null,'katamachi','順化','night','バー',''),
('s1cb86e25','マリブ(MALIBU)','まりぶ malibu',null,'katamachi','順化','gourmet','その他',''),
('sb838dce9','マルシェ','まるしぇ',null,'katamachi','順化','gourmet','その他',''),
('sa15735b1','ミムロ','みむろ',null,'katamachi','順化','gourmet','その他',''),
('s3d8d843f','メリージェーン','めりーじぇーん',null,'katamachi','順化','gourmet','その他',''),
('s7783a4ce','レオン','れおん',null,'katamachi','順化','gourmet','その他',''),
('s336d8d89','レディースマーケット','れでぃーすまーけっと',null,'katamachi','順化','gourmet','その他',''),
('s88f1a01b','ヴァンテレーヌ','ゔぁんてれーぬ',null,'katamachi','順化','gourmet','その他',''),
('saef08cb2','上野屋','うえのや',null,'katamachi','順化','gourmet','その他',''),
('see5ef528','亜米利館カツレツ店','ああめりかんかんかつれつてん',null,'katamachi','順化','gourmet','その他',''),
('s093086ca','凛','りん',null,'katamachi','順化','gourmet','その他',''),
('s5cea63aa','十六夜','いざよい',null,'katamachi','順化','gourmet','その他',''),
('sa56c9cfc','女子寮/福井店','じょしりょう ふくいてん',null,'katamachi','順化','gourmet','その他',''),
('s75f6146a','始皇帝','しこうてい',null,'katamachi','順化','gourmet','その他',''),
('s86a343d3','山根木','やまねき',null,'katamachi','順化','gourmet','その他',''),
('s1c0f2384','職人二人','しょくにんふたり',null,'katamachi','順化','gourmet','その他',''),
('sa118b8fa','花音','かのん',null,'katamachi','順化','gourmet','その他',''),
('s0918ef91','香華堂','こうげどう',null,'katamachi','順化','gourmet','その他',''),
('s3e2719c8','高島広幸','たかしまひろゆき',null,'katamachi','順化','gourmet','その他',''),
('s8c75506c','ルアンタイ','るあんたい',null,'katamachi','順化','gourmet','アジア・各国料理',''),
('s60b5526c','宗家','そうけ',null,'katamachi','順化','gourmet','アジア・各国料理',''),
('s3ae3fb1c','白頭山','しろがしらやま',null,'katamachi','順化','gourmet','アジア・各国料理',''),
('s359b50a6','豚屋','ぶたや',null,'katamachi','順化','gourmet','アジア・各国料理',''),
('sea1c91f9','韓国食堂mukuge','かんこくしょくどうmukuge',null,'katamachi','順化','gourmet','アジア・各国料理',''),
('s2da5446a','なかだ','なかだ',null,'katamachi','順化','gourmet','イタリアン・フレンチ',''),
('s2a539d8e','26ice','26ice',null,'katamachi','順化','gourmet','カフェ・スイーツ','26ice.fukui'),
('sf0cd82ef','ミルヒビカフェ','みるひびかふぇ',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('sb037cd70','YUKI LEIN','yuki lein',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('s45b60eaa','アスワン','あすわん',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('se3ea25db','ウィーン','うぃーん',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('saeef5c36','カフェ 点','かふぇ てん',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('s773dd354','コーヒーハウスコナン','こーひーはうすこなん',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('sb41499ea','パリス','ぱりす',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('s067aec81','千恵','ちえ',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('s83175030','喫茶 カファ・ブンナ','きっさ かふぁ ぶんな',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('sd65b6156','巴奈麻','ともえなま',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('s2554e909','珈琲所','こーひーところ',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('s8909b195','道安','どうあん',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('sb354a49f','カフェ アンパサンド','かふぇ あんぱさんど',null,'katamachi','順化','gourmet','カフェ・スイーツ','ampersand_tommy'),
('sd4136377','パティスリー オリヴィエール','ぱてぃすりー おりゔぃえーる',null,'katamachi','順化','gourmet','カフェ・スイーツ','oliviere_'),
('s621d80d0','喫茶 SEVEN’s(セブンズ)','きっさ seven s せぶんず',null,'katamachi','順化','gourmet','カフェ・スイーツ','sevens359'),
('s5c45398c','カラオケ ビッグエコー 片町店','からおけ びっぐえこー かたまちてん',null,'katamachi','順化','gourmet','その他',''),
('s7349674b','おはぎや 小林','おはぎや こばやし',null,'katamachi','順化','gourmet','カフェ・スイーツ','ohagiyakoba'),
('scf6e4f22','ティラミス専門店 トラットリア トマト','てぃらみすせんもんてん とらっとりあ とまと',null,'katamachi','順化','gourmet','イタリアン・フレンチ','trattoria.tomato'),
('sf6e52055','soba 月山','soba がっさん',null,'katamachi','順化','gourmet','そば・うどん','sobagezan'),
('sd178765f','つるきそば 佐佳枝支店','つるきそば さかえしてん',null,'katamachi','順化','gourmet','そば・うどん',''),
('sf213de58','手打ひと筋 さのや','てうちひとすじ さのや',null,'katamachi','順化','gourmet','そば・うどん',''),
('s1bb93f7c','越前蕎麦dining 櫻庭(さくらば)','えちぜんそばdining さくらば さくらば',null,'katamachi','順化','gourmet','そば・うどん','echizensoba.dining_sakuraba'),
('s95a2236e','天籠(てんかご)','てんかご てんかご',null,'katamachi','順化','gourmet','そば・うどん','tenkago.myo'),
('s3d5f6c4e','Mooma(モーマ)','mooma もーま',null,'katamachi','順化','gourmet','そば・うどん','mooma5745'),
('s839626e6','こんなパスタが食べたくて','こんなぱすたがたべたくて',null,'katamachi','順化','gourmet','イタリアン・フレンチ','konpasu_291'),
('s46f9af51','夕炊屋 fudo(ゆうげや ふど)','ゆうすいや fudo ゆうげや ふど',null,'katamachi','順化','gourmet','イタリアン・フレンチ','10nin10color'),
('sb77fbccd','GYOZA kitchen 信正(しんせい)','gyoza kitchen のぶまさ しんせい',null,'katamachi','順化','gourmet','ラーメン',''),
('s1133ed50','炭火焼き 赤身・じびえ・ほるもん どがいし','すみびやき あかみ じびえ ほるもん どがいし',null,'katamachi','順化','gourmet','洋食','dogaisi_291'),
('sb1e3455d','おばんざい家 たかはし','おばんざいいえ たかはし',null,'katamachi','順化','gourmet','洋食','obannzai.takahashi'),
('s4a5a5bd6','かき乃木','かきのぎ',null,'katamachi','順化','gourmet','洋食','kakinoki_fukui'),
('s1c2c0c33','陶酔 灯り','とうすい あかり',null,'katamachi','順化','gourmet','洋食','tousui_akari'),
('s3e300401','めしや しの﨑','めしや しのしの',null,'katamachi','順化','gourmet','居酒屋','meshiya.shinozaki'),
('s153fe11b','料理屋 みや﨑','りょうりや みやみや',null,'katamachi','順化','gourmet','居酒屋',''),
('sfd765333','歳時鹿火(さいじろくか)','さいじかび さいじろくか',null,'katamachi','順化','gourmet','洋食','saiji_rokuka_official'),
('s498b4096','四季ごはん おやびんHOUSE','しきごはん おやびんhouse',null,'katamachi','順化','gourmet','居酒屋',''),
('s3d95a6ec','晩酌 ちろり','ばんしゃく ちろり',null,'katamachi','順化','gourmet','居酒屋',''),
('sa4c1eaa7','酒彩 雁ぐらし(かりぐらし)','さけさい がんぐらし かりぐらし',null,'katamachi','順化','gourmet','居酒屋','karigurasi.fukui'),
('sa9bfddef','鉄板焼肉酒場 まねき屋','てっぱんやきにくさかば まねきや',null,'katamachi','順化','gourmet','焼肉・肉料理','manekiya320'),
('sf098584a','鶏料理居酒屋 トリノトリコ','にわとりりょうりいざかや とりのとりこ',null,'katamachi','順化','gourmet','居酒屋','tori_no_torico_fukui'),
('s578a39f9','GYUGYU焼肉 七福(しちふく)','gyugyuやきにく しちふく しちふく',null,'katamachi','順化','gourmet','焼肉・肉料理','yakiniku_shichifuku'),
('s510f1923','OHAKO','ohako',null,'katamachi','順化','gourmet','焼肉・肉料理','ohako_fukui'),
('s73376292','あぶり牧場 あん','あぶりぼくじょう あん',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('sdfb60a18','ジンギスカン鮮(せん)','じんぎすかんせん せん',null,'katamachi','順化','gourmet','焼肉・肉料理','sen_hituji0411'),
('sf45ad5e8','和田○商店','わだ しょうてん',null,'katamachi','順化','gourmet','焼肉・肉料理','akamiwadamaru'),
('s6cdaa3b7','焼き肉家 山本','やきにくいえ やまもと',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('scc8615a6','焼肉 うしのね','やきにく うしのね',null,'katamachi','順化','gourmet','焼肉・肉料理','yakiniku__usinone'),
('s8a365757','牛匠・人時(ぎゅうしょう・ひととき)','うしたくみ にんとき ぎゅうしょう ひととき',null,'katamachi','順化','gourmet','焼肉・肉料理','gyuushou.hitotoki'),
('sc1b4dfb9','Yellow(イエロー)','yellow いえろー',null,'katamachi','順化','gourmet','焼肉・肉料理','yellow_spice_labo'),
('sa9f5da48','遊留里楽酒場 みとん(ゆるりらさかば みとん)','ゆうるりたのさかば みとん ゆるりらさかば みとん',null,'katamachi','順化','gourmet','焼鳥・串','miton0521'),
('s6b32962a','暖らん酒場 八や(はちや)','だんらんさかば はちや はちや',null,'katamachi','順化','gourmet','居酒屋','hachiya.fukui'),
('sd99cb14d','華汀園','はなみぎわその',null,'katamachi','順化','gourmet','中華',''),
('se8ff9864','いちろくらーめん 片町本通り店','いちろくらーめん かたまちほんどおりてん',null,'katamachi','順化','gourmet','ラーメン','ichiroku_ramen'),
('sed22126a','がんこ2代目ラーメン','がんこ2だいめらーめん',null,'katamachi','順化','gourmet','ラーメン',''),
('s1b9f88a4','上海亭','しゃんはいてい',null,'katamachi','順化','gourmet','ラーメン',''),
('sc5f60290','多弐家','たにいえ',null,'katamachi','順化','gourmet','ラーメン',''),
('s7ae7c6d4','拉麺家 とんとん','らーめんいえ とんとん',null,'katamachi','順化','gourmet','ラーメン',''),
('sc3eb5591','長宝亭','ちょうたからてい',null,'katamachi','順化','gourmet','ラーメン',''),
('sb1f352b6','きのこしゃぶしゃぶ料理 栄福祥','きのこしゃぶしゃぶりょうり えいふくしょう',null,'katamachi','順化','gourmet','中華',''),
('sc97f1ff9','ギョウザ・ラーメン 彩菜','ぎょうざ らーめん あやな',null,'katamachi','順化','gourmet','ラーメン',''),
('s185970a0','中国本場料理 福井源','ちゅうごくほんばりょうり ふくいげん',null,'katamachi','順化','gourmet','中華',''),
('s3cc39b54','タコスのある人生 La Vida Tacos','たこすのあるじんせい la vida tacos',null,'katamachi','順化','gourmet','アジア・各国料理','la_vida_tacos'),
('s7dfb67d8','五味五色 じゅじゅむむ','ごみごしき じゅじゅむむ',null,'katamachi','順化','gourmet','アジア・各国料理',''),
('sa4e65b58','地中海バル OTTO','ちちゅうかいばる otto',null,'katamachi','順化','gourmet','居酒屋',''),
('s9a4c9676','韓国料理 ペゴパ','かんこくりょうり ぺごぱ',null,'katamachi','順化','gourmet','アジア・各国料理','pegopa1115'),
('se272263a','韓国風鉄板焼・鍋工房 鉄鍋屋','かんこくかぜてっぱんやき なべこうぼう てつなべや',null,'katamachi','順化','gourmet','アジア・各国料理','tetunabeya'),
('s15dd4dc1','にく家 うましか','にくいえ うましか',null,'katamachi','順化','gourmet','焼肉・肉料理','nikuya.umashika'),
('s1afd7ae6','炭火焼肉 春来','すみびやきにく はるらい',null,'katamachi','順化','gourmet','焼肉・肉料理','cut_haluku'),
('sa7747358','焼き肉 豊 -YUTAKA-','やきにく ゆたか yutaka',null,'katamachi','順化','gourmet','焼肉・肉料理','yakinikuyutaka5296'),
('sc037c175','焼肉 うし牛','やきにく うしうし',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('sab38c052','焼肉かわだ','やきにくかわだ',null,'katamachi','順化','gourmet','焼肉・肉料理','yakiniku_kawada'),
('s9e7b72ab','福昌園','ふくしょうその',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('sd6aef52a','若狭牛と個室焼肉 和田○商店','わかさうしとこしつやきにく わだ しょうてん',null,'katamachi','順化','gourmet','焼肉・肉料理','wadamaru_shouten'),
('saad46e0a','あげます','あげます',null,'katamachi','順化','gourmet','和食',''),
('sae2000ca','あらかわ','あらかわ',null,'katamachi','順化','gourmet','和食',''),
('s48972b45','いっすんぼうし','いっすんぼうし',null,'katamachi','順化','gourmet','和食',''),
('s8dc35a91','おきな','おきな',null,'katamachi','順化','gourmet','和食',''),
('saeacb1d2','お柳','おやなぎ',null,'katamachi','順化','gourmet','和食',''),
('s66fca2f8','かっちゃん','かっちゃん',null,'katamachi','順化','gourmet','和食',''),
('s554ec16c','じん','じん',null,'katamachi','順化','gourmet','和食',''),
('saa7a0452','すし善','すしぜん',null,'katamachi','順化','gourmet','寿司・海鮮',''),
('s456938cd','だるま鮨','だるますし',null,'katamachi','順化','gourmet','寿司・海鮮',''),
('s5eff3ef1','ちか','ちか',null,'katamachi','順化','gourmet','和食',''),
('s669c8e05','でん助','でんじょ',null,'katamachi','順化','gourmet','和食',''),
('s75e833a5','ときわ','ときわ',null,'katamachi','順化','gourmet','和食',''),
('s0f000893','とり新','とりしん',null,'katamachi','順化','gourmet','和食',''),
('sc17c8de0','みよしの','みよしの',null,'katamachi','順化','gourmet','和食',''),
('sf2d60390','やました','やました',null,'katamachi','順化','gourmet','和食',''),
('s2b34ab87','ゆずりは','ゆずりは',null,'katamachi','順化','gourmet','和食',''),
('sd54c2e62','佳納','かのう',null,'katamachi','順化','gourmet','和食',''),
('sb1475d1a','初味寿司呉服町店','はつあじすしごふくちょうてん',null,'katamachi','順化','gourmet','寿司・海鮮',''),
('s68b63729','吉田寿司本店','よしだすしほんてん',null,'katamachi','順化','gourmet','寿司・海鮮',''),
('sd83b39aa','味とまごころ 八勢','あじとまごころ はちせい',null,'katamachi','順化','gourmet','和食',''),
('s0509d1dd','咲咲','さきさき',null,'katamachi','順化','gourmet','和食',''),
('s3d24ec22','咲良・味工房','さくら あじこうぼう',null,'katamachi','順化','gourmet','和食',''),
('sf168fd4c','大仏そば','だいぶつそば',null,'katamachi','順化','gourmet','そば・うどん',''),
('s8a743fa5','大番','おおばん',null,'katamachi','順化','gourmet','和食',''),
('sbde5e1bd','大西','おおにし',null,'katamachi','順化','gourmet','和食',''),
('s431e6f4f','寿し保','すしほ',null,'katamachi','順化','gourmet','和食',''),
('scabe4132','寿ゞ屋','ひさしゞや',null,'katamachi','順化','gourmet','和食',''),
('s17d70843','寿司道楽','すしどうらく',null,'katamachi','順化','gourmet','寿司・海鮮',''),
('s24f4e4d6','文ちん','ぶんちん',null,'katamachi','順化','gourmet','和食',''),
('sb8320adf','文室','ふんや',null,'katamachi','順化','gourmet','和食',''),
('saae6d4a1','桜寿し本店','さくらすしほんてん',null,'katamachi','順化','gourmet','和食',''),
('sa73bcf7b','楽','らく',null,'katamachi','順化','gourmet','和食',''),
('sd62d598c','波の華','なみのはな',null,'katamachi','順化','gourmet','和食',''),
('sd27993d8','焼鳥大将片町店','やきとりたいしょうかたまちてん',null,'katamachi','順化','gourmet','焼鳥・串',''),
('s776b5062','田畑清正','たはたきよまさ',null,'katamachi','順化','gourmet','和食',''),
('s4ff26fa9','番晩亭','ばんばんてい',null,'katamachi','順化','gourmet','和食',''),
('sacfc6c86','磯季節料理店','いそきせつりょうりてん',null,'katamachi','順化','gourmet','和食',''),
('s9b859a1a','粂ちゃん','くめちゃん',null,'katamachi','順化','gourmet','和食',''),
('s3ab92ad1','紫川','むらさきがわ',null,'katamachi','順化','gourmet','和食',''),
('sd10debe6','細庵','さいあん',null,'katamachi','順化','gourmet','和食',''),
('sf2924ed3','茶がま','ちゃがま',null,'katamachi','順化','gourmet','和食',''),
('s36895a99','茶太片町分店','ちゃふとかたまちわかてん',null,'katamachi','順化','gourmet','和食',''),
('s0160358d','葉月','はづき',null,'katamachi','順化','gourmet','和食',''),
('s7b889572','金龍','きんりゅう',null,'katamachi','順化','gourmet','和食',''),
('s76f1c89a','釜めし 煮込うどん 王将','かまめし にこみうどん おうしょう',null,'katamachi','順化','gourmet','そば・うどん',''),
('se0f1621a','そば重','そばじゅう',null,'katamachi','順化','gourmet','そば・うどん',''),
('sa7e97ff0','ポポー軒','ぽぽーけん',null,'katamachi','順化','gourmet','そば・うどん',''),
('s8a5e585e','佐佳枝亭','さかえてい',null,'katamachi','順化','gourmet','そば・うどん',''),
('s7069add9','越前そば 片桐','えちぜんそば かたぎり',null,'katamachi','順化','gourmet','そば・うどん',''),
('s786a51b5','お好み焼き 富士美','おこのみやき ふじみ',null,'katamachi','順化','gourmet','和食',''),
('sbe378692','くくる','くくる',null,'katamachi','順化','gourmet','和食',''),
('sdb3613c2','とんかつ割烹 一えい','とんかつかっぽう いちえい',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('sbbbe1e11','とんかつ割烹 谷口や','とんかつかっぽう たにぐちや',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('sd1a4261a','ヨーロッパ軒総本店','よーろっぱけんそうほんてん',null,'katamachi','順化','gourmet','焼肉・肉料理','yoroppakensouhonten'),
('s891aae82','しゃぶ玄','しゃぶげん',null,'katamachi','順化','gourmet','和食',''),
('s8f165711','TSUGI(ツギ)','tsugi つぎ',null,'katamachi','順化','gourmet','和食','tsugi_19h'),
('s217fefa2','ご馳走 純','ごちそう じゅん',null,'katamachi','順化','gourmet','和食','gochisou_jun'),
('sb3c17def','はちまん','はちまん',null,'katamachi','順化','gourmet','和食','hach.imann'),
('s70a7f9ac','まちの都 machi no miyaco','まちのみやこ machi no miyaco',null,'katamachi','順化','gourmet','和食','machino_miyaco'),
('s71d8b75b','割烹 木屋町 Kiyamachi','かっぽう きやまち kiyamachi',null,'katamachi','順化','gourmet','和食',''),
('s2c63e16c','創作小鉢 あけると','そうさくこばち あけると',null,'katamachi','順化','gourmet','和食','_akeruto'),
('sda2640e6','味処 源太','あじどころ げんた',null,'katamachi','順化','gourmet','和食','genta_0924'),
('se7bea929','和食ダイニング 柳月亭','わしょくだいにんぐ やなぎがつてい',null,'katamachi','順化','gourmet','和食','ryugetsutei'),
('se4d8d95e','和食処 山海','わしょくどころ さんかい',null,'katamachi','順化','gourmet','和食',''),
('sceb510ce','御料理 味真乃','おりょうり あじまことの',null,'katamachi','順化','gourmet','和食',''),
('sdd37cf56','旬彩家 樹','じゅんさいいえ き',null,'katamachi','順化','gourmet','和食',''),
('s7852adf3','鮮','せん',null,'katamachi','順化','gourmet','和食','sen_hituji0411'),
('s2f101f89','天ぷら 天春','てんぷら てんはる',null,'katamachi','順化','gourmet','和食',''),
('s868ded4e','天菊','てんぎく',null,'katamachi','順化','gourmet','和食',''),
('s5621c2d4','魚菜園','ぎょさいその',null,'katamachi','順化','gourmet','寿司・海鮮',''),
('s9831a6a8','すし吉正','すしよしまさ',null,'katamachi','順化','gourmet','寿司・海鮮','sushi_yoshimasa'),
('s1a3398e9','寿し吉田','すしよしだ',null,'katamachi','順化','gourmet','寿司・海鮮','sushi_yoshida'),
('sde6ccd42','寿司・割烹・ふぐ料理 鮨長','すし かっぽう ふぐりょうり すしちょう',null,'katamachi','順化','gourmet','寿司・海鮮','sushicho2018'),
('sb9193d58','鮨 凌','すし りょう',null,'katamachi','順化','gourmet','寿司・海鮮','sushi__ryo'),
('sa95302ef','鮨 吉幸','すし よしゆき',null,'katamachi','順化','gourmet','寿司・海鮮','sushi_kiccou'),
('s786ae940','鮨光','すしひかり',null,'katamachi','順化','gourmet','寿司・海鮮','sushimitsu_fukui'),
('sff834a3d','鮨処 海月','すしどころ くらげ',null,'katamachi','順化','gourmet','寿司・海鮮','kurage.666'),
('saac1d3c0','お料理 いわし屋','おりょうり いわしや',null,'katamachi','順化','gourmet','和食','iwashiya_'),
('s9c10f23f','のちのち','のちのち',null,'katamachi','順化','gourmet','和食',''),
('s1a97bd84','日本料理 やなぎ町','にっぽんりょうり やなぎまち',null,'katamachi','順化','gourmet','和食','yanagimachi_honten'),
('sb7abccd5','燻鮎 KUNTEN','くんあゆ kunten',null,'katamachi','順化','gourmet','和食',''),
('s4fe7e7c6','田中マネの食堂','たなかまねのしょくどう',null,'katamachi','順化','gourmet','和食',''),
('se5018641','CREPE BON','crepe bon',null,'katamachi','順化','gourmet','カフェ・スイーツ','crepe.bon'),
('se5af507c','Spice Bar QUILT HOUSE(キルトハウス)','spice bar quilt house きるとはうす',null,'katamachi','順化','night','バー','spicebarquilthouse'),
('s3f80db21','THREE TIMES COFFEE','three times coffee',null,'katamachi','順化','gourmet','カフェ・スイーツ','threetimescoffee_fukui'),
('s6da86f0c','flat kitchen','flat kitchen',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('s55741195','カフェと雑貨 古民家35','かふぇとざっか こみんか35',null,'katamachi','順化','gourmet','カフェ・スイーツ','kominka35'),
('s8e705810','京町Y・Yカフェ','きょうまちy yかふぇ',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('s3c4c6f9b','CIGAR&CAFE 臼井煙草倶楽部','cigar cafe うすいたばこくらぶ',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('sd90895ec','異邦人倶楽部','いほうじんくらぶ',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('sbe6b898a','yokoyama別亭','yokoyamaわかてい',null,'katamachi','順化','gourmet','居酒屋',''),
('s307bfba9','炭火串焼千串屋','すみびくしやきせんくしや','2026-09-25'::date,'katamachi','順化','gourmet','焼鳥・串',''),
('s367eb072','あげはら','あげはら',null,'katamachi','順化','gourmet','居酒屋',''),
('s9663f919','あんぶん春','あんぶんはる',null,'katamachi','順化','gourmet','居酒屋',''),
('s069fd0ed','うまいもの屋敷 忍者','うまいものやしき にんじゃ',null,'katamachi','順化','gourmet','居酒屋',''),
('sead7d63c','かっぱ','かっぱ',null,'katamachi','順化','gourmet','居酒屋',''),
('s3a654b14','かんちゃん','かんちゃん',null,'katamachi','順化','gourmet','居酒屋',''),
('s639da5a4','ききょう','ききょう',null,'katamachi','順化','gourmet','居酒屋',''),
('scff2bc52','しまだ','しまだ',null,'katamachi','順化','gourmet','居酒屋',''),
('s7f29a26a','てらや','てらや',null,'katamachi','順化','gourmet','居酒屋',''),
('s73927a00','とも貴','ともたかし',null,'katamachi','順化','gourmet','居酒屋',''),
('s4d5c82b7','のむ喜','のむき',null,'katamachi','順化','gourmet','居酒屋',''),
('s2e041204','はせじ','はせじ',null,'katamachi','順化','gourmet','居酒屋',''),
('s0880190e','ひいきや','ひいきや',null,'katamachi','順化','gourmet','居酒屋',''),
('s551ea6ef','ひろちゃん','ひろちゃん',null,'katamachi','順化','gourmet','居酒屋',''),
('se937e33f','まき','まき',null,'katamachi','順化','gourmet','居酒屋',''),
('s5ba59f5d','まんぼう','まんぼう',null,'katamachi','順化','gourmet','居酒屋',''),
('s67514f4c','やきとり 八や','やきとり はちや',null,'katamachi','順化','gourmet','焼鳥・串',''),
('s13adad43','やき屋','やきや',null,'katamachi','順化','gourmet','居酒屋',''),
('s6b9c1233','よしむら 割烹 鍋物','よしむら かっぽう なべもの',null,'katamachi','順化','gourmet','居酒屋',''),
('s0862e47a','ろばた焼 弥吉 片町店','ろばたやき やきち かたまちてん',null,'katamachi','順化','gourmet','居酒屋',''),
('s74ee4314','シェ・シーマ(CHEZCIMA)','しぇ しーま chezcima',null,'katamachi','順化','gourmet','居酒屋',''),
('s6a580b5b','ソウル','そうる',null,'katamachi','順化','gourmet','居酒屋',''),
('scc2be637','プーケット','ぷーけっと',null,'katamachi','順化','gourmet','居酒屋',''),
('s5d767b0d','ムッ酒','むっさけ',null,'katamachi','順化','gourmet','居酒屋',''),
('sfde442cb','丸駒','まるこま',null,'katamachi','順化','gourmet','居酒屋',''),
('sf41e4a08','八州屋','はっしゅうや',null,'katamachi','順化','gourmet','居酒屋',''),
('s748ae3f8','友膳','ともぜん',null,'katamachi','順化','gourmet','居酒屋',''),
('s39d888e4','吟遊','ぎんゆう',null,'katamachi','順化','gourmet','居酒屋',''),
('s2cb6061a','呑むきんちゃん','のむきんちゃん',null,'katamachi','順化','gourmet','居酒屋',''),
('sc9ebaa56','和ぼうず','わぼうず',null,'katamachi','順化','gourmet','居酒屋',''),
('s0fe72c15','寿し割烹 八重','すしかっぽう やえ',null,'katamachi','順化','gourmet','居酒屋',''),
('sb18e43e4','居酒屋いちべえ','いざかやいちべえ',null,'katamachi','順化','gourmet','居酒屋',''),
('s74e6c803','居酒屋とっさん','いざかやとっさん',null,'katamachi','順化','gourmet','居酒屋',''),
('s2dc17270','居酒屋花や','いざかやはなや',null,'katamachi','順化','gourmet','居酒屋',''),
('sb0239e11','市','し',null,'katamachi','順化','gourmet','居酒屋',''),
('sd0bcb41c','平八','へいはち',null,'katamachi','順化','gourmet','居酒屋',''),
('sfed117ef','春月','しゅんげつ',null,'katamachi','順化','gourmet','居酒屋',''),
('s689532b4','来神','らいかみ',null,'katamachi','順化','gourmet','居酒屋',''),
('s940f2085','武','たけし',null,'katamachi','順化','gourmet','居酒屋',''),
('s93d5500a','民俗村','みんぞくむら',null,'katamachi','順化','gourmet','居酒屋',''),
('s1cb2f135','汐彩','しおさい',null,'katamachi','順化','gourmet','居酒屋',''),
('s33a2d7c3','洋食居酒屋クオーレ','ようしょくいざかやくおーれ',null,'katamachi','順化','gourmet','居酒屋',''),
('s96659a24','直','ちょく',null,'katamachi','順化','gourmet','居酒屋',''),
('sf451c6fc','福義','ふくよし',null,'katamachi','順化','gourmet','居酒屋',''),
('s30aec0c7','福菜福酒 師門','ふくなふくさけ しもん',null,'katamachi','順化','gourmet','居酒屋',''),
('sd6b4db8b','竹生','たけお',null,'katamachi','順化','gourmet','居酒屋',''),
('sac848a19','美ちゃん','びちゃん',null,'katamachi','順化','gourmet','居酒屋',''),
('s4f6e9220','翠翔 片町店','すいしょう かたまちてん',null,'katamachi','順化','gourmet','居酒屋',''),
('scbb2582c','花や片町店','はなやかたまちてん',null,'katamachi','順化','gourmet','居酒屋',''),
('se8215640','菜彩亭','なさいてい',null,'katamachi','順化','gourmet','居酒屋',''),
('s3295a40a','菜遊季','なゆうき',null,'katamachi','順化','gourmet','居酒屋',''),
('s34a51090','越の国つた屋','えつのくにつたや',null,'katamachi','順化','gourmet','居酒屋',''),
('sed552032','遊月家','ゆうがついえ',null,'katamachi','順化','gourmet','居酒屋',''),
('s11b4c972','遊月家参百圓食堂','ゆうがついえさんひゃくえんしょくどう',null,'katamachi','順化','gourmet','居酒屋',''),
('s0cead092','錦','にしき',null,'katamachi','順化','gourmet','居酒屋',''),
('s0c35cc80','食・酒野尻','しょく さけのじり',null,'katamachi','順化','gourmet','居酒屋',''),
('s600531b2','魚義','さかなぎ',null,'katamachi','順化','gourmet','寿司・海鮮',''),
('s74326fb5','ペントラ・ベーネ(Pentola・Bene)','ぺんとら べーね pentola bene',null,'katamachi','順化','gourmet','洋食',''),
('s10ab3b3c','レストランル・ラパン','れすとらんる らぱん',null,'katamachi','順化','gourmet','カフェ・スイーツ',''),
('s41a13a27','和洋創菜 豆や','わようそうさい まめや',null,'katamachi','順化','gourmet','洋食',''),
('s3c52bf29','Spuntino (スプンティーノ)','spuntino すぷんてぃーの',null,'katamachi','順化','gourmet','イタリアン・フレンチ','spuntino_italiano'),
('s048a4b39','伊食堂 Arancia','いしょくどう arancia',null,'katamachi','順化','gourmet','イタリアン・フレンチ','arancia_2008'),
('s411e7792','オニク☆パラダイス','おにく ぱらだいす',null,'katamachi','順化','gourmet','焼肉・肉料理','nikupara29'),
('scd7e2e2c','ステーキ 鐵船','すてーき てっせん',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('s2000f203','ステーキハウス アオヤマ','すてーきはうす あおやま',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('sc3b983cf','ステーキハウス キタジマ','すてーきはうす きたじま',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('s0e593b77','レストラン バンボッシュ・ド・ヤマ','れすとらん ばんぼっしゅ ど やま',null,'katamachi','順化','gourmet','イタリアン・フレンチ',''),
('s07d1f1b5','ワインと旬の料理の店 ミスター・デ・ヴ','わいんとじゅんのりょうりのてん みすたー で ゔ',null,'katamachi','順化','gourmet','イタリアン・フレンチ',''),
('s19cddc39','欧風割烹 北欧','おうふうかっぽう ほくおう',null,'katamachi','順化','gourmet','イタリアン・フレンチ',''),
('s4bb210af','洋食堂 yousyokudou','ひろししょくどう yousyokudou',null,'katamachi','順化','gourmet','イタリアン・フレンチ','yoshoku_do114'),
('s1ab1d3c7','VIP Amon','vip amon',null,'katamachi','順化','gourmet','洋食',''),
('s43f04cd5','レストラン クレドール','れすとらん くれどーる',null,'katamachi','順化','gourmet','洋食',''),
('se336a944','寿司政','すしまつりごと',null,'katamachi','順化','gourmet','寿司・海鮮','sushimasa_fukui'),
('s19b5bd45','しらさきホルモン','しらさきほるもん',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('s3b892d5d','ひばち','ひばち',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('sc0f46936','イガネ','いがね',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('sd1e97e3c','焼肉星香園','やきにくほしかおりその',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('s3112b1c6','牛牛','うしうし',null,'katamachi','順化','gourmet','焼肉・肉料理',''),
('s9d3e8d07','てがるそば','てがるそば',null,'katamachi','順化','gourmet','そば・うどん',''),
('s3ad2c6e9','越前そば 見吉屋','えちぜんそば けんよしや',null,'katamachi','順化','gourmet','そば・うどん',''),
('s6b5dd69d','割烹間海','かっぽうかんうみ',null,'katamachi','順化','gourmet','寿司・海鮮',''),
('s803c1518','親玉菓舗の碌寶焼','おやだまかほのろくたからやき',null,'katamachi','順化','gourmet','その他','oyadama32028'),
('s6aaab873','錦梅堂','きんばいどう',null,'katamachi','順化','gourmet','その他',''),
('s6af60179','のんちゃん','のんちゃん',null,'katamachi','順化','gourmet','居酒屋',''),
('s4eda15bf','和食と地酒 本伊勢','わしょくとじざけ ほんいせ',null,'katamachi','順化','gourmet','居酒屋',''),
('s2c32a5fc','居酒屋 えんの樹','いざかや えんのき',null,'katamachi','順化','gourmet','居酒屋',''),
('s19cda020','居酒屋 ひっぱり凧','いざかや ひっぱりたこ',null,'katamachi','順化','gourmet','居酒屋',''),
('s9b01884b','想作居酒屋 一ふじ','そうさくいざかや いちふじ',null,'katamachi','順化','gourmet','居酒屋',''),
('s072e3506','越前の幸と喜びの酒 前田屋いちりん','えちぜんのさちとよろこびのさけ まえだやいちりん',null,'katamachi','順化','gourmet','居酒屋',''),
('sa72bd449','越前中華 花ひなたに咲く','えちぜんちゅうか はなひなたにさく',null,'katamachi','順化','gourmet','居酒屋','hanahinatanisaku'),
('s5e600582','酒肴 コブ','しゅこう こぶ',null,'katamachi','順化','gourmet','居酒屋',''),
('sab1e5a39','食彩DINING 神無月 想い出','しょくさいdining かんなづき おもいで',null,'katamachi','順化','gourmet','居酒屋',''),
('sedc2651c','食彩酒楽 いち陽','しょくさいさかほがい いちよう',null,'katamachi','順化','gourmet','居酒屋',''),
('sdf3329c1','やきとり ごとう','やきとり ごとう',null,'katamachi','順化','gourmet','焼鳥・串',''),
('s6d6116f8','串揚げ処 㐂寿','くしあげどころ きじゅ',null,'katamachi','順化','gourmet','焼鳥・串',''),
('s0d8defce','鳥匠 あさぎり','とりたくみ あさぎり',null,'katamachi','順化','gourmet','焼鳥・串','asagirifukui'),
('sd4174d96','CLUB Risel','club risel',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s47fedf50','EAST','east',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sa1f6802f','Rui','rui',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s45a75088','club cherir','club cherir',null,'katamachi','順化','night','スナック・ラウンジ',''),
('se06c2d52','club 蓮','club はす',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s446a7e60','ひな乃','ひなの',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sf8bc563c','スナックJm','すなっくjm',null,'katamachi','順化','night','スナック・ラウンジ','snack_jm_1124_'),
('sfb9bf709','スナックKARA','すなっくkara',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sf560f241','スナックあれから','すなっくあれから',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s558ff87c','スナック・ロシア','すなっく ろしあ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sbd388289','ナイトラウンジ恋華片町','ないとらうんじこいはなかたまち',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s323a99e4','ラウンジステラ','らうんじすてら',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sb255c48c','リッカー(Riccar)','りっかー riccar',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s8e8bde68','Anri','anri',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s90e9520e','Belle vie~ベルヴィー~','belle vie べるゔぃー',null,'katamachi','順化','night','スナック・ラウンジ','bellevie62288'),
('sf7255b5d','FRIEND BAR CURIOUS','friend bar curious',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sb100728b','I♡DABAO','i dabao',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s97591a2d','JIGURO','jiguro',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s8360d520','KARAOKE BAR NOAH','karaoke bar noah',null,'katamachi','順化','night','スナック・ラウンジ','noah_keirin'),
('s0f2c64c6','KOBAR','kobar',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s6f213bdc','LesoUrIre','lesourire',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sfff10c76','Lounge Connection','lounge connection',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s10174fda','Luxe','luxe',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s44f5407f','More~モア~','more もあ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sbe58fd4d','NEGUS.','negus',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s50cf4f21','OG-ChinaTown','og chinatown',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s74c77dce','SMILeeeS~スマイリーズ~','smileees すまいりーず',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s517a1da8','cafe&bar NABO','cafe bar nabo',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sb85bc640','momo','momo',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s3223ff06','musa','musa',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s28f504d9','mystere','mystere',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s03ef00a4','vivian. (ビビアンドット)','vivian びびあんどっと',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sb31dd628','はてな','はてな',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sf9344bdf','やすらぎ','やすらぎ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sbfb74d02','アプリコット','あぷりこっと',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s2cc7c925','カラオケスナック あざみ','からおけすなっく あざみ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s237f50b1','カラオケバー LP','からおけばー lp',null,'katamachi','順化','night','スナック・ラウンジ','karaoke_bar_lp'),
('sb7a58119','スナック さくら','すなっく さくら',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s23a91273','スナック せせらぎ','すなっく せせらぎ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s77c70ced','スナック なつこ','すなっく なつこ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('saa4af146','スナック ぴーち','すなっく ぴーち',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sf5fcc1f6','スナック みやま','すなっく みやま',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sc491f560','スナック アーバン','すなっく あーばん',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s95a14250','スナック ニューりんご','すなっく にゅーりんご',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sc03920e5','スナック ラクシャリィ','すなっく らくしゃりぃ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sca529f69','スナック 五十八','すなっく いそや',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s3d6b9ac6','スナック 女帝','すなっく じょてい',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s0d4c2b03','スナック 真利倫','すなっく まさとしりん',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sdc8ff442','スナック 華','すなっく はな',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s5ac214f1','ナイトイン アップルハウス','ないといん あっぷるはうす',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sa0f6fc15','マリリン','まりりん',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s94c8b70c','ラウンジ たちばな','らうんじ たちばな',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s5f5f7aae','ラブ','らぶ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s13b3be9b','大連','だいれん',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s64ce2ef3','妖かし','ようかし',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s3aee8f03','燻(いぶし)','くん いぶし',null,'katamachi','順化','night','スナック・ラウンジ','eves.fukui'),
('sb89f1b9d','紗羅','さら',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s89f5ddc6','旬菜美酒 サスケ','じゅんなみさけ さすけ',null,'katamachi','順化','night','バー',''),
('s75b204ce','BAR 222','bar 222',null,'katamachi','順化','night','バー',''),
('s580b39a6','BAR GROWP.','bar growp',null,'katamachi','順化','night','バー',''),
('s3dcde339','BAR Rainbow st.','bar rainbow st',null,'katamachi','順化','night','バー',''),
('s7f821ec7','BAR Z','bar z',null,'katamachi','順化','night','バー',''),
('se6fde3e7','BAR primo','bar primo',null,'katamachi','順化','night','バー',''),
('se5d55e8b','BAR ぐーちょきぱー','bar ぐーちょきぱー',null,'katamachi','順化','night','バー',''),
('sa49785fb','BAR・SEA','bar sea',null,'katamachi','順化','night','バー',''),
('sa9990c09','Bar 018','bar 018',null,'katamachi','順化','night','バー',''),
('sd05db204','Bar STELA','bar stela',null,'katamachi','順化','night','バー',''),
('s45688cec','DON','don',null,'katamachi','順化','night','バー',''),
('s4d2b9604','EIGHT~Infinity Room~','eight infinity room',null,'katamachi','順化','night','バー',''),
('s09b193a2','Giorno','giorno',null,'katamachi','順化','night','バー',''),
('sf4df3742','LC','lc',null,'katamachi','順化','night','バー',''),
('s2116ea95','Lounge BIDEN','lounge biden',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s8368bd33','PAPILLON','papillon',null,'katamachi','順化','night','バー',''),
('s4e39d3e7','Party`s Bar BeReTTa','party s bar beretta',null,'katamachi','順化','night','バー',''),
('s2d4af826','dining cafe ヴィアーレ・ナフ','dining cafe ゔぃあーれ なふ',null,'katamachi','順化','night','バー',''),
('s53db608a','ゆる八','ゆるはち',null,'katamachi','順化','night','バー',''),
('sad7bee81','ホリチャン','ほりちゃん',null,'katamachi','順化','night','バー',''),
('s0f74b085','メリエンダ・バール DESPERADO','めりえんだ ばーる desperado',null,'katamachi','順化','night','バー',''),
('sdaebc4f2','suits AMUSEMENT BAR(スーツアミューズメントバー)福井店','suits amusement bar ふくいてん すーつあみゅーずめんとばー',null,'katamachi','順化','night','バー','suits__bar'),
('s4899be09','ARTIST BAR B(アーティストバービー)','artist bar b あーてぃすとばーびー',null,'katamachi','順化','night','バー','artist.bar.b'),
('s8eb58b22','BAR 7六歩(バー・ナナロクフ)','bar 7ろくほ ばー ななろくふ',null,'katamachi','順化','night','バー',''),
('s94c3c3ec','JAZZ BAR SHIRAI HOUSE(シライハウス)','jazz bar shirai house しらいはうす',null,'katamachi','順化','night','バー',''),
('scd7c8548','PICK UP BAR&CAFE (ピックアップバー&カフェ)','pick up bar cafe ぴっくあっぷばー かふぇ',null,'katamachi','順化','night','バー',''),
('s27530b44','SOMEN BAR白線屋','somen barはくせんや',null,'katamachi','順化','night','バー','hakusenya'),
('s19d452cc','十人十色koya','じゅうにんといろkoya',null,'katamachi','順化','night','バー','10nin10color_koya'),
('s8f270ba2','手品家 福井店','てじないえ ふくいてん',null,'katamachi','順化','night','バー','tejinaya.fukui'),
('s32a38885','Beer Stand Pivo(ビールスタンド ピヴォ)','beer stand pivo びーるすたんど ぴゔぉ',null,'katamachi','順化','night','バー','pivo_beerstand'),
('se20b01ba','Bar Someday','bar someday',null,'katamachi','順化','night','バー',''),
('s8c3cc9d1','Vestito Bar','vestito bar',null,'katamachi','順化','night','バー',''),
('saeb1e8e6','CLUB CHOCOLAT','club chocolat',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s479c1a94','CLUB Kai','club kai',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s16a3484e','CLUB NAGISA','club nagisa',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s79d60569','CLUB NAGISA','club nagisa',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sd0993f8d','CLUB ROCHER','club rocher',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s0d9ca646','CLUB Rapha','club rapha',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s1f968c13','Club ゆず','club ゆず',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sfcf7b292','KOMACHI','komachi',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s74523afd','L and Heart','l and heart',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sdf882d51','LA PAIX','la paix',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sb18877d9','LOUNGE 姫','lounge ひめ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sfc318514','LUMINE','lumine',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s62364e3d','Lounge Crystal','lounge crystal',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s25eafb21','Lounge K','lounge k',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s2b61279f','Lounge LA Coo','lounge la coo',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s50a7260e','Lounge ete','lounge ete',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s2f5ae9f8','Pretty May','pretty may',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s045b5231','RETENTIR','retentir',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s382df82a','Richebourg','richebourg',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s459aae16','SOHMA CLUB','sohma club',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s63514fd4','Shampoo','shampoo',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s367ecf02','club 奏鳴曲sonata','club そうめいきょくsonata',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s7c14a02c','lounge Salon','lounge salon',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sbeffbd40','おいない','おいない',null,'katamachi','順化','night','スナック・ラウンジ',''),
('saeea5f27','ラウンジ 晴','らうんじ せい',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s933eb384','京','きょう',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s3ca85da3','呼詩','こし',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sfb8404a0','小春日和','こはるびより',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s533e1c4f','小春日和','こはるびより',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sfc46a89d','彩 sayaka','さい sayaka',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s8e85acec','心','こころ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sbf085ba4','紗音','さおと',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s07f44bbf','藤','ふじ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sfcef8253','銀夏','ぎんなつ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sb3173cc7','離宮','りきゅう',null,'katamachi','順化','night','スナック・ラウンジ',''),
('se4c065aa','迦毘羅','かびら',null,'katamachi','順化','gourmet','アジア・各国料理',''),
('sa83be97a','まるさん屋 福井片町店','まるさんや ふくいかたまちてん',null,'katamachi','順化','gourmet','和食','marusanya_fukuikatamachi'),
('s75bc6b2f','KRAFT','kraft',null,'katamachi','順化','gourmet','居酒屋','kraft_fukui'),
('s8237af5d','Woody','woody',null,'katamachi','順化','gourmet','居酒屋',''),
('sd16a99f6','snow drop','snow drop',null,'katamachi','順化','gourmet','居酒屋','snow.drop.mama'),
('s2bbf9c2a','ケネディ・クラブ','けねでぃ くらぶ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s9d1d911a','パブ浪江','ぱぶなみえ',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s6a7f984b','猿の盃','さるのはい',null,'katamachi','順化','gourmet','居酒屋',''),
('s8641430b','HAMBURG STEAK 亜米利館','hamburg steak ああめりかんかん',null,'katamachi','順化','gourmet','焼肉・肉料理','hamburg_american'),
('sffc04f28','les quatre hommes','les quatre hommes',null,'katamachi','順化','gourmet','イタリアン・フレンチ','les.quatre.hommes'),
('s67e514d8','わらび 片町店','わらび かたまちてん',null,'katamachi','順化','gourmet','寿司・海鮮',''),
('s1effb8f7','やきとりの名門 秋吉 福井片町店','やきとりのめいもん あきよし ふくいかたまちてん',null,'katamachi','順化','gourmet','焼鳥・串',''),
('s20c94c25','やきとり治郎吉 片町店','やきとりじろうきち かたまちてん',null,'katamachi','順化','gourmet','焼鳥・串',''),
('sc9403682','㐂鶏屋(きどりや)','きにわとりや きどりや',null,'katamachi','順化','gourmet','焼鳥・串',''),
('s13659418','ACE.ATRIUM','ace atrium',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s8b15a371','Acclaim','acclaim',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s74a5a434','Aries trois','aries trois',null,'katamachi','順化','night','スナック・ラウンジ',''),
('scd30cc66','Believe','believe',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sd896e76d','C Collection','c collection',null,'katamachi','順化','night','スナック・ラウンジ',''),
('scf57e8cf','CAMELLIA','camellia',null,'katamachi','順化','night','スナック・ラウンジ','camellia20071206'),
('s14ccb856','CAVERNA AZZURRA','caverna azzurra',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s8652d2be','Diamond','diamond',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s72f2ff38','Girl''s Bar rerain','girl s bar rerain',null,'katamachi','順化','night','スナック・ラウンジ','rerain.com0810'),
('s206ce020','Imari','imari',null,'katamachi','順化','night','スナック・ラウンジ','imari_1221'),
('se715d19f','J’ADORE','j adore',null,'katamachi','順化','night','スナック・ラウンジ','jadore_fukui.lounge'),
('s5dcf0a7e','LOUNGE GLITTER','lounge glitter',null,'katamachi','順化','night','スナック・ラウンジ','glitter.lounge'),
('sf3deac55','LOUNGE Refuge','lounge refuge',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sf0ae02de','Lounge ACE','lounge ace',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s7897de60','Lounge BR','lounge br',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sd6f31ced','Lounge el','lounge el',null,'katamachi','順化','night','スナック・ラウンジ','lounge_el_ocg'),
('sff1f8564','Lounge 凛','lounge りん',null,'katamachi','順化','night','スナック・ラウンジ','lounge.rin'),
('sd7670334','MIZUKI','mizuki',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s7093e6e6','MOGA MODERN GIRL','moga modern girl',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s217715f4','OPUS ONE','opus one',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s86208ee6','SAYA','saya',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sd357eb91','THE Moon.','the moon',null,'katamachi','順化','night','スナック・ラウンジ','the_moon.102'),
('s774bab97','club 蒼','club あお',null,'katamachi','順化','night','スナック・ラウンジ','club_ao_fukui'),
('sa523f63f','ラウンジ Yuka','らうんじ yuka',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sbcdeae46','ラウンジ 阿吽','らうんじ あうん',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sfef16d72','楚々 -soso-','そそ soso',null,'katamachi','順化','night','スナック・ラウンジ','soso_fukui'),
('s4178b9d7','篠','しの',null,'katamachi','順化','night','スナック・ラウンジ',''),
('se1936e87','良玄 RYOGEN','りょうげん ryogen',null,'katamachi','順化','night','スナック・ラウンジ',''),
('sf693ab32','麻衣','まい',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s0a007fe7','黄色いハンカチ','きいろいはんかち',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s3d6abb7e','Agit(アジト)','agit あじと',null,'katamachi','順化','night','バー','agit19961220'),
('se8494126','Bistro Salice','bistro salice',null,'katamachi','順化','night','バー','salicefukui_pr'),
('s20f30845','ばあー くろぽん','ばあー くろぽん',null,'katamachi','順化','night','バー','kanekohideaki'),
('sefe7247a','パブ&レストラン樽','ぱぶ れすとらんたる',null,'katamachi','順化','night','スナック・ラウンジ',''),
('s82b13c27','煉瓦館','れんがかん',null,'katamachi','順化','night','バー','rengakan'),
('sfa7d871b','Amusemet Bar DOOR','amusemet bar door',null,'katamachi','順化','night','バー','bar.door'),
('s9d27ed13','BAR FLOW(フロー)','bar flow ふろー',null,'katamachi','順化','night','バー',''),
('s2fd277f4','BAR RADIO','bar radio',null,'katamachi','順化','night','バー',''),
('s430f7a01','BAR UTa','bar uta',null,'katamachi','順化','night','バー',''),
('sd6e4569f','BAR くろひげ','bar くろひげ',null,'katamachi','順化','night','バー',''),
('sa4207224','BAR 九龍(クーロン)','bar きゅうりゅう くーろん',null,'katamachi','順化','night','バー',''),
('s61116b31','BAR 浪漫','bar ろうまん',null,'katamachi','順化','night','バー','bar_roman_fukui'),
('sa6c87222','BIRTH','birth',null,'katamachi','順化','night','バー',''),
('sf7bfd3ec','Bar jake','bar jake',null,'katamachi','順化','night','バー',''),
('s88c7c8d2','Bar レッツゴーヤング','bar れっつごーやんぐ',null,'katamachi','順化','night','バー','lets_go_young'),
('sa41d8a45','DUFFTOWN','dufftown',null,'katamachi','順化','night','バー',''),
('s8b4e803f','K''z Bar(ケーズ・バー)','k z bar けーず ばー',null,'katamachi','順化','night','バー',''),
('sb0eea03d','Musica Y BAR SOMBRERO','musica y bar sombrero',null,'katamachi','順化','night','バー',''),
('s406971a8','ORIGINAL SOUND mix cafe CREME','original sound mix cafe creme',null,'katamachi','順化','night','バー','mix_cafe_creme'),
('sd0742f1e','SECRET CLASSICAL','secret classical',null,'katamachi','順化','night','バー',''),
('s5cf909b9','THE BAR LOTUS','the bar lotus',null,'katamachi','順化','night','バー',''),
('sf9e86472','THE BAR [i:st](イースト)','the bar i st いーすと',null,'katamachi','順化','night','バー',''),
('sa1233ddd','gri-gri','gri gri',null,'katamachi','順化','night','バー',''),
('s6f9d5eee','ブラッセリー&クラシックバー Very Good','ぶらっせりー くらしっくばー very good',null,'katamachi','順化','night','バー','verygoodbar'),
('scfaffe0c','レストバー season(シーズン)','れすとばー season しーずん',null,'katamachi','順化','night','バー',''),
('sd7e77550','ワインバル フォンデン','わいんばる ふぉんでん',null,'katamachi','順化','night','バー','fonden_winebar'),
('s2859042f','和食海鮮ダイニング 柳庵','わしょくかいせんだいにんぐ やなぎあん',null,'katamachi','順化','gourmet','寿司・海鮮','yanagimachi_ryuan')
on conflict (slug) do update set name=excluded.name, zone=excluded.zone, town=excluded.town,
  kana=case when public.shops.kana = '' then excluded.kana else public.shops.kana end,
  opened_on=coalesce(public.shops.opened_on, excluded.opened_on),
  category=excluded.category, genre=excluded.genre,
  instagram=case when public.shops.instagram_from='research' then excluded.instagram else public.shops.instagram end;
