-- build_seed.py が作るファイル。手で直さないこと。
insert into public.shops (slug,name,zone,town,category,genre,instagram) values
('s7fbd8215','Cafe&Bar まっしろ','ekimae','中央','night','バー','mashiro_cafeandbar'),
('s8441afb1','Mon Somme(モンソム)','ekimae','中央','gourmet','その他','mon.somme'),
('s31dcadd0','cafe はな','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sfe2ad9a7','la table de Roche(ロッシュ)','ekimae','手寄','gourmet','その他',''),
('s4dfe2eb3','おいしいふくい大満喫フェア','ekimae','中央','gourmet','その他',''),
('sea1d495e','まンまや おちょkitchen','ekimae','日之出','gourmet','その他',''),
('s691f731e','わおん書房','ekimae','中央','gourmet','その他','waonbooks'),
('s54c3c504','エンジョeat!!! CAFE','ekimae','中央','gourmet','カフェ・スイーツ','enjoyeat_fukui'),
('s44dd52a3','クレープ&バル FUKU NOTE','ekimae','中央','gourmet','居酒屋',''),
('s5be27486','スローベリィ くるふ福井駅福井店/高井屋','ekimae','中央','gourmet','その他',''),
('s9bf2cb0a','ハピリン総合受付','ekimae','中央','gourmet','その他','happiring_fukui'),
('sad3393df','マルノウチ フクラ','ekimae','中央','gourmet','その他',''),
('s7d7bd31f','小籠包ダイニング 鼎''s by JIN DIN ROU','ekimae','中央','gourmet','その他',''),
('s7896880c','椿宗善 日之出店','ekimae','日之出','gourmet','その他','tsubakisozen'),
('s5cb95492','焼きそば専門店 金波','ekimae','中央','gourmet','そば・うどん','yakisoba_kinpa'),
('s96304935','爽茶','ekimae','中央','gourmet','その他','socha_cafe'),
('s09c213ea','若廣(くるふ福井駅店)','ekimae','中央','gourmet','その他','wakahiro_jp'),
('saec8252a','茶屋cafe あたらしや','ekimae','中央','gourmet','カフェ・スイーツ','atarashiyaasuwayama'),
('s0ed71686','開花亭 BIS','ekimae','中央','gourmet','その他',''),
('sabcab050','韓国厨房 崔家','ekimae','中央','gourmet','アジア・各国料理','saike_fukui'),
('s1a91596b','食べる本屋さん','ekimae','中央','gourmet','その他','taberuhonyasan_fukuiseibu'),
('sd2740f86','駅前中華そば だるまや','ekimae','中央','gourmet','そば・うどん',''),
('s7616aa93','麺匠 麦之助(MINIE店)','ekimae','中央','gourmet','ラーメン','mensho_muginosuke'),
('sb2f49779','お好み焼たなか','ekimae','照手','gourmet','その他',''),
('s268c7b8a','さくら茶屋you‐canビル店','ekimae','中央','gourmet','その他',''),
('sb72278fe','たけや','ekimae','照手','gourmet','その他',''),
('s4ed8240c','ひらい','ekimae','大手','gourmet','その他',''),
('sbab28a94','小次郎','ekimae','大手','gourmet','その他',''),
('s4d076cd8','金ちゃん','ekimae','中央','gourmet','その他',''),
('s1c7e5b4b','PLAYCE(プレイス)','ekimae','中央','gourmet','その他','playce_fukui'),
('s56b39f6a','RUNNY PICNIC(ラニーピクニック)','ekimae','中央','gourmet','その他','runny.picnic'),
('s7ed82504','日々色々(ヒビイロイロ)','ekimae','大手','gourmet','その他','hibiiroiro291'),
('s2c421305','Fukui French Augus(オージュ)','ekimae','中央','gourmet','その他','aujus_fukui'),
('sc0ea7c02','NY FoodCourt BEER GARDEN 〜そらのガーデン〜','ekimae','中央','gourmet','その他','soranogarden'),
('s190e48bf','かんきち 冷凍食品の無人販売所 福井駅前店','ekimae','大手','gourmet','その他',''),
('s94a1ef56','自動販売機 越前かにめし','ekimae','中央','gourmet','寿司・海鮮',''),
('sfb0971c5','越前蕎麦倶楽部','ekimae','中央','gourmet','そば・うどん','echizensobaclub'),
('s869d24c5','Asia Mart','ekimae','中央','gourmet','その他',''),
('s56ad5248','FOODLAB Delicious food stores','ekimae','中央','gourmet','その他','foodlab.fukui'),
('sf0563360','NAM LONG QUAN(ナム ロン クァン)','ekimae','中央','gourmet','その他',''),
('s0c1bb85e','まちのちいさなちーずやさん HAPPY CHEESE','ekimae','中央','gourmet','その他',''),
('s2c3cd67e','やまや 彌右衛門 くるふ福井駅店','ekimae','中央','gourmet','その他',''),
('s2e168218','フルーツのウメダ 福井駅前本店/フルーツパーラー果樹園','ekimae','中央','gourmet','カフェ・スイーツ','fruit_no_umeda_official'),
('sa7f6929f','天たつ くるふ福井駅店','ekimae','中央','gourmet','その他','tentatsu_unisho.fukui'),
('s83a0e0a1','株式会社 カガセイフン','ekimae','','gourmet','その他',''),
('s8a05cfd9','越前田村屋 くるふ福井駅店','ekimae','中央','gourmet','その他','tamuraya_fukui'),
('s0810244b','開花亭 kuri-ya','ekimae','中央','gourmet','その他',''),
('s3d3c6143','Bear’sBar','ekimae','照手','gourmet','その他',''),
('se66b1d1d','Swing’n‐Base','ekimae','中央','gourmet','その他',''),
('s08b6d000','fukui cafe Chadou','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('s281bf00b','あすわ','ekimae','大手','gourmet','その他',''),
('sf090ca5b','おたん','ekimae','中央','gourmet','その他',''),
('s378113ab','かつき','ekimae','中央','gourmet','焼肉・肉料理',''),
('s5ce0e5b0','かりゆし','ekimae','日之出','gourmet','その他',''),
('s2d75effd','きぬ','ekimae','中央','gourmet','その他',''),
('s272fb962','さつき','ekimae','中央','gourmet','その他',''),
('s2e9f2fb6','とらや','ekimae','大手','gourmet','その他',''),
('s8003c885','のみすけ','ekimae','中央','gourmet','その他',''),
('se0fb1c38','ほていや','ekimae','中央','gourmet','その他',''),
('scc329f9e','まると','ekimae','日之出','gourmet','その他',''),
('s1f0b3df9','むらさき','ekimae','大手','gourmet','その他',''),
('s398e9bd3','オリーブの木','ekimae','大手','gourmet','その他',''),
('s0091a48e','カントリ','ekimae','大手','gourmet','その他',''),
('sb32fb9cb','カーサ福井西武店','ekimae','中央','gourmet','その他',''),
('sa02f4751','カームタイム(CalmTime)','ekimae','大手','gourmet','アジア・各国料理',''),
('sd08e56bb','サロン女湯','ekimae','中央','gourmet','その他',''),
('s2e2c957c','ヤマシタパン','ekimae','大手','gourmet','カフェ・スイーツ',''),
('sa871019f','七平','ekimae','手寄','gourmet','その他',''),
('sb1ac409e','今川焼本舗','ekimae','中央','gourmet','その他',''),
('s2799f8eb','匠きし','ekimae','中央','gourmet','その他',''),
('se800168c','印度','ekimae','大手','gourmet','その他',''),
('s7822e51b','女子寮/福井駅前店','ekimae','大手','gourmet','その他',''),
('s6133a887','料理 仕出し 与志多','ekimae','照手','gourmet','その他','tabakoya.yamamachi'),
('sd2851ea1','晴海','ekimae','中央','gourmet','その他',''),
('s2780b245','株式会社アンクル','ekimae','大手','gourmet','その他',''),
('s1598a124','桜むすび','ekimae','中央','gourmet','その他',''),
('s1edee58d','樅ノ木','ekimae','中央','gourmet','その他',''),
('s03b15c52','海賊艇','ekimae','中央','gourmet','その他',''),
('s81ab1c3d','熊五郎','ekimae','中央','gourmet','その他',''),
('s55f3d432','甘露司 飛嶋','ekimae','中央','gourmet','その他',''),
('sf5bfdba9','番匠本店 上りホーム店','ekimae','中央','gourmet','その他',''),
('sd56ace3d','福井ワシントンホテル・バロン','ekimae','大手','gourmet','その他',''),
('s7d67dc69','福井大麦倶楽部','ekimae','日之出','gourmet','その他',''),
('s707b8afd','福井県庁食堂','ekimae','大手','gourmet','その他',''),
('sf371dde9','秋吉 New秋吉','ekimae','大手','gourmet','その他',''),
('sc17f4e42','芝寿し 福井店','ekimae','大手','gourmet','その他',''),
('sc0f5aa2d','越前市場','ekimae','手寄','gourmet','その他',''),
('sea986e8d','モンナリッサの森','ekimae','中央','gourmet','アジア・各国料理',''),
('se5583b37','白菜美人','ekimae','中央','gourmet','アジア・各国料理',''),
('s84142e3a','FanFan','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s0da987fe','Italian Kitchen VANSAN 西武福井店','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('sd70a6325','イタリアスパゲティ','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('sd25ff878','イタリア料理 クッチーナ','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s02550abd','トレパーチェ・イタリアンレストラン','ekimae','大手','gourmet','イタリアン・フレンチ',''),
('se14b3b3f','ドレッセ','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s90e001cc','侍パスタ','ekimae','手寄','gourmet','イタリアン・フレンチ',''),
('s76408c0a','Paleo Brew Cafe','ekimae','中央','gourmet','カフェ・スイーツ','brewcafe00'),
('sa180b397','Soy Sweets ごーる堂 Do+','ekimae','中央','gourmet','カフェ・スイーツ','soysoftcream_goldo'),
('sc3c80ac6','cafe ieme','ekimae','中央','gourmet','カフェ・スイーツ','cafe_ieme'),
('s60e84920','あんカフェ 大嶋','ekimae','中央','gourmet','カフェ・スイーツ','an.cafe.oshima'),
('s9d624ce9','ヨリバ(YORIVER)','ekimae','中央','gourmet','カフェ・スイーツ','yoriver_asuwa'),
('s276f99eb','抹茶庵 福井中央店','ekimae','中央','gourmet','カフェ・スイーツ','matchaan_fukui'),
('s44b5276e','PUITS D’AMOUR','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('s8a3f24e9','UCC CAFE MERCADO 福井西武','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s359812db','YEN','ekimae','大手','gourmet','カフェ・スイーツ',''),
('sab0da53d','cafe maachar','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s13905151','かがみ','ekimae','大手','gourmet','カフェ・スイーツ',''),
('sbcb69889','きんつばの中田屋 プリズム福井水仙花店','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s5fcc5b45','つゆ','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s86e1194f','ぴえろはうす','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('sad7e62bf','みるく茶庵','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s91dea10e','るうぶる','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s859b836c','れーるろーど','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s478d54dc','カフェるん','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s36103bc2','カフェ・カプチーナ','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s2a1fd4c1','キルトカフェ・趣味工房','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s5cdbf379','クリーミードーナツ 福井駅前店','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s67d9b1ae','コーヒー専門吉田','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sa20e3e11','サロンド・GO','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s1b88cf41','シークチョイスカフェ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s6f1aaa8f','ダーツカフェ Green Box','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('sda7065aa','チャーム','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s8e708fc9','トーヨー','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s0f4e999b','ニシムラカフェ駅前店','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s4c7ec2c3','ニッパー','ekimae','照手','gourmet','カフェ・スイーツ',''),
('sfae834e9','ハーフ','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('s1b5bdc0b','ベーカリープラザ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s6bb5bc7f','ポニー純喫茶','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s539f12a1','マタリ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s567b4238','ムーラン','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sc8e51bff','モジカフェ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sb5d66038','モンターニュ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sf06a7d20','ヤン・カフェ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s57778317','ユトリ珈琲店 AOSSA店','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('sf253ab07','ユミ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s4d0b8d82','リトルマーメイドくるふ福井駅','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sa0155603','ルビー','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sb76a8139','ル・ピュイ','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('scebf7e9b','ルーツカフェ(ROUTE’SCAFE)','ekimae','照手','gourmet','カフェ・スイーツ',''),
('sc0f77424','古城','ekimae','大手','gourmet','カフェ・スイーツ',''),
('sf14bda3d','天秤座','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s73548a07','奈々重','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s98b47d7f','快活CLUB/福井駅前店','ekimae','大手','night','スナック・ラウンジ',''),
('s10e1f57f','森のフェスタおばさん','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s5fa54a4e','森乃家','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s5c294506','神戸ふう月堂福井店','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s94386578','絵紋','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s61151c82','花','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s572583db','茶房談話室','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s6efdb81a','蒼山','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('sbf0a4361','逢園','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s4d28e1e7','銀座茶廊','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s96ac50a1','Kisaki CAFE CENTRAL PARK','ekimae','大手','gourmet','カフェ・スイーツ',''),
('seff70599','とろけるクレープ MOMI&TOY’S 福井駅前店','ekimae','中央','gourmet','カフェ・スイーツ','momitoy_fukuiekimae'),
('sbc9f8a54','カフェレストラン su_mu(スム)','ekimae','中央','gourmet','カフェ・スイーツ','su_mu300567'),
('s1018b4c4','CAFÉ52(カフェ ゴジュウニ)','ekimae','中央','gourmet','カフェ・スイーツ','cafebar52'),
('s0bd2f63c','HANDS COFFEE(ハンズコーヒー)','ekimae','中央','gourmet','カフェ・スイーツ','hands_coffee'),
('s1aafc2bb','Att kitchen( アットキッチン)','ekimae','中央','gourmet','カフェ・スイーツ','att_kitchen_'),
('s33de1202','CAFÉ CON TE(カフェコンテ)','ekimae','中央','gourmet','カフェ・スイーツ','cafe.conte2026'),
('s0e036df3','CTS(シータス)','ekimae','照手','gourmet','カフェ・スイーツ','cts_coffee_to_sand'),
('s6f98adcc','Magari Coffee(マガリコーヒー)','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s4098663f','カフェまてき','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s92e75c9b','シューハウス','ekimae','中央','gourmet','その他',''),
('sb543236c','高級和栗モンブラン専門店 栗歩 福井駅前店(くりほ)','ekimae','中央','gourmet','カフェ・スイーツ','waguri_montblanc_kuriho'),
('sc4ebbf42','Okazu&bread(オカズ アンド ブレッド)','ekimae','手寄','gourmet','カフェ・スイーツ','okazu_and_bread'),
('s478c9e8f','エトワァル まるせん','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s83d42a65','マルサパン','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('sa186b57e','AFTERGLOW CHOCOLATE(アフターグロウチョコレート)','ekimae','照手','gourmet','カフェ・スイーツ','afterglow_chocolate'),
('sb4ad068c','Good Smile Donut(グッドスマイルドーナツ)','ekimae','日之出','gourmet','カフェ・スイーツ','goodsmile.donut'),
('sd546a9d9','スコーン専門店 肆 -よん-','ekimae','中央','gourmet','カフェ・スイーツ','yon_scone'),
('s7ee907f6','サニーさんの農園マルシェ','ekimae','中央','gourmet','カフェ・スイーツ','sunnysfarmmarche'),
('s0ac00f12','8番らーめん/くるふ福井駅店','ekimae','中央','gourmet','ラーメン',''),
('s75e3bf56','いちや福井駅前店','ekimae','中央','gourmet','ラーメン',''),
('s61d8b801','なん・なん亭 福井店','ekimae','大手','gourmet','ラーメン',''),
('s37b5b5ff','中華 集集','ekimae','中央','gourmet','ラーメン',''),
('s30c78e0f','Bistro&Bar GLOUTONNE','ekimae','中央','night','バー',''),
('s90da58ca','キッチントリアージュ','ekimae','中央','gourmet','洋食',''),
('s8a28b280','キナリ','ekimae','日之出','gourmet','洋食','_____kinari'),
('s76637454','サラマンジェフ','ekimae','中央','gourmet','洋食',''),
('s0a856f1a','トラットリア チャオ','ekimae','中央','gourmet','イタリアン・フレンチ','trattoria_ciao_'),
('s6f5e18f4','西武福井店 ダイニングスクエア','ekimae','中央','gourmet','洋食',''),
('se64356d9','あみだそば はなれ','ekimae','中央','gourmet','そば・うどん',''),
('s03a6dbe6','おそばだ うどんだ 越前','ekimae','中央','gourmet','そば・うどん',''),
('s8ad103bd','三井屋','ekimae','つくも','gourmet','そば・うどん',''),
('s4583b225','蕎麦庵 sio(シオ)','ekimae','中央','gourmet','そば・うどん','sobaansio40'),
('sf52878a6','西村屋日之出店','ekimae','日之出','gourmet','そば・うどん',''),
('s6e3a80b8','MINIE(ミニエ)','ekimae','中央','gourmet','焼鳥・串','minie_fukui'),
('s25796be9','U(ユー)','ekimae','大手','gourmet','焼肉・肉料理','u__fukui'),
('sbebfde1a','パスタと珈琲とカヌレのお店','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s1c5b0523','日豪レストラン ゆめや','ekimae','中央','gourmet','洋食',''),
('s55e7c838','越山若水 行雲(えつざんじゃくすいこううん)','ekimae','中央','gourmet','洋食','etsuzanjyakusui_koun'),
('sd4e68c11','すし日竜(ひりゅう)','ekimae','中央','gourmet','寿司・海鮮','sushi_hiryu'),
('s03f8cc3e','大衆赤酢寿司 ぼんた','ekimae','中央','gourmet','寿司・海鮮',''),
('s9c952b2d','Beer&Grill GRIOMAN(グリオマン)','ekimae','中央','gourmet','居酒屋','grioman_fukui'),
('s0c2231f0','sake to ate(サケトアテ)','ekimae','日之出','gourmet','居酒屋','sake.to.ate'),
('s0f913aee','タコとハイボール','ekimae','中央','gourmet','居酒屋',''),
('se90bbb55','大衆酒場 ラドン','ekimae','中央','gourmet','居酒屋',''),
('see25b77f','手羽先番長 福井駅前店','ekimae','中央','gourmet','居酒屋','tebasakibancho_fukui'),
('sf2bd41d7','魚六(ウオロック)','ekimae','中央','gourmet','寿司・海鮮','uorock291'),
('sb65f332e','酒と肴の旨い店 和華(わか)','ekimae','照手','gourmet','居酒屋','izakaya__waka'),
('s9bc498e5','越前海鮮屋 福井駅前店','ekimae','中央','gourmet','寿司・海鮮',''),
('sc94c43ec','やきとり やすぎ家','ekimae','中央','gourmet','焼鳥・串','yasugiya.tomomi'),
('s0c6c7bbb','たごさく 福井西武','ekimae','中央','gourmet','中華',''),
('s5c375ccf','ゴディバ 西武福井','ekimae','中央','gourmet','中華',''),
('s0a5d3303','ドンク 西武福井店','ekimae','中央','gourmet','中華',''),
('s47b4aa6a','ピリケン 本店','ekimae','つくも','gourmet','中華',''),
('s513f8ff4','ボノボノ プリズム福井店','ekimae','中央','gourmet','中華',''),
('sbd243964','万よし','ekimae','中央','gourmet','中華',''),
('sfc766a3a','御菓子司 栄太楼','ekimae','中央','gourmet','中華',''),
('sbaccabfb','悟空','ekimae','大手','gourmet','中華',''),
('s6c838691','来々軒','ekimae','つくも','gourmet','中華',''),
('s70b0f1a5','満堂紅福井店','ekimae','中央','gourmet','中華',''),
('s0e6cf074','白楽','ekimae','日之出','gourmet','中華',''),
('s6809818c','福林軒','ekimae','中央','gourmet','中華',''),
('s3645db7d','紅蘭','ekimae','中央','gourmet','中華',''),
('s5e66ff80','羽二重餅の古里 マエダセイカ プリズム福井 水仙花店','ekimae','中央','gourmet','中華',''),
('s8e3df346','西遊記','ekimae','中央','gourmet','中華',''),
('s3370fd96','集集','ekimae','中央','gourmet','中華',''),
('sd7ac3a10','鳳城酒家','ekimae','中央','gourmet','中華',''),
('s106b5997','SPICE CURRY &amp; COFFEE Livin&#039; for green','ekimae','中央','gourmet','アジア・各国料理','livin_for_green'),
('s13deb4bc','カレッテリア Cafe&amp;Curry','ekimae','大手','gourmet','アジア・各国料理','caletteria'),
('s39bea949','モーニングトマト','ekimae','中央','gourmet','アジア・各国料理',''),
('s26c0f87c','いちろくらーめん ふくい駅前店','ekimae','中央','gourmet','ラーメン','ichiroku_ramen'),
('s2caeb34f','とりで','ekimae','日之出','gourmet','ラーメン',''),
('s8c4eebb6','屋台 てっちゃんラーメン 福井駅前店','ekimae','中央','gourmet','ラーメン',''),
('s1c461256','屋台 岩ちゃんラーメン','ekimae','','gourmet','ラーメン',''),
('sf311a814','煮干そば・鶏そば 藍 &times; 福井らーめん 五目亭 福井駅前店','ekimae','中央','gourmet','そば・うどん','fukui_ramen_gomokutei'),
('sf5894701','ふ一FUKUMACHIBLOCKMINIE','ekimae','中央','gourmet','中華','fuichi_fukui'),
('sb6f31430','中国料理 紅蘭','ekimae','','gourmet','中華',''),
('sec11e85c','中華料理 ISSEI','ekimae','手寄','gourmet','中華',''),
('s3065bd5e','四季彩中華シノワ','ekimae','大手','gourmet','中華',''),
('s198573a0','四川料理 西遊記','ekimae','','gourmet','中華',''),
('sd35a5578','茶荘・香蘭(ちゃそうこうらん)','ekimae','中央','gourmet','中華','chasoukouran2025111'),
('s67908d92','KOREA','ekimae','中央','gourmet','アジア・各国料理',''),
('s743e8c6c','TARY HOUSE','ekimae','中央','gourmet','アジア・各国料理','taryhouse'),
('se1680e15','ベトナムレストラン Que Huong Quan','ekimae','中央','gourmet','アジア・各国料理',''),
('s6177a351','ホットドッグショップ Dogs','ekimae','大手','gourmet','アジア・各国料理','dogs_hotdog_fukui'),
('sc15721ee','居酒屋 しゃんがり。','ekimae','大手','gourmet','居酒屋','izakaya_shangari_fukui'),
('s53132fd2','あさひそばや','ekimae','中央','gourmet','そば・うどん',''),
('s4aa386ab','おお田','ekimae','大手','gourmet','和食',''),
('sc4757ccf','かき恭','ekimae','中央','gourmet','和食',''),
('s3527a6ce','かわきん','ekimae','大手','gourmet','和食',''),
('s6cf33e3c','こんぴら亭三の丸店','ekimae','大手','gourmet','和食',''),
('s9a9b6a54','さが良','ekimae','照手','gourmet','和食',''),
('sb06737be','さくら茶屋くるふ福井駅店','ekimae','中央','gourmet','和食',''),
('seda0e607','せいもん','ekimae','大手','gourmet','和食',''),
('sfe9342cb','そば勝アオッサ店','ekimae','手寄','gourmet','そば・うどん',''),
('s392c8643','そば勝本店','ekimae','中央','gourmet','そば・うどん',''),
('s977f9ab2','てらしま','ekimae','中央','gourmet','和食',''),
('s64a33e0b','はら田','ekimae','照手','gourmet','和食',''),
('sd815c904','べんがら屋','ekimae','中央','gourmet','和食',''),
('s470d2762','まわるすし中央店','ekimae','中央','gourmet','寿司・海鮮',''),
('sa5b95428','まんもと','ekimae','日之出','gourmet','和食',''),
('s7b9d37ca','やま田','ekimae','中央','gourmet','和食',''),
('sc5d36fef','カルマ繊協ビル店','ekimae','大手','gourmet','和食',''),
('s4a1313e4','ビックリ竹田屋総本店','ekimae','大手','gourmet','和食',''),
('s47175d3f','ミチ','ekimae','中央','gourmet','和食',''),
('s67b72d3c','ランチ屋 麦米','ekimae','大手','gourmet','和食',''),
('sb2683b78','三喜寿司','ekimae','日之出','gourmet','寿司・海鮮',''),
('sd9c0a218','中清','ekimae','中央','gourmet','和食',''),
('s508562d6','今庄そば','ekimae','手寄','gourmet','そば・うどん',''),
('sa7c85c96','信濃','ekimae','中央','gourmet','和食',''),
('sa30f648f','割烹敏','ekimae','中央','gourmet','和食',''),
('s9c6c2422','呑喜','ekimae','中央','gourmet','和食',''),
('sa33c83e7','和食料理 釜蔵','ekimae','中央','gourmet','和食',''),
('s0f7a740d','善甚','ekimae','大手','gourmet','和食',''),
('s3554ccb2','四十萬','ekimae','大手','gourmet','和食',''),
('sc5a5aadf','城の橋','ekimae','手寄','gourmet','和食',''),
('s8ea4c3b0','天新','ekimae','大手','gourmet','和食',''),
('sf7ee645e','太鼓寿し','ekimae','大手','gourmet','和食',''),
('sfed1e0c1','宴会屋','ekimae','大手','gourmet','和食',''),
('s089c89ef','富士','ekimae','日之出','gourmet','和食',''),
('s8fc8b4d9','山清','ekimae','中央','gourmet','和食',''),
('s878f6e02','新日本料理 桜ばし','ekimae','中央','gourmet','和食',''),
('sf4472555','昌冨ずし','ekimae','中央','gourmet','和食',''),
('s33a711ac','昭和寿司','ekimae','照手','gourmet','寿司・海鮮',''),
('s6fe70d3a','楽庵','ekimae','中央','gourmet','和食',''),
('se210380d','歌舞伎寿司本店','ekimae','中央','gourmet','寿司・海鮮',''),
('s8d2bdf59','満里邑','ekimae','中央','gourmet','和食',''),
('s9b10b23a','源治鮨','ekimae','大手','gourmet','寿司・海鮮',''),
('s7ad15852','照寿し','ekimae','中央','gourmet','和食',''),
('s3dd83a32','甘泉堂','ekimae','中央','gourmet','和食',''),
('s52fa3549','生簀海鮮 やまもとや','ekimae','大手','gourmet','寿司・海鮮',''),
('sea9725fc','町寿司いちもんめ 福井駅前','ekimae','大手','gourmet','寿司・海鮮',''),
('s19600a96','異人館跡風琴亭','ekimae','中央','gourmet','和食',''),
('sf71ab51f','福井山相撲料理','ekimae','中央','gourmet','和食',''),
('sba6e73e6','笏谷そば だるまや西武店','ekimae','中央','gourmet','そば・うどん',''),
('s9c7f80f2','芝寿し 福井西武店','ekimae','中央','gourmet','和食',''),
('sdaf8623c','華家','ekimae','大手','gourmet','和食',''),
('s331b3393','葵納豆料理店','ekimae','照手','gourmet','和食',''),
('sf92fe821','農協のおむすび大手町店','ekimae','大手','gourmet','和食',''),
('sdcf3c594','野のや','ekimae','中央','gourmet','和食',''),
('s897b57f1','鮨志乃介','ekimae','中央','gourmet','寿司・海鮮',''),
('s11678821','あさひそば 本店','ekimae','','gourmet','そば・うどん',''),
('s90c0bd12','あみだそば遊歩庵(ゆうぶあん)','ekimae','中央','gourmet','そば・うどん','amidasoba'),
('s504f30cd','越前つるきそば 本店','ekimae','中央','gourmet','そば・うどん',''),
('s80891f7c','お好み焼き エミ','ekimae','大手','gourmet','和食',''),
('sb4d83523','とんかつ・そば 吉ちょう','ekimae','大手','gourmet','そば・うどん',''),
('s9ca8b5be','みそかつのむろまち','ekimae','中央','gourmet','焼肉・肉料理',''),
('s02770244','富士喜FUKUMACHIBLOCKMINIE','ekimae','中央','gourmet','焼肉・肉料理','fujiki_2020'),
('sc9d4dc84','熟成とんかつ 天膳 ハピリン店','ekimae','中央','gourmet','焼肉・肉料理','fukui.tonkatu.amazen'),
('s0ce20144','RICE BAR CRAFT SAKE LABO','ekimae','','night','バー',''),
('s147f682c','お食事処 飛彈','ekimae','中央','gourmet','和食','hida_fukui'),
('sd42a3491','しゃぶしゃぶ・鍋・割烹 銀座','ekimae','','gourmet','和食',''),
('s2080a93b','まちDeli かくれわ食堂','ekimae','中央','gourmet','和食','kakurewa2016'),
('s44530f58','一品料理 四十萬','ekimae','','gourmet','和食',''),
('s00743a4b','旬魚とおでん 味美家','ekimae','日之出','gourmet','寿司・海鮮',''),
('s98913494','浜町 かつき','ekimae','','gourmet','焼肉・肉料理',''),
('s304f9740','福井フェニックスホテル 和食・茶房 養浩館','ekimae','大手','gourmet','和食',''),
('sfa13ee3a','紋や','ekimae','中央','gourmet','和食',''),
('s23a62a6f','蟹と海鮮ぼんた くるふ福井駅店','ekimae','中央','gourmet','寿司・海鮮','kanibonta'),
('s11804aca','越前がに・旬のお料理 らでん','ekimae','中央','gourmet','和食','raden0428'),
('sc9372fdd','越前蕎麦・お食事処 花ひらく','ekimae','','gourmet','そば・うどん',''),
('s6726c0fb','魚善','ekimae','','gourmet','寿司・海鮮',''),
('s1faa0bf5','魚菜園','ekimae','中央','gourmet','寿司・海鮮',''),
('sb3231094','本格職人にぎり や台ずし 福井駅前町','ekimae','中央','gourmet','寿司・海鮮','yataizushi_official'),
('s3f187b94','焼肉 牛成 西武福井店','ekimae','中央','gourmet','寿司・海鮮','homaresushi'),
('s283663bd','越前あて巻き デリアテール','ekimae','中央','gourmet','寿司・海鮮','deliaterre_minie'),
('sc9ee101d','鮨 仲島','ekimae','','gourmet','寿司・海鮮',''),
('s1300faa8','鮨清(すしせい)','ekimae','中央','gourmet','寿司・海鮮','sei2025525'),
('sb43852dc','割烹料亭 かき恭','ekimae','','gourmet','和食',''),
('s137458de','和の食 忠兵衛(ちゅうべえ)','ekimae','中央','gourmet','和食',''),
('sf1f0a0fe','和心味NAGOMI たち花','ekimae','','gourmet','和食',''),
('sd4995ad9','日本料理 越前がに 浜町緒ばた','ekimae','中央','gourmet','和食',''),
('s048375a2','旬味 泰平','ekimae','中央','gourmet','和食',''),
('s55a5d4dc','楽teiなか田 ゙(らくていなかだ)','ekimae','中央','gourmet','和食','rakutei_nakada'),
('sc9fc0c44','浜町 日々','ekimae','','gourmet','和食',''),
('sd6f00f4e','浜町 香爐園','ekimae','','gourmet','和食',''),
('sa59d072a','美食 恵長庵 まんもと','ekimae','','gourmet','和食',''),
('s802d1072','開花亭 sou-an','ekimae','','gourmet','和食',''),
('s0e3dd365','開花亭/SOU‐AN','ekimae','中央','gourmet','和食',''),
('sd3fab077','kitchen 和(キッチンなごみ)','ekimae','大手','gourmet','和食','kitchennagomi2023111'),
('sf0f71534','お食事処 ほていや','ekimae','中央','gourmet','和食',''),
('scf8cca10','ふくいのこめとだし まるしん','ekimae','中央','gourmet','和食','marushin_kometodashi'),
('s99704c4a','凸凹29ごはん 福井市役所地下','ekimae','','gourmet','和食',''),
('s1c1b7239','福井肉食堂','ekimae','中央','gourmet','焼肉・肉料理','kurufu_nikusyokudo'),
('sf517e00e','郷土料理・お食事処 福福茶屋','ekimae','中央','gourmet','和食','hukubuku2929'),
('s7dbb5b39','BLUESTOCKING(ブルーストッキング)','ekimae','中央','gourmet','カフェ・スイーツ','bluestocking.seibu'),
('s437b3812','Cafe CoCotte','ekimae','中央','gourmet','カフェ・スイーツ','cafecocotte420'),
('saa12fe5f','Cafe リンデン 越前ふくい美術館','ekimae','大手','gourmet','カフェ・スイーツ','echizen_fukui_artmuseum_'),
('sa39c0566','Dessert &amp; Coffee papillote','ekimae','中央','gourmet','カフェ・スイーツ','papillote_fukui'),
('s4fc16885','NIVI SPECIALTY COFFEE(ニビ スペシャルティコーヒー)','ekimae','中央','gourmet','カフェ・スイーツ','nivi_specialty_coffee'),
('se8ee5656','Organic Vegan cafe 深緑','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s8f66dd35','イタリアン・トマト CafeJr. 福井西武店','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('sf2264074','ベビーカステラ専門店 さんじのおやつ 観光交流センター店','ekimae','手寄','gourmet','カフェ・スイーツ','sanjinooyatsu_fk1001'),
('sd708f1b4','点 葉巻室 福井店','ekimae','中央','gourmet','カフェ・スイーツ','ten_cigar_room_fukui'),
('sdcaf3a90','紅茶のお店 RanaTea','ekimae','中央','gourmet','カフェ・スイーツ','ranatea_fukui'),
('s4c99333d','茶楽 かぐや 西武福井店','ekimae','中央','gourmet','カフェ・スイーツ','saraku_kaguya'),
('s3edeff2f','MAGGIE&#039;S FARM','ekimae','中央','gourmet','カフェ・スイーツ','maggies_farm1986'),
('s2fdfd97e','カフェテラス','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s0d9cf47f','喫茶 珈琲壺 〜コーヒーぽっと〜','ekimae','大手','gourmet','カフェ・スイーツ',''),
('sf633add3','199円生ビールと絶品焼き鳥 居酒屋 「三代目」鳥メロ 福井駅前店','ekimae','中央','gourmet','焼鳥・串',''),
('s8b76fe09','Churrascaria ban(シュラスカリア バン) 福井店','ekimae','中央','gourmet','居酒屋',''),
('sb67ea96d','個室居酒屋 葵屋-あおいや- 福井駅前店','ekimae','中央','gourmet','居酒屋',''),
('s850722a5','おふくろの味こころ','ekimae','大手','gourmet','居酒屋',''),
('s67de7438','のんのん','ekimae','中央','gourmet','居酒屋',''),
('s65d5344b','のんべえよしき','ekimae','大手','gourmet','居酒屋',''),
('sf95c753b','まごころ','ekimae','中央','gourmet','居酒屋',''),
('s333dfc62','みなり','ekimae','大手','gourmet','居酒屋',''),
('s3cbdc57e','もみじ 福井駅前店','ekimae','中央','gourmet','居酒屋',''),
('sf1a7d4f6','ろ組 福井駅前店','ekimae','中央','gourmet','居酒屋',''),
('sdefd9b7f','ブラスリー河合','ekimae','中央','gourmet','居酒屋',''),
('s59c41c33','串・魚介類 炭火焼の店 織々屋','ekimae','中央','gourmet','焼鳥・串',''),
('s3aba873d','個室完備 大衆とり酒場 とりいちず 福井駅前店','ekimae','中央','gourmet','居酒屋','toriichizu_mania'),
('sd40f6f26','個室居酒屋 くいもの屋わん 福井駅前店','ekimae','中央','gourmet','居酒屋',''),
('s90c2ae57','六兵衛','ekimae','中央','gourmet','居酒屋',''),
('sd01dbf56','割烹 桝酒','ekimae','大手','gourmet','居酒屋',''),
('s098b101b','千本','ekimae','中央','gourmet','居酒屋',''),
('sa4f16f4c','味の王様ガレリア店','ekimae','中央','gourmet','居酒屋',''),
('safba9b18','土鍋ご飯《米と魚 たて涌》','ekimae','中央','gourmet','寿司・海鮮','tatewaki_kometosakana'),
('s8cc017e9','安楽','ekimae','大手','gourmet','居酒屋',''),
('s13a09f65','寿司・地酒 はやし','ekimae','大手','gourmet','寿司・海鮮',''),
('s097c40a1','寿司和食処 わだつみ','ekimae','大手','gourmet','寿司・海鮮',''),
('s96ca45ee','小料理のむ喜 優','ekimae','中央','gourmet','居酒屋',''),
('sea741e8d','山がっちゃん家の台所','ekimae','大手','gourmet','居酒屋',''),
('s1853373d','横浜天下鳥 福井駅前店','ekimae','中央','gourmet','居酒屋',''),
('s333a28c2','然の家 味彩','ekimae','中央','gourmet','居酒屋',''),
('s47fbad00','焼肉 肉鍋 肉吟 福井駅前店','ekimae','中央','gourmet','焼肉・肉料理',''),
('se04557f5','玄達市場','ekimae','手寄','gourmet','居酒屋',''),
('s04b85b8e','目利きの銀次 福井西口駅前店','ekimae','大手','gourmet','居酒屋',''),
('sa73580d4','福井名物お刺身&豚骨おでん 酒処JET','ekimae','日之出','gourmet','居酒屋',''),
('s7cbf20df','菜香楼 くるふ福井駅店','ekimae','中央','gourmet','居酒屋',''),
('s21231265','越前地魚とおでん酒場 鮨とおでん','ekimae','中央','gourmet','寿司・海鮮',''),
('s583d78f9','越前若狭の旬と地酒 頂き枡 福井駅前東口店','ekimae','日之出','gourmet','居酒屋',''),
('s2298f9e8','越前魚酒 ほやほ家','ekimae','大手','gourmet','寿司・海鮮',''),
('s0000e279','酒菜夜','ekimae','中央','gourmet','居酒屋',''),
('sf2a68918','魚河岸直営 いけす海鮮 ろ組くるふ福井駅店','ekimae','中央','gourmet','寿司・海鮮',''),
('s3ff73c5b','日本料理 橘','ekimae','大手','gourmet','和食',''),
('sbfc0e5ca','とみや','ekimae','中央','gourmet','洋食',''),
('s6831efc4','キンイロキッチンアオッサ店','ekimae','手寄','gourmet','洋食',''),
('s0ff080c0','シュバルージュ','ekimae','手寄','gourmet','居酒屋',''),
('s177662fe','ムサシノ軒','ekimae','手寄','gourmet','洋食',''),
('sdeccc578','ラッキー食堂1階レストラン部','ekimae','中央','gourmet','洋食',''),
('s6b8af86d','名産工房・旬','ekimae','中央','gourmet','洋食',''),
('s1268ca15','日下部','ekimae','中央','gourmet','洋食',''),
('s47640b37','福井厚生年金会館','ekimae','手寄','gourmet','洋食',''),
('s3faa3277','赤茄子亭','ekimae','日之出','gourmet','洋食',''),
('s7daaf531','鉄板料理 薫風','ekimae','日之出','gourmet','洋食',''),
('scc63b563','石窯食堂 Tsumugi','ekimae','大手','gourmet','イタリアン・フレンチ','tsumugi_fukui'),
('sd4759e1c','Alfredo.Alfredo','ekimae','中央','gourmet','イタリアン・フレンチ','alfredo_fukui'),
('sd261cdea','Osteria da Silvano','ekimae','','gourmet','イタリアン・フレンチ',''),
('sdb3f8b40','Ristorante CUCINA','ekimae','','gourmet','イタリアン・フレンチ',''),
('s927e1e54','Sincere Lily','ekimae','中央','gourmet','イタリアン・フレンチ','sincerelily.fukui'),
('s21cb020b','イタリア食堂ITSUKI','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s52f71c78','サイゼリヤ 福井駅前店','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s606e36f0','レストラン・バー 粟樹楼','ekimae','中央','night','バー',''),
('se32d8474','モンシェルトントンカトー','ekimae','中央','gourmet','焼肉・肉料理',''),
('saa7747e6','石窯焼 時ノ鐘','ekimae','','gourmet','焼肉・肉料理',''),
('s22bd026c','鉄板焼肉とジンギスカン ぼんた 福井駅前店','ekimae','大手','gourmet','焼肉・肉料理','jingisukanbonta'),
('sbea13dc1','Bistro &amp; Bar GLOUTONNE','ekimae','中央','night','バー',''),
('s3be015b1','Brasserie Lou(ブラッスリー ルー)','ekimae','中央','gourmet','イタリアン・フレンチ','brasserie_lou'),
('s1e83b17a','Fukui French Aujus','ekimae','','gourmet','イタリアン・フレンチ',''),
('sc1ba17fa','IRISER(イリゼ)','ekimae','大手','gourmet','イタリアン・フレンチ','iriser.fukui'),
('s35ee8df9','RESTAURANT OTSUKA','ekimae','大手','gourmet','イタリアン・フレンチ','restaurantotsuka'),
('s96d87f55','SHEZ SAKAI(シェ サカイ)','ekimae','日之出','gourmet','イタリアン・フレンチ',''),
('sf09a0dcd','Salon De Chef  NAKAO','ekimae','大手','gourmet','イタリアン・フレンチ',''),
('sce77d268','ULO(FUKUMACHI BLOCK)','ekimae','中央','gourmet','イタリアン・フレンチ','ulo_fukui'),
('s55478b75','グリル葵','ekimae','大手','gourmet','イタリアン・フレンチ',''),
('s048ea878','ビストロ 後藤','ekimae','中央','gourmet','イタリアン・フレンチ','athletic8488'),
('saf7eab35','フランス酒場 Antique (アンティーク) 福井駅前','ekimae','中央','gourmet','居酒屋','antique__fukui'),
('s132f7ebc','欧風料理 Salle a manger F','ekimae','','gourmet','イタリアン・フレンチ',''),
('sa5d3f7cc','二ノ丸グリル','ekimae','大手','gourmet','洋食',''),
('sfb4be5dc','洋食&創作イタリアン Kitchen Toriage','ekimae','','gourmet','イタリアン・フレンチ',''),
('s7d628105','吉野寿司','ekimae','中央','gourmet','寿司・海鮮','fukui_yoshinozushi'),
('s641ed098','香爐園','ekimae','中央','gourmet','寿司・海鮮',''),
('s8be5beb6','いっ福亭','ekimae','日之出','gourmet','焼肉・肉料理',''),
('s588dd8ac','ホルモン 焼肉 お食事処 はるや','ekimae','日之出','gourmet','焼肉・肉料理',''),
('sb5bcd9fa','焼肉ホルモン はらたん 福井駅前店','ekimae','中央','gourmet','焼肉・肉料理',''),
('sd63ab7c5','そば処 三国屋','ekimae','大手','gourmet','そば・うどん',''),
('sb68ff2b6','今庄そば 福井駅コンコース店','ekimae','中央','gourmet','そば・うどん',''),
('sb13e7aef','福そば','ekimae','中央','gourmet','そば・うどん',''),
('s9356b702','蕎麦Dining 一福','ekimae','中央','gourmet','そば・うどん','ippuku129'),
('sa2fb7beb','福井名物ずわい蟹料理 こまつや','ekimae','照手','gourmet','寿司・海鮮',''),
('sde46651d','御菓子司 あまとや','ekimae','つくも','gourmet','カフェ・スイーツ',''),
('sc83ffc72','御菓子司 森八大名閣','ekimae','大手','gourmet','カフェ・スイーツ',''),
('sb541e4f7','村中甘泉堂本店/パティスリーKANSENDO','ekimae','中央','gourmet','その他',''),
('s415dda88','水羊かん/えがわ 【ふくいの恵み認定商品】','ekimae','照手','gourmet','その他',''),
('s10d31742','米粉フィナンシェ旅歩記 【ふくいの恵み認定商品】','ekimae','つくも','gourmet','その他',''),
('s43b701a9','羽二重餅總本舗 松岡軒 本店','ekimae','中央','gourmet','その他','matsuokaken.habutaemochi'),
('sc38bb334','新幹線開業【福井駅前】ガラポン!レシートチャレンジ','ekimae','中央','gourmet','その他',''),
('se183111c','お酒とおばんざい ななと実','ekimae','大手','gourmet','居酒屋','nanatomi_sachiko'),
('sbc95f6c8','きはちらくはち 駅前店','ekimae','大手','gourmet','居酒屋','kihachirakuhachi'),
('s2ec1c847','ろばた焼 弥吉 駅前店','ekimae','大手','gourmet','居酒屋',''),
('sf5065559','名古屋コーチンの 翠翔 福井駅前店','ekimae','大手','gourmet','居酒屋','_suisyooo'),
('saadbc958','呑み処 たけうち','ekimae','大手','gourmet','居酒屋',''),
('s9f25bc08','居酒屋 竜の髭','ekimae','','gourmet','居酒屋',''),
('s10c5daa0','旬菜鮮魚と旨い酒 わらび 福井駅前店','ekimae','','gourmet','寿司・海鮮',''),
('s745b95fb','旬香逎燈 煙や','ekimae','大手','gourmet','居酒屋',''),
('s4c5514d8','沖縄料理 南風 ぱいかじ','ekimae','','gourmet','居酒屋',''),
('s7e2048c7','炭火焼の店 織々屋','ekimae','','gourmet','居酒屋',''),
('sf22774df','福井 海鮮 KAKETUKE 福井MINIE店','ekimae','中央','gourmet','寿司・海鮮','kaketuke_fukui'),
('sb48f82a3','越前鮮魚と炭火焼 炭と魚 福井駅前店','ekimae','中央','gourmet','寿司・海鮮','sumi.to.sakana'),
('s11b4c972','遊月家参百圓食堂','ekimae','大手','gourmet','居酒屋',''),
('sb051e496','酒場 丸子','ekimae','','gourmet','居酒屋',''),
('s8579cb95','酒季織々 旨い肴と和み酒 錦輝','ekimae','','gourmet','居酒屋',''),
('s799a6b23','飲み喰い処 和楽路','ekimae','中央','gourmet','居酒屋',''),
('scc22d7b3','骨付鳥、からあげ、ハイボール がブリチキン。 福井駅前店','ekimae','中央','gourmet','居酒屋','gabukichi_gaburichicken'),
('s0e47f167','魚のうまい店 寿司居酒屋 かんきち 福井駅前店','ekimae','大手','gourmet','寿司・海鮮','kankichi_291'),
('sb9357380','魚六 -UOROCK-','ekimae','','gourmet','寿司・海鮮',''),
('s05a24e2d','鶏屋 塚田農場 福井駅前店','ekimae','中央','gourmet','居酒屋','fukui_tsukadanojo'),
('sa9f71617','串カツ田中 福井駅前店','ekimae','大手','gourmet','焼鳥・串','kushikatsu_tanaka'),
('s31b3bcc7','串カツ酒場 ナニワ屋 福井駅前店','ekimae','中央','gourmet','焼鳥・串',''),
('s239cbf2c','炭・串焼 べんがら屋','ekimae','','gourmet','焼鳥・串',''),
('sc751def6','焼き鳥 八穴(はちのあな)','ekimae','大手','gourmet','焼鳥・串','hachinoana_yakitori'),
('s75cbfd09','秋吉 New秋吉店','ekimae','','gourmet','焼鳥・串',''),
('sebc25d2d','スナックおすみ','ekimae','中央','night','スナック・ラウンジ',''),
('s565c2c14','Disco×Club×Karaoke Rum Fire','ekimae','中央','night','スナック・ラウンジ',''),
('s2a51afb8','G’sBAR 0821','ekimae','中央','night','スナック・ラウンジ',''),
('sd8dd5f20','Rum Fire(ラムファイヤ―)','ekimae','中央','night','スナック・ラウンジ',''),
('sdd4a89da','Santana','ekimae','中央','night','スナック・ラウンジ',''),
('sefb719c7','あずま','ekimae','手寄','night','スナック・ラウンジ',''),
('sd09a9257','どんどん','ekimae','中央','night','スナック・ラウンジ',''),
('sc2625260','バレッタ','ekimae','中央','night','スナック・ラウンジ',''),
('s326db697','パリジェンヌ','ekimae','中央','night','スナック・ラウンジ',''),
('s38f5773f','ミュージックスペース シューハウス','ekimae','中央','night','スナック・ラウンジ',''),
('s0663cb88','日々','ekimae','中央','night','スナック・ラウンジ',''),
('s8c4f966a','笑殿','ekimae','中央','night','スナック・ラウンジ',''),
('sabb6da8c','紫苑','ekimae','中央','night','スナック・ラウンジ',''),
('s263b15fb','BAR 月下(バーげっか)','ekimae','中央','night','バー','gekka_fukui'),
('s3b14b9c6','Bistro&Bar Bono(ボーノ)','ekimae','中央','night','バー','foop.entertainment.service'),
('sd259ece0','バーこうみんかん','ekimae','中央','night','バー','kominkan2.0'),
('s6b4b3c83','SHIMA(シマ)','ekimae','中央','night','バー','shima_coffee_sake'),
('s8e6ca65b','アイリッシュバー Shelbourne(シェルボーン)','ekimae','中央','night','バー','shelbourne.ib'),
('s3322a85d','ダーツ&キッチン BAD BIRDY(バッド バーディ)','ekimae','大手','night','バー','bad_birdy_fukui'),
('s4c8c15d7','ミワンソン','ekimae','中央','night','バー','miwanseong.cafe'),
('sba771388','浜町安文酒店','ekimae','中央','night','バー',''),
('s9771811c','BEER BAR アワタチ','ekimae','中央','night','バー','beer_awatachi'),
('s65a8861d','Blue Light Cafe','ekimae','中央','night','バー',''),
('sd22f874a','オステリア ダ シルバーノ','ekimae','中央','night','バー','osteriadasilvano'),
('sc9e51efe','たこ焼きバー たこパ','ekimae','中央','night','バー','takopa_fukui'),
('sff5f6e32','卸直営 生ホルモン 炭と肉。','ekimae','中央','night','焼肉・肉料理','sumitoniku'),
('s49d8ac83','旬ふく食彩 よしな','ekimae','大手','night','和食','yoshina_624'),
('s967f220e','くずし割烹 ぼんた 個室お二階','ekimae','中央','night','和食',''),
('s0be49bbd','釣り人 しまちゃん','ekimae','中央','night','寿司・海鮮','tsuribito_shimachan'),
('s4c9fd68e','味処 おたん','ekimae','中央','night','和食',''),
('s08e04a3a','CAFE &amp; BAR PRONTO 福井駅前店','ekimae','中央','night','バー','pronto___official'),
('s0d5a9f96','Bar UNCLE(アンクル)','ekimae','大手','night','バー',''),
('se36ce584','GINCHIYO','ekimae','中央','night','バー','ginchiyo_fukui'),
('s69548fc0','OUR BREWING TAPROOM','ekimae','中央','night','バー','ourbrewing'),
('s1c709fa5','eclat(エクラ)','ekimae','大手','night','バー','eclat__2023'),
('s58b36dea','the best space bar FUKU(フク)','ekimae','中央','night','バー','t.b.s.barfuku'),
('s8962fe8f','なごとん','ekimae','中央','night','バー',''),
('s5756d30a','ふくい屋台村','ekimae','日之出','night','バー','fukui_yataimura'),
('s1b2f1de2','パブおいち・深夜食堂','ekimae','中央','night','スナック・ラウンジ','nishikou'),
('sedf01bb3','歌謡喫茶 ユミ','ekimae','中央','night','バー','kayoukissa_yumi'),
('s7d261690','肉はナカノ MINIE店','ekimae','中央','night','焼肉・肉料理','nikuhanakano'),
('s5f15823c','兄ん家','ekimae','大手','night','バー','kaisen343'),
('s4d946582','八兆屋駅の蔵 福井駅店','ekimae','中央','night','バー',''),
('sc4b4e40b','目からうろこ 福井駅前本店','ekimae','中央','night','バー',''),
('sad14b649','越前魚問屋 蟹ヱ門','ekimae','中央','night','バー','kaniemon_minie'),
('s3b4d8d43','炭火焼鳥 鶏次 福井駅前店','ekimae','中央','night','バー','sumibiyakitori_keiji'),
('s777fcfb5','福井駅前フードホール MINIE(ミニエ福井)','ekimae','中央','night','バー',''),
('s28c02e51','SIERRA MADRE','ekimae','','night','バー',''),
('s88f82896','WINE食堂 TAMAMIN13','ekimae','大手','night','バー','tamamisongjing'),
('s45f72746','ちょい吞み処 ババズ','ekimae','中央','night','バー','ba__buzz'),
('s69411869','エノバル','ekimae','中央','night','バー','enobar_fukui'),
('s92f96719','Bar & Restaurant Blue Light Cafe','ekimae','','night','バー',''),
('s5db5ddca','Bar 堀川','ekimae','中央','night','バー',''),
('s44b0f375','CINEMA "street theater"','ekimae','','night','バー',''),
('s8a70a856','Craft Beer Bar アワタチ','ekimae','','night','バー',''),
('sae19d524','DISCOTHEQUE SALOON Rum Fire DJ Event & Club Music','ekimae','','night','スナック・ラウンジ',''),
('s3e5f6e5c','HIDINGPLACE','ekimae','中央','night','バー',''),
('s51ed9d01','IRISH WHISKEY PUB shelbourne','ekimae','','night','バー',''),
('s645ff303','ODDS POKER ROOM','ekimae','','night','バー',''),
('s7231e638','SHIMA & coffee & sake','ekimae','','night','バー',''),
('s15f90bb9','Sincerely Bar UNCLE(アンクル)','ekimae','','night','バー',''),
('s58fa00bc','THE BAR 灯火 TOMOSHIBI','ekimae','大手','night','バー','bar_tomoshibi_fukui'),
('s87dcb8a5','おさけとワイン みずもと くるふ福井駅店','ekimae','中央','night','バー','mizumoto_sake'),
('sa93c800a','アミューズメントバー・トランプ 福井駅前 貸切 二次会','ekimae','大手','night','バー','trump_golfanddarts_bar'),
('sa8dd9927','コートヤード・バイ・マリオット福井 THE LOUNGE &amp; BAR','ekimae','中央','night','スナック・ラウンジ','courtyard_by_marriott_fukui'),
('s59aa7397','ワインバル ヴェレゾン','ekimae','大手','night','バー',''),
('s2f0aadc1','屋上BAR BRIDGE','ekimae','','night','バー',''),
('sa0a076b6','日本酒BAR Room','ekimae','','night','バー',''),
('sbebd0195','味の王様 本店','ekimae','大手','night','居酒屋','aji_ou'),
('s4fecae1c','味処 庄屋','ekimae','中央','night','居酒屋',''),
('s7d39ff3b','味劇場 松田屋','ekimae','日之出','night','居酒屋',''),
('s690446b2','居酒屋 味とら','ekimae','大手','night','居酒屋',''),
('s4357786e','やきとりの名門 秋吉 福井駅前店','ekimae','大手','night','焼鳥・串',''),
('sc37eaa46','味の清八','ekimae','中央','night','焼鳥・串',''),
('s3005c9ff','焼肉ほるもんサンマルコ','katamachi','順化','gourmet','焼肉・肉料理',''),
('sbd3dd6a4','金福','katamachi','順化','gourmet','その他',''),
('s43b636a5','ぼてじゃこ福井片町店','katamachi','順化','gourmet','その他',''),
('s2ee77113','よしな片町店','katamachi','順化','gourmet','その他',''),
('se75193a0','富士美','katamachi','順化','gourmet','その他',''),
('se99600ad','山中','katamachi','順化','gourmet','その他',''),
('s44c3d4e3','国嶋清平商店','katamachi','','gourmet','その他',''),
('scd0d2bee','天たつ 福井片町本店','katamachi','','gourmet','その他',''),
('s1c0a991b','新鮮食品市場 まえがわ','katamachi','順化','gourmet','その他','maegawa.yaoya'),
('s370e73a0','昆布・海産物 小田こんぶ','katamachi','','gourmet','その他',''),
('sd924393f','越前かに 成前','katamachi','順化','gourmet','寿司・海鮮',''),
('s18e7a90b','&Room','katamachi','順化','gourmet','その他',''),
('sa4f29e79','BANBAN','katamachi','順化','gourmet','その他',''),
('s317ffbcb','CLUB・Queen’s','katamachi','順化','night','スナック・ラウンジ',''),
('saa9ac2b9','CREAM','katamachi','順化','gourmet','その他',''),
('s91eefd77','ELAN','katamachi','順化','gourmet','その他',''),
('sc90cd7da','JagBAR','katamachi','順化','gourmet','その他',''),
('s65c28a30','JuGo','katamachi','順化','gourmet','その他',''),
('s867c97ed','LeapDay','katamachi','順化','gourmet','その他',''),
('s9e448f01','NewYork・ニューヨーク','katamachi','順化','gourmet','その他',''),
('s325178f0','RoseRed','katamachi','順化','gourmet','その他',''),
('sb7f6f7c1','Startin’','katamachi','順化','gourmet','その他',''),
('s59952785','TOYSBOX','katamachi','順化','gourmet','その他',''),
('s13061b4a','Yダッシュ','katamachi','順化','gourmet','その他',''),
('s14a917ce','abuku','katamachi','順化','gourmet','その他',''),
('s69a04e29','きぶね','katamachi','順化','gourmet','その他',''),
('s3a58059c','さなえ','katamachi','順化','gourmet','その他',''),
('sc84a2afd','その字 弐','katamachi','順化','gourmet','その他',''),
('s8c934cc7','そば茶屋まつき','katamachi','順化','gourmet','そば・うどん',''),
('se63cf918','とび田','katamachi','順化','gourmet','その他',''),
('s8486f4ff','どん茶屋御食事処','katamachi','順化','gourmet','その他',''),
('sbce0670a','みやぎ(宮妓)','katamachi','順化','gourmet','その他',''),
('s428d8297','アフロディーテ','katamachi','順化','gourmet','その他',''),
('sb6c24e6d','アミーチ','katamachi','順化','gourmet','その他',''),
('s8b37d3b4','アリーズバー','katamachi','順化','night','バー',''),
('s129ac94d','オー・ド・ヴィー','katamachi','順化','gourmet','その他',''),
('sd1150155','キュキュキュ','katamachi','順化','gourmet','その他',''),
('s331e2db6','キンヤ人情下町店','katamachi','順化','gourmet','その他',''),
('sc788de6c','クレム(creme)','katamachi','順化','gourmet','その他',''),
('sff34115f','ケイズバー(K’zBar)','katamachi','順化','night','バー',''),
('se2538d93','ゴードン','katamachi','順化','gourmet','その他',''),
('s19a22213','サンクチュアリ','katamachi','順化','gourmet','その他',''),
('sa6c7bb1a','ザ・バーイースト','katamachi','順化','night','バー',''),
('sbc794b10','シーズン','katamachi','順化','gourmet','その他',''),
('sa617f4a1','ジェイ‐グローブ(J-globe)','katamachi','順化','gourmet','その他',''),
('sa0653b5f','ジェイ・グローブ','katamachi','順化','gourmet','その他',''),
('s048f70e3','スピークイージー','katamachi','順化','gourmet','その他',''),
('s849179f9','スペイン酒場エル・スール','katamachi','順化','gourmet','居酒屋',''),
('sa22c4fea','セナラ ジュテイ','katamachi','順化','gourmet','その他',''),
('s7046b5ce','セント・ジェームズ','katamachi','順化','gourmet','その他',''),
('sd3549282','ゼット','katamachi','順化','gourmet','その他',''),
('sd5d4d796','ダフタウン','katamachi','順化','gourmet','その他',''),
('sc753a6df','ナイトイン季節風','katamachi','順化','gourmet','その他',''),
('s18c1203f','ナフナフ','katamachi','順化','gourmet','その他',''),
('s942993d8','ニュー淀','katamachi','順化','gourmet','その他',''),
('s73a7aa97','バッカス(BACCHUS)','katamachi','順化','gourmet','その他',''),
('s529f286d','パインズ・バー','katamachi','順化','night','バー',''),
('s537a8bd8','パラダイス','katamachi','順化','gourmet','その他',''),
('s78ce1532','プラチナム(PLATINUM)','katamachi','順化','gourmet','その他',''),
('sbc48c481','プロペラ','katamachi','順化','gourmet','その他',''),
('s51a24057','ボギーズバー','katamachi','順化','night','バー',''),
('s1cb86e25','マリブ(MALIBU)','katamachi','順化','gourmet','その他',''),
('sb838dce9','マルシェ','katamachi','順化','gourmet','その他',''),
('sa15735b1','ミムロ','katamachi','順化','gourmet','その他',''),
('s3d8d843f','メリージェーン','katamachi','順化','gourmet','その他',''),
('s1e5d0e7c','ラジオ','katamachi','順化','gourmet','その他',''),
('s7783a4ce','レオン','katamachi','順化','gourmet','その他',''),
('s336d8d89','レディースマーケット','katamachi','順化','gourmet','その他',''),
('sb5a824d4','ロータス','katamachi','順化','gourmet','その他',''),
('s88f1a01b','ヴァンテレーヌ','katamachi','順化','gourmet','その他',''),
('saef08cb2','上野屋','katamachi','順化','gourmet','その他',''),
('s093086ca','凛','katamachi','順化','gourmet','その他',''),
('s5cea63aa','十六夜','katamachi','順化','gourmet','その他',''),
('s75f6146a','始皇帝','katamachi','順化','gourmet','その他',''),
('s86a343d3','山根木','katamachi','順化','gourmet','その他',''),
('s1c0f2384','職人二人','katamachi','順化','gourmet','その他',''),
('sa118b8fa','花音','katamachi','順化','gourmet','その他',''),
('s0918ef91','香華堂','katamachi','順化','gourmet','その他',''),
('s3e2719c8','高島広幸','katamachi','順化','gourmet','その他',''),
('s8c75506c','ルアンタイ','katamachi','順化','gourmet','アジア・各国料理',''),
('s60b5526c','宗家','katamachi','順化','gourmet','アジア・各国料理',''),
('s3ae3fb1c','白頭山','katamachi','順化','gourmet','アジア・各国料理',''),
('s359b50a6','豚屋','katamachi','順化','gourmet','アジア・各国料理',''),
('sea1c91f9','韓国食堂mukuge','katamachi','順化','gourmet','アジア・各国料理',''),
('s91d1b18b','Arancia','katamachi','順化','gourmet','イタリアン・フレンチ','arancia_2008'),
('s2da5446a','なかだ','katamachi','順化','gourmet','イタリアン・フレンチ',''),
('sf0cd82ef','ミルヒビカフェ','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s83e700a2','深夜あいす26','katamachi','順化','gourmet','カフェ・スイーツ','26ice.fukui'),
('sb037cd70','YUKI LEIN','katamachi','順化','gourmet','カフェ・スイーツ',''),
('sd2caeac3','cafe&セレクトショップ キルトハウス','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s45b60eaa','アスワン','katamachi','順化','gourmet','カフェ・スイーツ',''),
('se3ea25db','ウィーン','katamachi','順化','gourmet','カフェ・スイーツ',''),
('saeef5c36','カフェ 点','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s773dd354','コーヒーハウスコナン','katamachi','順化','gourmet','カフェ・スイーツ',''),
('sb41499ea','パリス','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s067aec81','千恵','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s83175030','喫茶 カファ・ブンナ','katamachi','順化','gourmet','カフェ・スイーツ',''),
('sd65b6156','巴奈麻','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s2554e909','珈琲所','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s8909b195','道安','katamachi','順化','gourmet','カフェ・スイーツ',''),
('sb354a49f','カフェ アンパサンド','katamachi','順化','gourmet','カフェ・スイーツ','ampersand_tommy'),
('s67c4ccb7','カフェと雑貨と、ときどき猫 古民家35(ミーコ)','katamachi','順化','gourmet','カフェ・スイーツ','kominka35'),
('sd4136377','パティスリー オリヴィエール','katamachi','順化','gourmet','カフェ・スイーツ','oliviere_'),
('sc71669f9','寄合カフェ 京町Y・Y','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s621d80d0','喫茶 SEVEN’s(セブンズ)','katamachi','順化','gourmet','カフェ・スイーツ','sevens359'),
('s5c45398c','カラオケ ビッグエコー 片町店','katamachi','順化','gourmet','その他',''),
('sdb3613c2','とんかつ割烹 一えい','katamachi','順化','gourmet','焼肉・肉料理',''),
('sbbbe1e11','とんかつ割烹 谷口や','katamachi','順化','gourmet','焼肉・肉料理',''),
('s7349674b','おはぎや 小林','katamachi','順化','gourmet','カフェ・スイーツ','ohagiyakoba'),
('scf6e4f22','ティラミス専門店 トラットリア トマト','katamachi','順化','gourmet','イタリアン・フレンチ','trattoria.tomato'),
('s3c52bf29','Spuntino (スプンティーノ)','katamachi','順化','gourmet','洋食','spuntino_italiano'),
('sd178765f','つるきそば 佐佳枝支店','katamachi','順化','gourmet','そば・うどん',''),
('scb957c62','佐佳枝亭 本店','katamachi','順化','gourmet','そば・うどん',''),
('sf213de58','手打ひと筋 さのや','katamachi','順化','gourmet','そば・うどん',''),
('s1bb93f7c','越前蕎麦dining 櫻庭(さくらば)','katamachi','順化','gourmet','そば・うどん','echizensoba.dining_sakuraba'),
('s95a2236e','天籠(てんかご)','katamachi','順化','gourmet','そば・うどん','tenkago.myo'),
('s3d5f6c4e','Mooma(モーマ)','katamachi','順化','gourmet','そば・うどん','mooma5745'),
('s46f9af51','夕炊屋 fudo(ゆうげや ふど)','katamachi','順化','gourmet','イタリアン・フレンチ','10nin10color'),
('sb77fbccd','GYOZA kitchen 信正(しんせい)','katamachi','順化','gourmet','ラーメン',''),
('s1133ed50','炭火焼き 赤身・じびえ・ほるもん どがいし','katamachi','順化','gourmet','洋食','dogaisi_291'),
('s8f165711','TSUGI(ツギ)','katamachi','順化','gourmet','洋食','tsugi_19h'),
('sb1e3455d','おばんざい家 たかはし','katamachi','順化','gourmet','洋食','obannzai.takahashi'),
('s4a5a5bd6','かき乃木','katamachi','順化','gourmet','洋食','kakinoki_fukui'),
('s1c2c0c33','陶酔 灯り','katamachi','順化','gourmet','洋食','tousui_akari'),
('s3e300401','めしや しの﨑','katamachi','順化','gourmet','居酒屋','meshiya.shinozaki'),
('s153fe11b','料理屋 みや﨑','katamachi','順化','gourmet','居酒屋',''),
('sfd765333','歳時鹿火(さいじろくか)','katamachi','順化','gourmet','洋食','saiji_rokuka_official'),
('sb3c17def','はちまん','katamachi','順化','gourmet','居酒屋','hach.imann'),
('s498b4096','四季ごはん おやびんHOUSE','katamachi','順化','gourmet','居酒屋',''),
('s3d95a6ec','晩酌 ちろり','katamachi','順化','gourmet','居酒屋',''),
('sa4c1eaa7','酒彩 雁ぐらし(かりぐらし)','katamachi','順化','gourmet','居酒屋','karigurasi.fukui'),
('sa9bfddef','鉄板焼肉酒場 まねき屋','katamachi','順化','gourmet','焼肉・肉料理','manekiya320'),
('scfd15dd6','鮮 -sen-(せん)','katamachi','順化','gourmet','居酒屋','sen_hituji0411'),
('sf098584a','鶏料理居酒屋 トリノトリコ','katamachi','順化','gourmet','居酒屋','tori_no_torico_fukui'),
('s578a39f9','GYUGYU焼肉 七福(しちふく)','katamachi','順化','gourmet','焼肉・肉料理','yakiniku_shichifuku'),
('s7468491e','OHAKO (オハコ)','katamachi','順化','gourmet','焼肉・肉料理','ohako_fukui'),
('s73376292','あぶり牧場 あん','katamachi','順化','gourmet','焼肉・肉料理',''),
('sc1995f5c','株式会社ワンダーフードサービス','katamachi','順化','gourmet','焼肉・肉料理','akamiwadamaru'),
('s6cdaa3b7','焼き肉家 山本','katamachi','順化','gourmet','焼肉・肉料理',''),
('scc8615a6','焼肉 うしのね','katamachi','順化','gourmet','焼肉・肉料理','yakiniku__usinone'),
('s8a365757','牛匠・人時(ぎゅうしょう・ひととき)','katamachi','順化','gourmet','焼肉・肉料理','gyuushou.hitotoki'),
('sc1b4dfb9','Yellow(イエロー)','katamachi','順化','gourmet','焼肉・肉料理','yellow_spice_labo'),
('sa9f5da48','遊留里楽酒場 みとん(ゆるりらさかば みとん)','katamachi','順化','gourmet','焼鳥・串','miton0521'),
('s6b32962a','暖らん酒場 八や(はちや)','katamachi','順化','gourmet','居酒屋','hachiya.fukui'),
('sd99cb14d','華汀園','katamachi','順化','gourmet','中華',''),
('s8171aa1f','喜寿','katamachi','順化','gourmet','その他',''),
('sb71081ad','迦毘羅','katamachi','','gourmet','アジア・各国料理',''),
('s0d1b893c','いちろくらーめん 片町本通り店','katamachi','','gourmet','ラーメン',''),
('s347a6c5e','がんこ2代目ラーメン','katamachi','','gourmet','ラーメン',''),
('s1b9f88a4','上海亭','katamachi','順化','gourmet','ラーメン',''),
('s4d70ce7f','多弐家','katamachi','順化','gourmet','ラーメン',''),
('s0f29951c','拉麺家 とんとん','katamachi','','gourmet','ラーメン',''),
('sc3eb5591','長宝亭','katamachi','順化','gourmet','ラーメン',''),
('sbbbb0be0','きのこしゃぶしゃぶ料理 栄福祥(えいふくしょう)','katamachi','順化','gourmet','中華',''),
('s88292dbb','ギョウザ・ラーメン 彩菜','katamachi','','gourmet','ラーメン',''),
('s19c2fd09','中国本場料理 福井源','katamachi','','gourmet','中華',''),
('sd4f767c6','タコスのある人生~la vida tacos~','katamachi','順化','gourmet','アジア・各国料理','la_vida_tacos'),
('sc835ecd0','五味五色 じゅじゅむむ','katamachi','','gourmet','アジア・各国料理',''),
('s7dc899ed','地中海バル OTTO','katamachi','','gourmet','居酒屋',''),
('s9b61fc71','韓国料理 ペゴパ','katamachi','順化','gourmet','アジア・各国料理','pegopa1115'),
('s53e3133b','韓国風鉄板焼・鍋工房 鉄鍋屋','katamachi','','gourmet','アジア・各国料理',''),
('sd762e015','にく家 うましか','katamachi','順化','gourmet','焼肉・肉料理','nikuya.umashika'),
('s2200ab8a','炭火焼肉 春来','katamachi','','gourmet','焼肉・肉料理',''),
('s767895f8','焼き肉 豊 -YUTAKA-','katamachi','','gourmet','焼肉・肉料理',''),
('sf1090fcd','焼肉 うし牛','katamachi','','gourmet','焼肉・肉料理',''),
('s84d8bb73','焼肉 かわだ','katamachi','順化','gourmet','焼肉・肉料理','yakiniku_kawada'),
('s9e7b72ab','福昌園','katamachi','順化','gourmet','焼肉・肉料理',''),
('sc8f7b05d','若狭牛と個室焼肉 和田○商店','katamachi','','gourmet','焼肉・肉料理',''),
('saad46e0a','あげます','katamachi','順化','gourmet','和食',''),
('sae2000ca','あらかわ','katamachi','順化','gourmet','和食',''),
('s48972b45','いっすんぼうし','katamachi','順化','gourmet','和食',''),
('s8dc35a91','おきな','katamachi','順化','gourmet','和食',''),
('saeacb1d2','お柳','katamachi','順化','gourmet','和食',''),
('s66fca2f8','かっちゃん','katamachi','順化','gourmet','和食',''),
('s554ec16c','じん','katamachi','順化','gourmet','和食',''),
('saa7a0452','すし善','katamachi','順化','gourmet','寿司・海鮮',''),
('s456938cd','だるま鮨','katamachi','順化','gourmet','寿司・海鮮',''),
('s5eff3ef1','ちか','katamachi','順化','gourmet','和食',''),
('s669c8e05','でん助','katamachi','順化','gourmet','和食',''),
('s75e833a5','ときわ','katamachi','順化','gourmet','和食',''),
('s0f000893','とり新','katamachi','順化','gourmet','和食',''),
('sc17c8de0','みよしの','katamachi','順化','gourmet','和食',''),
('sf2d60390','やました','katamachi','順化','gourmet','和食',''),
('s2b34ab87','ゆずりは','katamachi','順化','gourmet','和食',''),
('sd54c2e62','佳納','katamachi','順化','gourmet','和食',''),
('sb1475d1a','初味寿司呉服町店','katamachi','順化','gourmet','寿司・海鮮',''),
('s68b63729','吉田寿司本店','katamachi','順化','gourmet','寿司・海鮮',''),
('sd83b39aa','味とまごころ 八勢','katamachi','順化','gourmet','和食',''),
('s0509d1dd','咲咲','katamachi','順化','gourmet','和食',''),
('s3d24ec22','咲良・味工房','katamachi','順化','gourmet','和食',''),
('sf168fd4c','大仏そば','katamachi','順化','gourmet','そば・うどん',''),
('s8a743fa5','大番','katamachi','順化','gourmet','和食',''),
('sbde5e1bd','大西','katamachi','順化','gourmet','和食',''),
('sf3994741','天春','katamachi','順化','gourmet','和食',''),
('s431e6f4f','寿し保','katamachi','順化','gourmet','和食',''),
('scabe4132','寿ゞ屋','katamachi','順化','gourmet','和食',''),
('s17d70843','寿司道楽','katamachi','順化','gourmet','寿司・海鮮',''),
('s24f4e4d6','文ちん','katamachi','順化','gourmet','和食',''),
('sb8320adf','文室','katamachi','順化','gourmet','和食',''),
('saae6d4a1','桜寿し本店','katamachi','順化','gourmet','和食',''),
('sa73bcf7b','楽','katamachi','順化','gourmet','和食',''),
('sd62d598c','波の華','katamachi','順化','gourmet','和食',''),
('s14f3cb65','源太','katamachi','順化','gourmet','和食',''),
('sd27993d8','焼鳥大将片町店','katamachi','順化','gourmet','焼鳥・串',''),
('s55b731a1','片桐','katamachi','順化','gourmet','和食',''),
('s776b5062','田畑清正','katamachi','順化','gourmet','和食',''),
('s4ff26fa9','番晩亭','katamachi','順化','gourmet','和食',''),
('sacfc6c86','磯季節料理店','katamachi','順化','gourmet','和食',''),
('s9b859a1a','粂ちゃん','katamachi','順化','gourmet','和食',''),
('s3ab92ad1','紫川','katamachi','順化','gourmet','和食',''),
('sd10debe6','細庵','katamachi','順化','gourmet','和食',''),
('sf2924ed3','茶がま','katamachi','順化','gourmet','和食',''),
('s36895a99','茶太片町分店','katamachi','順化','gourmet','和食',''),
('s0160358d','葉月','katamachi','順化','gourmet','和食',''),
('s7b889572','金龍','katamachi','順化','gourmet','和食',''),
('s76f1c89a','釜めし 煮込うどん 王将','katamachi','順化','gourmet','そば・うどん',''),
('s80b7c383','そば居酒屋 ポポー軒','katamachi','','gourmet','そば・うどん',''),
('se0f1621a','そば重','katamachi','順化','gourmet','そば・うどん',''),
('s089fd1e4','越前そば 佐佳枝亭','katamachi','','gourmet','そば・うどん',''),
('s8206b04b','越前そば 片桐','katamachi','','gourmet','そば・うどん',''),
('s3ad2c6e9','越前そば 見吉屋','katamachi','順化','gourmet','そば・うどん',''),
('sbb5f9a98','お好み焼き 富士美','katamachi','','gourmet','和食',''),
('s67fcef83','く・く・る','katamachi','順化','gourmet','和食',''),
('s07be2f9b','とんかつ かっぽう 一えい','katamachi','','gourmet','焼肉・肉料理',''),
('s731766a5','ヨーロッパ軒 総本店','katamachi','順化','gourmet','焼肉・肉料理',''),
('s2b13b5b2','郷土料理・とんかつ 谷口や','katamachi','','gourmet','焼肉・肉料理',''),
('s891aae82','しゃぶ玄','katamachi','順化','gourmet','和食',''),
('s369ebef9','おばんざいのお店 TSUGI','katamachi','','gourmet','和食',''),
('saa142b8f','ご馳走 純','katamachi','順化','gourmet','和食',''),
('se78dfc59','ひより','katamachi','','gourmet','和食',''),
('saf81b217','まちの都 machi no miyaco','katamachi','','gourmet','和食',''),
('s2a0e1d0d','割烹 木屋町 Kiyamachi','katamachi','','gourmet','和食',''),
('see72ce6b','創作小鉢 あけると','katamachi','順化','gourmet','和食','_akeruto'),
('se7e8701a','味処 源太','katamachi','','gourmet','和食',''),
('s6ab86a87','和食ダイニング 柳月亭','katamachi','','gourmet','和食',''),
('se3123166','和食処 山海','katamachi','','gourmet','和食',''),
('s0c180bb7','御料理 味真乃','katamachi','順化','gourmet','和食',''),
('sdf3b56fc','旨い魚・うまい肴 まるさん屋 福井片町','katamachi','','gourmet','寿司・海鮮',''),
('s1c3a2dda','旬彩家 樹','katamachi','','gourmet','和食',''),
('s103d9e54','鍋料理・寿司・天ぷら はちまん','katamachi','','gourmet','寿司・海鮮',''),
('se64ea2e8','鮮','katamachi','','gourmet','和食',''),
('s4fd6a14c','天ぷら 天春','katamachi','','gourmet','和食',''),
('s868ded4e','天菊','katamachi','順化','gourmet','和食',''),
('s9831a6a8','すし吉正','katamachi','順化','gourmet','寿司・海鮮','sushi_yoshimasa'),
('s440cffda','寿し 吉田','katamachi','順化','gourmet','寿司・海鮮','sushi_yoshida'),
('sd8cdc1da','寿司・割烹・ふぐ料理 鮨長','katamachi','','gourmet','寿司・海鮮',''),
('s4adbb5f9','鮨 凌','katamachi','','gourmet','寿司・海鮮',''),
('s7e8db528','鮨 吉幸','katamachi','','gourmet','寿司・海鮮',''),
('s4892d4ca','鮨光','katamachi','','gourmet','寿司・海鮮',''),
('scf5bcaa9','鮨処 海月(クラゲ)','katamachi','順化','gourmet','寿司・海鮮','kurage.666'),
('s186422a9','のちのち','katamachi','','gourmet','和食',''),
('s6b951e4f','御料理 いわし屋','katamachi','','gourmet','和食',''),
('s70fb2431','日本料理 やなぎ町','katamachi','','gourmet','和食',''),
('sc511749c','燻鮎 KUNTEN','katamachi','','gourmet','和食',''),
('s6ec34d7b','六本弦 お昼の部 ちえみん家のお米でつくったおにぎり','katamachi','','gourmet','和食',''),
('s4fe7e7c6','田中マネの食堂','katamachi','順化','gourmet','和食',''),
('s0846f5eb','CREPE BON','katamachi','','gourmet','カフェ・スイーツ',''),
('sb426626f','Spice Bar QUILT HOUSE(キルトハウス) 〜欧風家庭料理〜','katamachi','','night','バー',''),
('s5d33d84b','THREE TIMES COFFEE (スリータイムズコーヒー)','katamachi','順化','gourmet','アジア・各国料理','threetimescoffee_fukui'),
('sb5ba39b4','flat kitchen','katamachi','','gourmet','カフェ・スイーツ',''),
('s5a37ab0b','カフェと雑貨 古民家35','katamachi','','gourmet','カフェ・スイーツ',''),
('s6e2e3802','京町Y・Yカフェ','katamachi','','gourmet','カフェ・スイーツ',''),
('sd900e179','CIGAR&CAFE 臼井煙草倶楽部','katamachi','','gourmet','カフェ・スイーツ',''),
('sf546ea8a','異邦人倶楽部','katamachi','','gourmet','カフェ・スイーツ',''),
('sbe6b898a','yokoyama別亭','katamachi','順化','gourmet','居酒屋',''),
('s307bfba9','炭火串焼千串屋','katamachi','順化','gourmet','焼鳥・串',''),
('s367eb072','あげはら','katamachi','順化','gourmet','居酒屋',''),
('s9663f919','あんぶん春','katamachi','順化','gourmet','居酒屋',''),
('s069fd0ed','うまいもの屋敷 忍者','katamachi','順化','gourmet','居酒屋',''),
('sead7d63c','かっぱ','katamachi','順化','gourmet','居酒屋',''),
('s3a654b14','かんちゃん','katamachi','順化','gourmet','居酒屋',''),
('s639da5a4','ききょう','katamachi','順化','gourmet','居酒屋',''),
('scff2bc52','しまだ','katamachi','順化','gourmet','居酒屋',''),
('s7f29a26a','てらや','katamachi','順化','gourmet','居酒屋',''),
('s73927a00','とも貴','katamachi','順化','gourmet','居酒屋',''),
('s4d5c82b7','のむ喜','katamachi','順化','gourmet','居酒屋',''),
('s2e041204','はせじ','katamachi','順化','gourmet','居酒屋',''),
('s0880190e','ひいきや','katamachi','順化','gourmet','居酒屋',''),
('s551ea6ef','ひろちゃん','katamachi','順化','gourmet','居酒屋',''),
('se937e33f','まき','katamachi','順化','gourmet','居酒屋',''),
('s5ba59f5d','まんぼう','katamachi','順化','gourmet','居酒屋',''),
('s67514f4c','やきとり 八や','katamachi','順化','gourmet','焼鳥・串',''),
('s13adad43','やき屋','katamachi','順化','gourmet','居酒屋',''),
('s6b9c1233','よしむら 割烹 鍋物','katamachi','順化','gourmet','居酒屋',''),
('s74ee4314','シェ・シーマ(CHEZCIMA)','katamachi','順化','gourmet','居酒屋',''),
('s6a580b5b','ソウル','katamachi','順化','gourmet','居酒屋',''),
('scc2be637','プーケット','katamachi','順化','gourmet','居酒屋',''),
('s5d767b0d','ムッ酒','katamachi','順化','gourmet','居酒屋',''),
('sfde442cb','丸駒','katamachi','順化','gourmet','居酒屋',''),
('sf41e4a08','八州屋','katamachi','順化','gourmet','居酒屋',''),
('s748ae3f8','友膳','katamachi','順化','gourmet','居酒屋',''),
('s39d888e4','吟遊','katamachi','順化','gourmet','居酒屋',''),
('s2cb6061a','呑むきんちゃん','katamachi','順化','gourmet','居酒屋',''),
('sc9ebaa56','和ぼうず','katamachi','順化','gourmet','居酒屋',''),
('sc4b4c29c','寿し割烹 八重 【個室完備・最大40名様迄】','katamachi','順化','gourmet','居酒屋',''),
('sb18e43e4','居酒屋いちべえ','katamachi','順化','gourmet','居酒屋',''),
('s74e6c803','居酒屋とっさん','katamachi','順化','gourmet','居酒屋',''),
('s2dc17270','居酒屋花や','katamachi','順化','gourmet','居酒屋',''),
('sb0239e11','市','katamachi','順化','gourmet','居酒屋',''),
('sd0bcb41c','平八','katamachi','順化','gourmet','居酒屋',''),
('sfed117ef','春月','katamachi','順化','gourmet','居酒屋',''),
('sb2666067','本伊勢','katamachi','順化','gourmet','居酒屋',''),
('s689532b4','来神','katamachi','順化','gourmet','居酒屋',''),
('s940f2085','武','katamachi','順化','gourmet','居酒屋',''),
('s93d5500a','民俗村','katamachi','順化','gourmet','居酒屋',''),
('s1cb2f135','汐彩','katamachi','順化','gourmet','居酒屋',''),
('s33a2d7c3','洋食居酒屋クオーレ','katamachi','順化','gourmet','居酒屋',''),
('s57c29797','炎のダイニングじゅじゅむむ','katamachi','順化','gourmet','居酒屋',''),
('s96659a24','直','katamachi','順化','gourmet','居酒屋',''),
('sf451c6fc','福義','katamachi','順化','gourmet','居酒屋',''),
('s30aec0c7','福菜福酒 師門','katamachi','順化','gourmet','居酒屋',''),
('sd6b4db8b','竹生','katamachi','順化','gourmet','居酒屋',''),
('sac848a19','美ちゃん','katamachi','順化','gourmet','居酒屋',''),
('s4f6e9220','翠翔 片町店','katamachi','順化','gourmet','居酒屋',''),
('se8215640','菜彩亭','katamachi','順化','gourmet','居酒屋',''),
('s3295a40a','菜遊季','katamachi','順化','gourmet','居酒屋',''),
('s5c9d5897','薫鮎','katamachi','順化','gourmet','居酒屋',''),
('s34a51090','越の国つた屋','katamachi','順化','gourmet','居酒屋',''),
('s0cead092','錦','katamachi','順化','gourmet','居酒屋',''),
('s0c35cc80','食・酒野尻','katamachi','順化','gourmet','居酒屋',''),
('s600531b2','魚義','katamachi','順化','gourmet','寿司・海鮮',''),
('s9d3b898b','鮨長','katamachi','順化','gourmet','寿司・海鮮',''),
('s74326fb5','ペントラ・ベーネ(Pentola・Bene)','katamachi','順化','gourmet','洋食',''),
('s10ab3b3c','レストランル・ラパン','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s2e3542de','北欧','katamachi','順化','gourmet','洋食',''),
('s41a13a27','和洋創菜 豆や','katamachi','順化','gourmet','洋食',''),
('sc6ceaad8','Spuntino(スプンティーノ) ITALIANO','katamachi','','gourmet','イタリアン・フレンチ',''),
('sc954c866','伊食堂 Arancia','katamachi','','gourmet','イタリアン・フレンチ',''),
('sb37cb8c1','HAMBURG STEAK 亜米利館','katamachi','','gourmet','焼肉・肉料理',''),
('s7a9529f9','肉バル オニク☆パラダイス 福井片町店','katamachi','順化','gourmet','焼肉・肉料理','nikupara29'),
('s84fa3b5f','ステーキ 鐵船','katamachi','','gourmet','焼肉・肉料理',''),
('s0a073f91','ステーキハウス キタジマ','katamachi','','gourmet','焼肉・肉料理',''),
('s37d9b108','ステーキハウスアオヤマ','katamachi','順化','gourmet','焼肉・肉料理',''),
('s0ce1d614','バンボッシュ・ド・ヤマ','katamachi','順化','gourmet','イタリアン・フレンチ',''),
('s07d1f1b5','ワインと旬の料理の店 ミスター・デ・ヴ','katamachi','順化','gourmet','イタリアン・フレンチ',''),
('s00d94a9a','欧風割烹 北欧','katamachi','','gourmet','イタリアン・フレンチ',''),
('s35cf0d3e','洋食堂 yousyokudou','katamachi','','gourmet','イタリアン・フレンチ',''),
('s0aab2608','VIP Amon','katamachi','','gourmet','洋食',''),
('s97a8ae3a','福井パレスホテル ビアガーデン','katamachi','順化','gourmet','洋食',''),
('se336a944','寿司政','katamachi','順化','gourmet','寿司・海鮮','sushimasa_fukui'),
('s19b5bd45','しらさきホルモン','katamachi','順化','gourmet','焼肉・肉料理',''),
('s3b892d5d','ひばち','katamachi','順化','gourmet','焼肉・肉料理',''),
('sc0f46936','イガネ','katamachi','順化','gourmet','焼肉・肉料理',''),
('sd1e97e3c','焼肉星香園','katamachi','順化','gourmet','焼肉・肉料理',''),
('s3112b1c6','牛牛','katamachi','順化','gourmet','焼肉・肉料理',''),
('sa7e97ff0','ポポー軒','katamachi','順化','gourmet','そば・うどん',''),
('s92e2be62','手軽そば順化店','katamachi','順化','gourmet','そば・うどん',''),
('saac1d3c0','お料理 いわし屋','katamachi','順化','gourmet','寿司・海鮮',''),
('s6b5dd69d','割烹間海','katamachi','順化','gourmet','寿司・海鮮',''),
('s1e601a2f','和食個室ダイニング 柳月亭','katamachi','順化','gourmet','寿司・海鮮',''),
('sb3550b5a','日本料理 越前ガニ料理 やなぎ町','katamachi','順化','gourmet','寿司・海鮮','yanagimachi_honten'),
('s803c1518','親玉菓舗の碌寶焼','katamachi','順化','gourmet','その他','oyadama32028'),
('s6aaab873','錦梅堂','katamachi','順化','gourmet','その他',''),
('s8b13224f','えんの樹','katamachi','順化','gourmet','居酒屋',''),
('s6af60179','のんちゃん','katamachi','順化','gourmet','居酒屋',''),
('se722632c','ひっぱり凧','katamachi','順化','gourmet','居酒屋',''),
('scf6a8eeb','和食と地酒 本伊勢','katamachi','','gourmet','居酒屋',''),
('s84a6a919','和食ダイニング 柳庵 Ryu-an','katamachi','','gourmet','居酒屋',''),
('s9b01884b','想作居酒屋 一ふじ','katamachi','順化','gourmet','居酒屋',''),
('sc0bf71a9','越前の幸と喜びの酒 前田屋いちりん','katamachi','','gourmet','居酒屋',''),
('s1d75d313','越前中華 花ひなたに咲く','katamachi','順化','gourmet','居酒屋','hanahinatanisaku'),
('s7d77d677','酒肴 コブ','katamachi','','gourmet','居酒屋',''),
('sa1605bcf','食彩DINING 神無月 想い出','katamachi','','gourmet','居酒屋',''),
('s111f1093','食彩酒楽 いち陽','katamachi','順化','gourmet','居酒屋',''),
('s4e79fb62','やきとり ごとう','katamachi','','gourmet','焼鳥・串',''),
('s0219101b','串揚げ処 㐂寿','katamachi','','gourmet','焼鳥・串',''),
('s839868cb','宮崎地鶏と福彩の四季 㐂鶏屋','katamachi','','gourmet','焼鳥・串',''),
('sf43888ae','鳥匠 あさぎり','katamachi','順化','gourmet','焼鳥・串','asagirifukui'),
('sd4174d96','CLUB Risel','katamachi','順化','night','スナック・ラウンジ',''),
('s47fedf50','EAST','katamachi','順化','night','スナック・ラウンジ',''),
('s45a75088','club cherir','katamachi','順化','night','スナック・ラウンジ',''),
('se06c2d52','club 蓮','katamachi','順化','night','スナック・ラウンジ',''),
('s446a7e60','ひな乃','katamachi','順化','night','スナック・ラウンジ',''),
('sf8bc563c','スナックJm','katamachi','順化','night','スナック・ラウンジ','snack_jm_1124_'),
('sfb9bf709','スナックKARA','katamachi','順化','night','スナック・ラウンジ',''),
('sf560f241','スナックあれから','katamachi','順化','night','スナック・ラウンジ',''),
('s558ff87c','スナック・ロシア','katamachi','順化','night','スナック・ラウンジ',''),
('sbd388289','ナイトラウンジ恋華片町','katamachi','順化','night','スナック・ラウンジ',''),
('s323a99e4','ラウンジステラ','katamachi','順化','night','スナック・ラウンジ',''),
('sb255c48c','リッカー(Riccar)','katamachi','順化','night','スナック・ラウンジ',''),
('s8e8bde68','Anri','katamachi','順化','night','スナック・ラウンジ',''),
('sff7bb7f7','Bar妖かし','katamachi','順化','night','スナック・ラウンジ',''),
('s90e9520e','Belle vie~ベルヴィー~','katamachi','順化','night','スナック・ラウンジ','bellevie62288'),
('sf7255b5d','FRIEND BAR CURIOUS','katamachi','順化','night','スナック・ラウンジ',''),
('s06abb137','I LOVE DABAO','katamachi','順化','night','スナック・ラウンジ',''),
('sb100728b','I♡DABAO','katamachi','順化','night','スナック・ラウンジ',''),
('s97591a2d','JIGURO','katamachi','順化','night','スナック・ラウンジ',''),
('s8360d520','KARAOKE BAR NOAH','katamachi','順化','night','スナック・ラウンジ','noah_keirin'),
('s0f2c64c6','KOBAR','katamachi','順化','night','スナック・ラウンジ',''),
('s6f213bdc','LesoUrIre','katamachi','順化','night','スナック・ラウンジ',''),
('sfff10c76','Lounge Connection','katamachi','順化','night','スナック・ラウンジ',''),
('s10174fda','Luxe','katamachi','順化','night','スナック・ラウンジ',''),
('s44f5407f','More~モア~','katamachi','順化','night','スナック・ラウンジ',''),
('sbe58fd4d','NEGUS.','katamachi','順化','night','スナック・ラウンジ',''),
('s50cf4f21','OG-ChinaTown','katamachi','順化','night','スナック・ラウンジ',''),
('s74c77dce','SMILeeeS~スマイリーズ~','katamachi','順化','night','スナック・ラウンジ',''),
('s517a1da8','cafe&bar NABO','katamachi','順化','night','スナック・ラウンジ',''),
('sb85bc640','momo','katamachi','順化','night','スナック・ラウンジ',''),
('s3223ff06','musa','katamachi','順化','night','スナック・ラウンジ',''),
('s28f504d9','mystere','katamachi','順化','night','スナック・ラウンジ',''),
('s03ef00a4','vivian. (ビビアンドット)','katamachi','順化','night','スナック・ラウンジ',''),
('sb31dd628','はてな','katamachi','順化','night','スナック・ラウンジ',''),
('sf9344bdf','やすらぎ','katamachi','順化','night','スナック・ラウンジ',''),
('sbfb74d02','アプリコット','katamachi','順化','night','スナック・ラウンジ',''),
('s2cc7c925','カラオケスナック あざみ','katamachi','順化','night','スナック・ラウンジ',''),
('s237f50b1','カラオケバー LP','katamachi','順化','night','スナック・ラウンジ','karaoke_bar_lp'),
('s1eac43ce','コーヒー&カレー 迦毘羅(カビラ)','katamachi','順化','night','スナック・ラウンジ',''),
('sb7a58119','スナック さくら','katamachi','順化','night','スナック・ラウンジ',''),
('s23a91273','スナック せせらぎ','katamachi','順化','night','スナック・ラウンジ',''),
('s77c70ced','スナック なつこ','katamachi','順化','night','スナック・ラウンジ',''),
('saa4af146','スナック ぴーち','katamachi','順化','night','スナック・ラウンジ',''),
('sf5fcc1f6','スナック みやま','katamachi','順化','night','スナック・ラウンジ',''),
('sc491f560','スナック アーバン','katamachi','順化','night','スナック・ラウンジ',''),
('s95a14250','スナック ニューりんご','katamachi','順化','night','スナック・ラウンジ',''),
('sc03920e5','スナック ラクシャリィ','katamachi','順化','night','スナック・ラウンジ',''),
('sca529f69','スナック 五十八','katamachi','順化','night','スナック・ラウンジ',''),
('s3d6b9ac6','スナック 女帝','katamachi','順化','night','スナック・ラウンジ',''),
('s0d4c2b03','スナック 真利倫','katamachi','順化','night','スナック・ラウンジ',''),
('sdc8ff442','スナック 華','katamachi','順化','night','スナック・ラウンジ',''),
('s5ac214f1','ナイトイン アップルハウス','katamachi','順化','night','スナック・ラウンジ',''),
('sa0f6fc15','マリリン','katamachi','順化','night','スナック・ラウンジ',''),
('s94c8b70c','ラウンジ たちばな','katamachi','順化','night','スナック・ラウンジ',''),
('s5f5f7aae','ラブ','katamachi','順化','night','スナック・ラウンジ',''),
('s13b3be9b','大連','katamachi','順化','night','スナック・ラウンジ',''),
('s3aee8f03','燻(いぶし)','katamachi','順化','night','スナック・ラウンジ',''),
('sb89f1b9d','紗羅','katamachi','順化','night','スナック・ラウンジ',''),
('s89f5ddc6','旬菜美酒 サスケ','katamachi','順化','night','バー',''),
('s5c7d3d3e','Amusement+Bar DOOR','katamachi','順化','night','バー',''),
('s75b204ce','BAR 222','katamachi','順化','night','バー',''),
('s580b39a6','BAR GROWP.','katamachi','順化','night','バー',''),
('s3dcde339','BAR Rainbow st.','katamachi','順化','night','バー',''),
('sb85174dc','BAR SEA(バーシー)','katamachi','順化','night','バー',''),
('s7f821ec7','BAR Z','katamachi','順化','night','バー',''),
('se6fde3e7','BAR primo','katamachi','順化','night','バー',''),
('se5d55e8b','BAR ぐーちょきぱー','katamachi','順化','night','バー',''),
('sa9990c09','Bar 018','katamachi','順化','night','バー',''),
('sd05db204','Bar STELA','katamachi','順化','night','バー',''),
('s4d2b9604','EIGHT~Infinity Room~','katamachi','順化','night','バー',''),
('sf4df3742','LC','katamachi','順化','night','バー',''),
('s2116ea95','Lounge BIDEN','katamachi','順化','night','スナック・ラウンジ',''),
('s8368bd33','PAPILLON','katamachi','順化','night','バー',''),
('s4e39d3e7','Party`s Bar BeReTTa','katamachi','順化','night','バー',''),
('s2d4af826','dining cafe ヴィアーレ・ナフ','katamachi','順化','night','バー',''),
('sbc078b67','ばぁーくろぽん(笑)','katamachi','順化','night','バー',''),
('s53db608a','ゆる八','katamachi','順化','night','バー',''),
('sad7bee81','ホリチャン','katamachi','順化','night','バー',''),
('s0f74b085','メリエンダ・バール DESPERADO','katamachi','順化','night','バー',''),
('sdaebc4f2','suits AMUSEMENT BAR(スーツアミューズメントバー)福井店','katamachi','順化','night','バー','suits__bar'),
('s4899be09','ARTIST BAR B(アーティストバービー)','katamachi','順化','night','バー','artist.bar.b'),
('s8eb58b22','BAR 7六歩(バー・ナナロクフ)','katamachi','順化','night','バー',''),
('s94c3c3ec','JAZZ BAR SHIRAI HOUSE(シライハウス)','katamachi','順化','night','バー',''),
('scd7c8548','PICK UP BAR&CAFE (ピックアップバー&カフェ)','katamachi','順化','night','バー',''),
('sd3a695a4','SOMEN BAR 白線屋(ソーメンバーはくせんや)','katamachi','順化','night','バー','hakusenya'),
('sc18b7e53','マジックレストラン&バー 手品家福井店','katamachi','順化','night','バー','tejinaya.fukui'),
('s19d452cc','十人十色koya','katamachi','順化','night','バー','10nin10color_koya'),
('s48f03a3b','燻(いぶし)','katamachi','順化','night','バー','eves.fukui'),
('s32a38885','Beer Stand Pivo(ビールスタンド ピヴォ)','katamachi','順化','night','バー','pivo_beerstand'),
('se20b01ba','Bar Someday','katamachi','順化','night','バー',''),
('s8c3cc9d1','Vestito Bar','katamachi','順化','night','バー',''),
('saeb1e8e6','CLUB CHOCOLAT','katamachi','順化','night','スナック・ラウンジ',''),
('s479c1a94','CLUB Kai','katamachi','順化','night','スナック・ラウンジ',''),
('s16a3484e','CLUB NAGISA','katamachi','順化','night','スナック・ラウンジ',''),
('sd0993f8d','CLUB ROCHER','katamachi','順化','night','スナック・ラウンジ',''),
('s1f968c13','Club ゆず','katamachi','順化','night','スナック・ラウンジ',''),
('sfcf7b292','KOMACHI','katamachi','順化','night','スナック・ラウンジ',''),
('s74523afd','L and Heart','katamachi','順化','night','スナック・ラウンジ',''),
('sdf882d51','LA PAIX','katamachi','順化','night','スナック・ラウンジ',''),
('sb18877d9','LOUNGE 姫','katamachi','順化','night','スナック・ラウンジ',''),
('sfc318514','LUMINE','katamachi','順化','night','スナック・ラウンジ',''),
('s62364e3d','Lounge Crystal','katamachi','順化','night','スナック・ラウンジ',''),
('s25eafb21','Lounge K','katamachi','順化','night','スナック・ラウンジ',''),
('s2b61279f','Lounge LA Coo','katamachi','順化','night','スナック・ラウンジ',''),
('s50a7260e','Lounge ete','katamachi','順化','night','スナック・ラウンジ',''),
('s2f5ae9f8','Pretty May','katamachi','順化','night','スナック・ラウンジ',''),
('s045b5231','RETENTIR','katamachi','順化','night','スナック・ラウンジ',''),
('s382df82a','Richebourg','katamachi','順化','night','スナック・ラウンジ',''),
('s459aae16','SOHMA CLUB','katamachi','順化','night','スナック・ラウンジ',''),
('s63514fd4','Shampoo','katamachi','順化','night','スナック・ラウンジ',''),
('s367ecf02','club 奏鳴曲sonata','katamachi','順化','night','スナック・ラウンジ',''),
('s7c14a02c','lounge Salon','katamachi','順化','night','スナック・ラウンジ',''),
('sbeffbd40','おいない','katamachi','順化','night','スナック・ラウンジ',''),
('saeea5f27','ラウンジ 晴','katamachi','順化','night','スナック・ラウンジ',''),
('s933eb384','京','katamachi','順化','night','スナック・ラウンジ',''),
('s3ca85da3','呼詩','katamachi','順化','night','スナック・ラウンジ',''),
('sfb8404a0','小春日和','katamachi','順化','night','スナック・ラウンジ',''),
('sfc46a89d','彩 sayaka','katamachi','順化','night','スナック・ラウンジ',''),
('s8e85acec','心','katamachi','順化','night','スナック・ラウンジ',''),
('sbf085ba4','紗音','katamachi','順化','night','スナック・ラウンジ',''),
('s07f44bbf','藤','katamachi','順化','night','スナック・ラウンジ',''),
('sfcef8253','銀夏','katamachi','順化','night','スナック・ラウンジ',''),
('sb3173cc7','離宮','katamachi','順化','night','スナック・ラウンジ',''),
('s06f66f5c','ハンバーグステーキ 亜米利館(あめりかん)','katamachi','順化','night','バー','hamburg_american'),
('s3d6abb7e','Agit(アジト)','katamachi','順化','night','バー','agit19961220'),
('sfa3a63ab','KRAFT(クラフト)','katamachi','順化','night','バー','kraft_fukui'),
('s8237af5d','Woody','katamachi','順化','night','バー',''),
('sd16a99f6','snow drop','katamachi','順化','night','バー','snow.drop.mama'),
('s2bbf9c2a','ケネディ・クラブ','katamachi','順化','night','スナック・ラウンジ',''),
('s9d1d911a','パブ浪江','katamachi','順化','night','スナック・ラウンジ',''),
('s6d74241f','株式会社猿の盃','katamachi','順化','night','バー',''),
('s11b1b003','les quatre hommes(レ キャトロム)','katamachi','順化','night','イタリアン・フレンチ','nagaya_teruo'),
('s1effb8f7','やきとりの名門 秋吉 福井片町店','katamachi','順化','night','バー',''),
('s20c94c25','やきとり治郎吉 片町店','katamachi','順化','night','バー',''),
('sc9403682','㐂鶏屋(きどりや)','katamachi','順化','night','バー',''),
('sa83be97a','まるさん屋 福井片町店','katamachi','順化','night','バー','marusanya_fukuikatamachi'),
('s2859042f','和食海鮮ダイニング 柳庵','katamachi','順化','night','バー','yanagimachi_ryuan'),
('s692cdae2','ACE. Atrium','katamachi','順化','night','スナック・ラウンジ',''),
('s8b15a371','Acclaim','katamachi','順化','night','スナック・ラウンジ',''),
('s6081fa64','Aries trois','katamachi','順化','night','スナック・ラウンジ',''),
('scd30cc66','Believe','katamachi','順化','night','スナック・ラウンジ',''),
('sd896e76d','C Collection','katamachi','順化','night','スナック・ラウンジ',''),
('scf57e8cf','CAMELLIA','katamachi','順化','night','スナック・ラウンジ','camellia20071206'),
('s14ccb856','CAVERNA AZZURRA','katamachi','順化','night','スナック・ラウンジ',''),
('s8652d2be','Diamond','katamachi','順化','night','スナック・ラウンジ',''),
('s3cb61315','Girl''s Bar rerain','katamachi','','night','スナック・ラウンジ',''),
('sd0a2a0c2','J&rsquo;ADORE','katamachi','順化','night','スナック・ラウンジ','jadore_fukui.lounge'),
('s5dcf0a7e','LOUNGE GLITTER','katamachi','順化','night','スナック・ラウンジ','glitter.lounge'),
('s018da4c4','Lounge ACE','katamachi','順化','night','スナック・ラウンジ',''),
('s7897de60','Lounge BR','katamachi','順化','night','スナック・ラウンジ',''),
('s696aa26f','Lounge Refuge','katamachi','順化','night','スナック・ラウンジ',''),
('sd6f31ced','Lounge el','katamachi','順化','night','スナック・ラウンジ','lounge_el_ocg'),
('sff1f8564','Lounge 凛','katamachi','順化','night','スナック・ラウンジ','lounge.rin'),
('sd7670334','MIZUKI','katamachi','順化','night','スナック・ラウンジ',''),
('s7093e6e6','MOGA MODERN GIRL','katamachi','順化','night','スナック・ラウンジ',''),
('s96c9f9e9','OPUS ONE','katamachi','','night','スナック・ラウンジ',''),
('s86208ee6','SAYA','katamachi','順化','night','スナック・ラウンジ',''),
('sc33ee9ba','THE Moon.','katamachi','順化','night','スナック・ラウンジ',''),
('s0070b912','club 蒼 Ao','katamachi','順化','night','スナック・ラウンジ','club_ao_fukui'),
('s11078327','スナック 麻衣','katamachi','順化','night','スナック・ラウンジ',''),
('s2aa053e0','ラウンジ Imari','katamachi','順化','night','スナック・ラウンジ','imari_1221'),
('sa523f63f','ラウンジ Yuka','katamachi','順化','night','スナック・ラウンジ',''),
('sbcdeae46','ラウンジ 阿吽','katamachi','順化','night','スナック・ラウンジ',''),
('sfef16d72','楚々 -soso-','katamachi','順化','night','スナック・ラウンジ','soso_fukui'),
('s4178b9d7','篠','katamachi','順化','night','スナック・ラウンジ',''),
('se1936e87','良玄 RYOGEN','katamachi','順化','night','スナック・ラウンジ',''),
('s0a007fe7','黄色いハンカチ','katamachi','順化','night','スナック・ラウンジ',''),
('s5b3c0a45','Agit(アジト) drink, eat and chat','katamachi','','night','バー',''),
('s7671719e','Night sweets BAR Salice(サリチェ)','katamachi','順化','night','バー','salicefukui_pr'),
('sd0d94c1c','ばあー くろぽん','katamachi','','night','バー',''),
('s74c8a348','パブ&レストラン樽調理場','katamachi','順化','night','スナック・ラウンジ',''),
('s80a014ad','煉瓦館','katamachi','順化','night','バー',''),
('see5cdcbb','Amusemet Bar DOOR','katamachi','','night','バー',''),
('s409ccc73','BAR RADIO','katamachi','','night','バー',''),
('scabfb9f0','BAR UTa','katamachi','','night','バー',''),
('sd9ecbdb0','BAR くろひげ','katamachi','','night','バー',''),
('s73e6e77b','BAR レッツゴーヤング','katamachi','順化','night','バー','lets_go_young'),
('s53c9adae','BIRTH','katamachi','順化','night','バー',''),
('s096e774f','Bar jake','katamachi','','night','バー',''),
('s17d973b1','Bar九龍','katamachi','順化','night','バー',''),
('s8b31c932','DUFFTOWN','katamachi','','night','バー',''),
('s22159064','FLOW','katamachi','順化','night','バー',''),
('s1f8c518f','K''z Bar(ケーズ・バー)','katamachi','','night','バー',''),
('s58a7b43c','Musica Y BAR SOMBRERO','katamachi','','night','バー',''),
('s1e92bf48','ORIGINAL SOUND mix cafe CREME','katamachi','','night','バー',''),
('scd2f4e84','SECRET CLASSICAL','katamachi','','night','バー',''),
('s619ad5ff','THE BAR LOTUS','katamachi','','night','バー',''),
('s625795a8','THE BAR [i:st](イースト)','katamachi','','night','バー',''),
('s58f7060e','gri-gri','katamachi','','night','バー',''),
('s5e344923','ハイボール ビール おもてなし OSPITALITA(オスピタリタ)','katamachi','順化','night','バー','giorno_fukui'),
('sfb20caad','ブラッセリー&クラシックバー Very good','katamachi','順化','night','バー','verygoodbar'),
('se8bfa315','レストバー season(シーズン)','katamachi','','night','バー',''),
('sd7e77550','ワインバル フォンデン','katamachi','順化','night','バー','fonden_winebar'),
('s0e5dfdac','浪漫','katamachi','順化','night','バー','')
on conflict (slug) do update set name=excluded.name, zone=excluded.zone, town=excluded.town,
  category=excluded.category, genre=excluded.genre,
  instagram=case when public.shops.instagram_from='research' then excluded.instagram else public.shops.instagram end;
