-- build_seed.py が作るファイル。手で直さないこと。
insert into public.shops (slug,name,zone,town,category,genre,instagram) values
('s7fbd8215','Cafe&Bar まっしろ','ekimae','中央','night','バー','mashiro_cafeandbar'),
('s8441afb1','Mon Somme(モンソム)','ekimae','中央','gourmet','その他','mon.somme'),
('s31dcadd0','cafe はな','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s4f811d32','や台ずし 福井駅東口町','ekimae','日之出','gourmet','その他','yataizushi_official'),
('s691f731e','わおん書房','ekimae','中央','gourmet','その他','waonbooks'),
('s69411869','エノバル','ekimae','中央','gourmet','居酒屋','enobar_fukui'),
('s54c3c504','エンジョeat!!! CAFE','ekimae','中央','gourmet','カフェ・スイーツ','enjoyeat_fukui'),
('s44dd52a3','クレープ&バル FUKU NOTE','ekimae','中央','gourmet','居酒屋',''),
('s5be27486','スローベリィ くるふ福井駅福井店/高井屋','ekimae','中央','gourmet','その他',''),
('s9bf2cb0a','ハピリン総合受付','ekimae','中央','gourmet','その他','happiring_fukui'),
('sad3393df','マルノウチ フクラ','ekimae','中央','gourmet','その他',''),
('s7d7bd31f','小籠包ダイニング 鼎''s by JIN DIN ROU','ekimae','中央','gourmet','その他',''),
('s7896880c','椿宗善 日之出店','ekimae','日之出','gourmet','その他','tsubakisozen'),
('s5cb95492','焼きそば専門店 金波','ekimae','中央','gourmet','そば・うどん','yakisoba_kinpa'),
('s87ba4420','焼肉 牛成','ekimae','中央','gourmet','焼肉・肉料理','ushinari_yakiniku'),
('s96304935','爽茶','ekimae','中央','gourmet','その他','socha_cafe'),
('s09c213ea','若廣(くるふ福井駅店)','ekimae','中央','gourmet','その他','wakahiro_jp'),
('saec8252a','茶屋cafe あたらしや','ekimae','中央','gourmet','カフェ・スイーツ','atarashiyaasuwayama'),
('s2c635ca0','越前あて巻き デリアテール','ekimae','中央','gourmet','その他','deliaterre_minie'),
('s0ed71686','開花亭 BIS','ekimae','中央','gourmet','その他',''),
('sabcab050','韓国厨房 崔家','ekimae','中央','gourmet','アジア・各国料理','saike_fukui'),
('s1a91596b','食べる本屋さん','ekimae','中央','gourmet','その他','taberuhonyasan_fukuiseibu'),
('sd2740f86','駅前中華そば だるまや','ekimae','中央','gourmet','そば・うどん',''),
('s7616aa93','麺匠 麦之助(MINIE店)','ekimae','中央','gourmet','ラーメン','mensho_muginosuke'),
('s36ea945b','お好み焼たなか','ekimae','照手','gourmet','その他',''),
('s268c7b8a','さくら茶屋you‐canビル店','ekimae','中央','gourmet','その他',''),
('sb72278fe','たけや','ekimae','照手','gourmet','その他',''),
('s4ed8240c','ひらい','ekimae','大手','gourmet','その他',''),
('sbab28a94','小次郎','ekimae','大手','gourmet','その他',''),
('s4d076cd8','金ちゃん','ekimae','中央','gourmet','その他',''),
('s1c7e5b4b','PLAYCE(プレイス)','ekimae','中央','gourmet','その他','playce_fukui'),
('sd011f4ae','ラニーピクニック','ekimae','中央','gourmet','その他',''),
('s7ed82504','日々色々(ヒビイロイロ)','ekimae','大手','gourmet','その他','hibiiroiro291'),
('sfb0971c5','越前蕎麦倶楽部','ekimae','中央','gourmet','そば・うどん','echizensobaclub'),
('s482ab95b','TRAU VANG 88 FOODS','ekimae','中央','gourmet','その他',''),
('s3d3c6143','Bear’sBar','ekimae','照手','gourmet','その他',''),
('se66b1d1d','Swing’n‐Base','ekimae','中央','gourmet','その他',''),
('s08b6d000','fukui cafe Chadou','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('s281bf00b','あすわ','ekimae','大手','gourmet','その他',''),
('s5ce0e5b0','かりゆし','ekimae','日之出','gourmet','その他',''),
('s2d75effd','きぬ','ekimae','中央','gourmet','その他',''),
('s272fb962','さつき','ekimae','中央','gourmet','その他',''),
('s2e9f2fb6','とらや','ekimae','大手','gourmet','その他',''),
('s8003c885','のみすけ','ekimae','中央','gourmet','その他',''),
('scc329f9e','まると','ekimae','日之出','gourmet','その他',''),
('s1f0b3df9','むらさき','ekimae','大手','gourmet','その他',''),
('s398e9bd3','オリーブの木','ekimae','大手','gourmet','その他',''),
('s0091a48e','カントリ','ekimae','大手','gourmet','その他',''),
('sb32fb9cb','カーサ福井西武店','ekimae','中央','gourmet','その他',''),
('sa02f4751','カームタイム(CalmTime)','ekimae','大手','gourmet','アジア・各国料理',''),
('sd08e56bb','サロン女湯','ekimae','中央','gourmet','その他',''),
('sa4132b5b','シェ・サカイ','ekimae','中央','gourmet','その他',''),
('s2e2c957c','ヤマシタパン','ekimae','大手','gourmet','カフェ・スイーツ',''),
('sa871019f','七平','ekimae','手寄','gourmet','その他',''),
('sb1ac409e','今川焼本舗','ekimae','中央','gourmet','その他',''),
('s2799f8eb','匠きし','ekimae','中央','gourmet','その他',''),
('se800168c','印度','ekimae','大手','gourmet','その他',''),
('s7822e51b','女子寮/福井駅前店','ekimae','大手','gourmet','その他',''),
('s6133a887','料理 仕出し 与志多','ekimae','照手','gourmet','その他','tabakoya.yamamachi'),
('sd2851ea1','晴海','ekimae','中央','gourmet','その他',''),
('s2780b245','株式会社アンクル','ekimae','大手','gourmet','その他',''),
('s1598a124','桜むすび','ekimae','中央','gourmet','その他',''),
('s1edee58d','樅ノ木','ekimae','中央','gourmet','その他',''),
('s03b15c52','海賊艇','ekimae','中央','gourmet','その他',''),
('s81ab1c3d','熊五郎','ekimae','中央','gourmet','その他',''),
('s55f3d432','甘露司 飛嶋','ekimae','中央','gourmet','その他',''),
('sf5bfdba9','番匠本店 上りホーム店','ekimae','中央','gourmet','その他',''),
('sd56ace3d','福井ワシントンホテル・バロン','ekimae','大手','gourmet','その他',''),
('s7d67dc69','福井大麦倶楽部','ekimae','日之出','gourmet','その他',''),
('s707b8afd','福井県庁食堂','ekimae','大手','gourmet','その他',''),
('s42e6e5a6','福井駅前フードホール MINIE','ekimae','中央','gourmet','その他',''),
('sf371dde9','秋吉 New秋吉','ekimae','大手','gourmet','その他',''),
('sc17f4e42','芝寿し 福井店','ekimae','大手','gourmet','その他',''),
('sc0f5aa2d','越前市場','ekimae','手寄','gourmet','その他',''),
('s20744fed','越前田村屋・プリズム福井店','ekimae','中央','gourmet','その他',''),
('sea986e8d','モンナリッサの森','ekimae','中央','gourmet','アジア・各国料理',''),
('se5583b37','白菜美人','ekimae','中央','gourmet','アジア・各国料理',''),
('s84142e3a','FanFan','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s7f0b5db2','Italian Kitchen VANSAN','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('sd70a6325','イタリアスパゲティ','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s02550abd','トレパーチェ・イタリアンレストラン','ekimae','大手','gourmet','イタリアン・フレンチ',''),
('se14b3b3f','ドレッセ','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s90e001cc','侍パスタ','ekimae','手寄','gourmet','イタリアン・フレンチ',''),
('s76408c0a','Paleo Brew Cafe','ekimae','中央','gourmet','カフェ・スイーツ','brewcafe00'),
('sc3c80ac6','cafe ieme','ekimae','中央','gourmet','カフェ・スイーツ','cafe_ieme'),
('s3e58125e','あんカフェ','ekimae','中央','gourmet','カフェ・スイーツ','an.cafe.oshima'),
('s4a2831ba','ごーる堂Do+','ekimae','中央','gourmet','カフェ・スイーツ','soysoftcream_goldo'),
('s9d624ce9','ヨリバ(YORIVER)','ekimae','中央','gourmet','カフェ・スイーツ','yoriver_asuwa'),
('s276f99eb','抹茶庵 福井中央店','ekimae','中央','gourmet','カフェ・スイーツ','matchaan_fukui'),
('s44b5276e','PUITS D’AMOUR','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('s8a3f24e9','UCC CAFE MERCADO 福井西武','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s359812db','YEN','ekimae','大手','gourmet','カフェ・スイーツ',''),
('sab0da53d','cafe maachar','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sf8e2058b','えがわ','ekimae','照手','gourmet','カフェ・スイーツ',''),
('s13905151','かがみ','ekimae','大手','gourmet','カフェ・スイーツ',''),
('sbcb69889','きんつばの中田屋 プリズム福井水仙花店','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s5fcc5b45','つゆ','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s86e1194f','ぴえろはうす','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('sad7e62bf','みるく茶庵','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s91dea10e','るうぶる','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s859b836c','れーるろーど','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s478d54dc','カフェるん','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s36103bc2','カフェ・カプチーナ','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s2a1fd4c1','キルトカフェ・趣味工房','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s5cdbf379','クリーミードーナツ 福井駅前店','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s67d9b1ae','コーヒー専門吉田','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sa20e3e11','サロンド・GO','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s1b88cf41','シークチョイスカフェ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s6f1aaa8f','ダーツカフェ Green Box','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('sda7065aa','チャーム','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s8e708fc9','トーヨー','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s0f4e999b','ニシムラカフェ駅前店','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s4c7ec2c3','ニッパー','ekimae','照手','gourmet','カフェ・スイーツ',''),
('sbbce2c2f','ハシモト洋菓子店','ekimae','つくも','gourmet','カフェ・スイーツ',''),
('sfae834e9','ハーフ','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('s1b5bdc0b','ベーカリープラザ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s6bb5bc7f','ポニー純喫茶','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s539f12a1','マタリ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s567b4238','ムーラン','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sc8e51bff','モジカフェ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sb5d66038','モンターニュ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sf06a7d20','ヤン・カフェ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s57778317','ユトリ珈琲店 AOSSA店','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('sf253ab07','ユミ','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s4d0b8d82','リトルマーメイドくるふ福井駅','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sa0155603','ルビー','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sb76a8139','ル・ピュイ','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('scebf7e9b','ルーツカフェ(ROUTE’SCAFE)','ekimae','照手','gourmet','カフェ・スイーツ',''),
('sc0f77424','古城','ekimae','大手','gourmet','カフェ・スイーツ',''),
('sf14bda3d','天秤座','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s73548a07','奈々重','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s98b47d7f','快活CLUB/福井駅前店','ekimae','大手','night','スナック・ラウンジ',''),
('s10e1f57f','森のフェスタおばさん','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s5fa54a4e','森乃家','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s5c294506','神戸ふう月堂福井店','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s94386578','絵紋','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s61151c82','花','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s572583db','茶房談話室','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s6efdb81a','蒼山','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('sbf0a4361','逢園','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s4d28e1e7','銀座茶廊','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s96ac50a1','Kisaki CAFE CENTRAL PARK','ekimae','大手','gourmet','カフェ・スイーツ',''),
('seff70599','とろけるクレープ MOMI&TOY’S 福井駅前店','ekimae','中央','gourmet','カフェ・スイーツ','momitoy_fukuiekimae'),
('sbc9f8a54','カフェレストラン su_mu(スム)','ekimae','中央','gourmet','カフェ・スイーツ','su_mu300567'),
('s1018b4c4','CAFÉ52(カフェ ゴジュウニ)','ekimae','中央','gourmet','カフェ・スイーツ','cafebar52'),
('s0bd2f63c','HANDS COFFEE(ハンズコーヒー)','ekimae','中央','gourmet','カフェ・スイーツ','hands_coffee'),
('s1aafc2bb','Att kitchen( アットキッチン)','ekimae','中央','gourmet','カフェ・スイーツ','att_kitchen_'),
('s33de1202','CAFÉ CON TE(カフェコンテ)','ekimae','中央','gourmet','カフェ・スイーツ','cafe.conte2026'),
('s6f98adcc','Magari Coffee(マガリコーヒー)','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s4098663f','カフェまてき','ekimae','大手','gourmet','カフェ・スイーツ',''),
('sb543236c','高級和栗モンブラン専門店 栗歩 福井駅前店(くりほ)','ekimae','中央','gourmet','カフェ・スイーツ','waguri_montblanc_kuriho'),
('sc4ebbf42','Okazu&bread(オカズ アンド ブレッド)','ekimae','手寄','gourmet','カフェ・スイーツ','okazu_and_bread'),
('s19efcdc4','エトワァル','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s83d42a65','マルサパン','ekimae','手寄','gourmet','カフェ・スイーツ',''),
('sa186b57e','AFTERGLOW CHOCOLATE(アフターグロウチョコレート)','ekimae','照手','gourmet','カフェ・スイーツ','afterglow_chocolate'),
('sb4ad068c','Good Smile Donut(グッドスマイルドーナツ)','ekimae','日之出','gourmet','カフェ・スイーツ','goodsmile.donut'),
('sd546a9d9','スコーン専門店 肆 -よん-','ekimae','中央','gourmet','カフェ・スイーツ','yon_scone'),
('s7ee907f6','サニーさんの農園マルシェ','ekimae','中央','gourmet','カフェ・スイーツ','sunnysfarmmarche'),
('s0ac00f12','8番らーめん/くるふ福井駅店','ekimae','中央','gourmet','ラーメン',''),
('s75e3bf56','いちや福井駅前店','ekimae','中央','gourmet','ラーメン',''),
('s61d8b801','なん・なん亭 福井店','ekimae','大手','gourmet','ラーメン',''),
('s3370fd96','集集','ekimae','中央','gourmet','ラーメン',''),
('s30c78e0f','Bistro&Bar GLOUTONNE','ekimae','中央','night','バー',''),
('s8a28b280','キナリ','ekimae','日之出','gourmet','洋食','_____kinari'),
('s0a856f1a','トラットリア チャオ','ekimae','中央','gourmet','イタリアン・フレンチ','trattoria_ciao_'),
('s6f5e18f4','西武福井店 ダイニングスクエア','ekimae','中央','gourmet','洋食',''),
('se64356d9','あみだそば はなれ','ekimae','中央','gourmet','そば・うどん',''),
('s69243200','おそばだうどんだ越前','ekimae','中央','gourmet','そば・うどん',''),
('s8ad103bd','三井屋','ekimae','つくも','gourmet','そば・うどん',''),
('s9a8cb6ff','日ノ出西村屋','ekimae','日之出','gourmet','そば・うどん',''),
('s4583b225','蕎麦庵 sio(シオ)','ekimae','中央','gourmet','そば・うどん','sobaansio40'),
('s7668ab61','Beer&Grill GRIOMAN(グリオマン)','ekimae','中央','gourmet','焼肉・肉料理','grioman_fukui'),
('s25796be9','U(ユー)','ekimae','大手','gourmet','焼肉・肉料理','u__fukui'),
('sbebfde1a','パスタと珈琲とカヌレのお店','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s56b39f6a','RUNNY PICNIC(ラニーピクニック)','ekimae','中央','gourmet','洋食','runny.picnic'),
('s1c5b0523','日豪レストラン ゆめや','ekimae','中央','gourmet','洋食',''),
('s55e7c838','越山若水 行雲(えつざんじゃくすいこううん)','ekimae','中央','gourmet','洋食','etsuzanjyakusui_koun'),
('sd4e68c11','すし日竜(ひりゅう)','ekimae','中央','gourmet','寿司・海鮮','sushi_hiryu'),
('s03f8cc3e','大衆赤酢寿司 ぼんた','ekimae','中央','gourmet','寿司・海鮮',''),
('s0c2231f0','sake to ate(サケトアテ)','ekimae','日之出','gourmet','居酒屋','sake.to.ate'),
('s0f913aee','タコとハイボール','ekimae','中央','gourmet','居酒屋',''),
('s7668ab61','大衆酒場 れいわ 福井駅前店','ekimae','中央','gourmet','居酒屋',''),
('se90bbb55','大衆酒場 ラドン','ekimae','中央','gourmet','居酒屋',''),
('see25b77f','手羽先番長 福井駅前店','ekimae','中央','gourmet','居酒屋','tebasakibancho_fukui'),
('sb65f332e','酒と肴の旨い店 和華(わか)','ekimae','照手','gourmet','居酒屋','izakaya__waka'),
('s9bc498e5','越前海鮮屋 福井駅前店','ekimae','中央','gourmet','寿司・海鮮',''),
('sc94c43ec','やきとり やすぎ家','ekimae','中央','gourmet','焼鳥・串','yasugiya.tomomi'),
('sf61651e6','えがわ プリズム福井 水仙花店','ekimae','中央','gourmet','中華',''),
('s0c6c7bbb','たごさく 福井西武','ekimae','中央','gourmet','中華',''),
('s5c375ccf','ゴディバ 西武福井','ekimae','中央','gourmet','中華',''),
('s0a5d3303','ドンク 西武福井店','ekimae','中央','gourmet','中華',''),
('s513f8ff4','ボノボノ プリズム福井店','ekimae','中央','gourmet','中華',''),
('sbd243964','万よし','ekimae','中央','gourmet','中華',''),
('sfc766a3a','御菓子司 栄太楼','ekimae','中央','gourmet','中華',''),
('sbaccabfb','悟空','ekimae','大手','gourmet','中華',''),
('s70b0f1a5','満堂紅福井店','ekimae','中央','gourmet','中華',''),
('s0e6cf074','白楽','ekimae','日之出','gourmet','中華',''),
('sc4b4e40b','目からうろこ 福井駅前本店','ekimae','中央','gourmet','中華',''),
('s6809818c','福林軒','ekimae','中央','gourmet','中華',''),
('s5e66ff80','羽二重餅の古里 マエダセイカ プリズム福井 水仙花店','ekimae','中央','gourmet','中華',''),
('sd7ac3a10','鳳城酒家','ekimae','中央','gourmet','中華',''),
('s3fed0671','Cafe&Curry カレッテリア','ekimae','大手','gourmet','アジア・各国料理','caletteria'),
('s2d8cb41e','Livin’ for green','ekimae','中央','gourmet','アジア・各国料理','livin_for_green'),
('s39bea949','モーニングトマト','ekimae','中央','gourmet','アジア・各国料理',''),
('s26c0f87c','いちろくらーめん ふくい駅前店','ekimae','中央','gourmet','ラーメン','ichiroku_ramen'),
('sfa12c119','つけ麺 いちろく','ekimae','中央','gourmet','ラーメン','ichiroku_ramen'),
('s2caeb34f','とりで','ekimae','日之出','gourmet','ラーメン',''),
('s6b9bcc45','五目亭の福井らーめん「かたいけの」','ekimae','中央','gourmet','ラーメン','fukui_ramen_gomokutei'),
('s8c4eebb6','屋台 てっちゃんラーメン 福井駅前店','ekimae','中央','gourmet','ラーメン',''),
('sffb16825','屋台 岩ちゃんラーメン','ekimae','中央','gourmet','ラーメン',''),
('s27343607','つくも橋 ピリケン 本店','ekimae','つくも','gourmet','中華','pilliken_honten'),
('s5fcbd905','ふ一 MINIE店','ekimae','中央','gourmet','中華','fuichi_fukui'),
('sdc3cbb64','中国料理 紅蘭','ekimae','中央','gourmet','中華',''),
('sec11e85c','中華料理 ISSEI','ekimae','手寄','gourmet','中華',''),
('se710cfe5','四季彩中華 シノワ','ekimae','大手','gourmet','中華',''),
('s890e7d23','四川料理 西遊記','ekimae','中央','gourmet','中華',''),
('s6c838691','来々軒','ekimae','つくも','gourmet','中華',''),
('sd35a5578','茶荘・香蘭(ちゃそうこうらん)','ekimae','中央','gourmet','中華','chasoukouran2025111'),
('s1b359789','Dogs','ekimae','大手','gourmet','アジア・各国料理','dogs_hotdog_fukui'),
('s67908d92','KOREA','ekimae','中央','gourmet','アジア・各国料理',''),
('s743e8c6c','TARY HOUSE','ekimae','中央','gourmet','アジア・各国料理','taryhouse'),
('se1680e15','ベトナムレストラン Que Huong Quan','ekimae','中央','gourmet','アジア・各国料理',''),
('sc15721ee','居酒屋 しゃんがり。','ekimae','大手','gourmet','居酒屋','izakaya_shangari_fukui'),
('s8be5beb6','いっ福亭','ekimae','日之出','gourmet','焼肉・肉料理',''),
('s588dd8ac','ホルモン 焼肉 お食事処 はるや','ekimae','日之出','gourmet','焼肉・肉料理',''),
('s22bd026c','鉄板焼肉とジンギスカン ぼんた 福井駅前店','ekimae','大手','gourmet','焼肉・肉料理','jingisukanbonta'),
('s4aa386ab','おお田','ekimae','大手','gourmet','和食',''),
('s3527a6ce','かわきん','ekimae','大手','gourmet','和食',''),
('s6cf33e3c','こんぴら亭三の丸店','ekimae','大手','gourmet','和食',''),
('s9a9b6a54','さが良','ekimae','照手','gourmet','和食',''),
('sb06737be','さくら茶屋くるふ福井駅店','ekimae','中央','gourmet','和食',''),
('seda0e607','せいもん','ekimae','大手','gourmet','和食',''),
('sfe9342cb','そば勝アオッサ店','ekimae','手寄','gourmet','そば・うどん',''),
('s392c8643','そば勝本店','ekimae','中央','gourmet','そば・うどん',''),
('s977f9ab2','てらしま','ekimae','中央','gourmet','和食',''),
('s64a33e0b','はら田','ekimae','照手','gourmet','和食',''),
('s470d2762','まわるすし中央店','ekimae','中央','gourmet','寿司・海鮮',''),
('s7b9d37ca','やま田','ekimae','中央','gourmet','和食',''),
('sc5d36fef','カルマ繊協ビル店','ekimae','大手','gourmet','和食',''),
('s4a1313e4','ビックリ竹田屋総本店','ekimae','大手','gourmet','和食',''),
('s47175d3f','ミチ','ekimae','中央','gourmet','和食',''),
('s67b72d3c','ランチ屋 麦米','ekimae','大手','gourmet','和食',''),
('sb2683b78','三喜寿司','ekimae','日之出','gourmet','寿司・海鮮',''),
('sd9c0a218','中清','ekimae','中央','gourmet','和食',''),
('s508562d6','今庄そば','ekimae','手寄','gourmet','そば・うどん',''),
('sa7c85c96','信濃','ekimae','中央','gourmet','和食',''),
('sa30f648f','割烹敏','ekimae','中央','gourmet','和食',''),
('s9c6c2422','呑喜','ekimae','中央','gourmet','和食',''),
('sa33c83e7','和食料理 釜蔵','ekimae','中央','gourmet','和食',''),
('s0f7a740d','善甚','ekimae','大手','gourmet','和食',''),
('sc5a5aadf','城の橋','ekimae','手寄','gourmet','和食',''),
('s8ea4c3b0','天新','ekimae','大手','gourmet','和食',''),
('sf7ee645e','太鼓寿し','ekimae','大手','gourmet','和食',''),
('sfed1e0c1','宴会屋','ekimae','大手','gourmet','和食',''),
('s089c89ef','富士','ekimae','日之出','gourmet','和食',''),
('s8fc8b4d9','山清','ekimae','中央','gourmet','和食',''),
('s878f6e02','新日本料理 桜ばし','ekimae','中央','gourmet','和食',''),
('sf4472555','昌冨ずし','ekimae','中央','gourmet','和食',''),
('s33a711ac','昭和寿司','ekimae','照手','gourmet','寿司・海鮮',''),
('s6fe70d3a','楽庵','ekimae','中央','gourmet','和食',''),
('se210380d','歌舞伎寿司本店','ekimae','中央','gourmet','寿司・海鮮',''),
('s8d2bdf59','満里邑','ekimae','中央','gourmet','和食',''),
('s9b10b23a','源治鮨','ekimae','大手','gourmet','寿司・海鮮',''),
('s7ad15852','照寿し','ekimae','中央','gourmet','和食',''),
('s3dd83a32','甘泉堂','ekimae','中央','gourmet','和食',''),
('s52fa3549','生簀海鮮 やまもとや','ekimae','大手','gourmet','寿司・海鮮',''),
('sea9725fc','町寿司いちもんめ 福井駅前','ekimae','大手','gourmet','寿司・海鮮',''),
('s19600a96','異人館跡風琴亭','ekimae','中央','gourmet','和食',''),
('sf71ab51f','福井山相撲料理','ekimae','中央','gourmet','和食',''),
('sba6e73e6','笏谷そば だるまや西武店','ekimae','中央','gourmet','そば・うどん',''),
('s9c7f80f2','芝寿し 福井西武店','ekimae','中央','gourmet','和食',''),
('sdaf8623c','華家','ekimae','大手','gourmet','和食',''),
('s331b3393','葵納豆料理店','ekimae','照手','gourmet','和食',''),
('sf92fe821','農協のおむすび大手町店','ekimae','大手','gourmet','和食',''),
('sdcf3c594','野のや','ekimae','中央','gourmet','和食',''),
('s897b57f1','鮨志乃介','ekimae','中央','gourmet','寿司・海鮮',''),
('sc9530b9a','あさひそば 本店','ekimae','中央','gourmet','そば・うどん',''),
('sa94353fd','越前つるきそば本店','ekimae','中央','gourmet','そば・うどん','tsurukisoba'),
('s80891f7c','お好み焼き エミ','ekimae','大手','gourmet','和食',''),
('s23391263','広島風お好み焼き・つけ麺 一期一会','ekimae','日之出','gourmet','ラーメン',''),
('s32b00400','とんかつ そば 吉ちょう','ekimae','大手','gourmet','そば・うどん',''),
('sf5ddf8e7','むろまち','ekimae','中央','gourmet','焼肉・肉料理',''),
('saf5a7fa3','富士喜 MINIE店','ekimae','中央','gourmet','焼肉・肉料理','fujiki_2020'),
('s1dfd4d1a','熟成かつ 天膳 ハピリン店','ekimae','中央','gourmet','焼肉・肉料理','fukui.tonkatu.amazen'),
('s3257e875','RICE BAR CRAFT SAKE LABO','ekimae','中央','night','バー','bridgelabo_ricebar'),
('s447c7347','お食事処 飛彈','ekimae','中央','gourmet','和食','hida_fukui'),
('sb134d23b','しゃぶしゃぶ・鍋・割烹 銀座','ekimae','大手','gourmet','和食',''),
('s68443c09','まちDeli かくれわ食堂','ekimae','中央','gourmet','和食','kakurewa2016'),
('sd2f23010','一品料理 四十萬','ekimae','大手','gourmet','和食',''),
('s00743a4b','旬魚とおでん 味美家','ekimae','日之出','gourmet','寿司・海鮮',''),
('s3f9381d5','浜町 かつき','ekimae','中央','gourmet','焼肉・肉料理',''),
('sa173db6f','福い','ekimae','中央','gourmet','和食','courtyard_by_marriott_fukui'),
('s304f9740','福井フェニックスホテル 和食・茶房 養浩館','ekimae','大手','gourmet','和食',''),
('sfa13ee3a','紋や','ekimae','中央','gourmet','和食','monya_141117'),
('s027d4522','蟹と海鮮 ぼんた','ekimae','中央','gourmet','寿司・海鮮','kanibonta'),
('s11804aca','越前がに・旬のお料理 らでん','ekimae','中央','gourmet','和食','raden0428'),
('s37eaeae8','越前蕎麦・お食事処 花ひらく','ekimae','大手','gourmet','そば・うどん',''),
('sf813e082','魚善','ekimae','大手','gourmet','寿司・海鮮',''),
('s87ba4420','ほまれ寿司','ekimae','中央','gourmet','寿司・海鮮','homaresushi'),
('s2ba55054','鮨 仲島','ekimae','中央','gourmet','寿司・海鮮','sushi_nakajima_fukui'),
('sf5f397ee','鮨清','ekimae','中央','gourmet','寿司・海鮮','sei2025525'),
('s0c41fd45','割烹料亭 かき恭','ekimae','中央','gourmet','和食',''),
('sae63d11b','和の食 忠兵衛','ekimae','中央','gourmet','和食',''),
('s5dd435e4','和心味NAGOMI たち花','ekimae','大手','gourmet','和食',''),
('sb3b45b94','料亭 開花亭','ekimae','中央','gourmet','和食',''),
('sdb36d8c6','日本料理 越前がに 浜町 緒ばた','ekimae','中央','gourmet','和食','obata_hamamachi'),
('s9bee29d3','旬味 泰平','ekimae','中央','gourmet','和食',''),
('s07d13a5e','楽tei なか田”','ekimae','中央','gourmet','和食','rakutei_nakada'),
('se6f0dda9','美食 恵長庵 まんもと','ekimae','日之出','gourmet','和食',''),
('se0f468ca','開花亭 sou-an','ekimae','中央','gourmet','和食',''),
('s641ed098','香爐園','ekimae','中央','gourmet','和食','fukui.kouroen'),
('s69749d6a','kitchen 和','ekimae','大手','gourmet','和食','kitchennagomi2023111'),
('sf0f71534','お食事処 ほていや','ekimae','中央','gourmet','和食',''),
('scf8cca10','ふくいのこめとだし まるしん','ekimae','中央','gourmet','和食','marushin_kometodashi'),
('s86f800ed','凸凹29ごはん 福井市役所地下','ekimae','大手','gourmet','和食',''),
('s1c1b7239','福井肉食堂','ekimae','中央','gourmet','焼肉・肉料理','kurufu_nikusyokudo'),
('sa2a3ccc4','福福茶屋','ekimae','中央','gourmet','和食','hukubuku2929'),
('s082726aa','BLUESTOCKING','ekimae','中央','gourmet','カフェ・スイーツ','bluestocking.seibu'),
('s0e036df3','CTS(シータス)','ekimae','照手','gourmet','カフェ・スイーツ','cts_coffee_to_sand'),
('s437b3812','Cafe CoCotte','ekimae','中央','gourmet','カフェ・スイーツ','cafecocotte420'),
('s40dd3cf5','Cafe リンデン','ekimae','大手','gourmet','カフェ・スイーツ','echizen_fukui_artmuseum_'),
('s0068cc18','NIVI','ekimae','中央','gourmet','カフェ・スイーツ','nivi_specialty_coffee'),
('se8ee5656','Organic Vegan cafe 深緑','ekimae','中央','gourmet','カフェ・スイーツ',''),
('sc7e29544','papillote','ekimae','中央','gourmet','カフェ・スイーツ','papillote_fukui'),
('s72772f7f','さんじのおやつ 観光交流センター店','ekimae','手寄','gourmet','カフェ・スイーツ','sanjinooyatsu_fk1001'),
('sea1d495e','まンまや おちょkitchen','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('s8f66dd35','イタリアン・トマト CafeJr. 福井西武店','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('sd708f1b4','点 葉巻室 福井店','ekimae','中央','gourmet','カフェ・スイーツ','ten_cigar_room_fukui'),
('sdcaf3a90','紅茶のお店 RanaTea','ekimae','中央','gourmet','カフェ・スイーツ','ranatea_fukui'),
('sb263c571','茶楽 かぐや 西武店','ekimae','中央','gourmet','カフェ・スイーツ','saraku_kaguya'),
('s2fdfd97e','カフェテラス','ekimae','中央','gourmet','カフェ・スイーツ',''),
('s5338c029','カラオケ喫茶 笑','ekimae','日之出','gourmet','カフェ・スイーツ',''),
('sf16f84cd','フルーツパーラー 果樹園','ekimae','中央','gourmet','カフェ・スイーツ','fruit_no_umeda_official'),
('s196d83f4','マギーズファーム','ekimae','中央','gourmet','カフェ・スイーツ','maggies_farm1986'),
('s0d9cf47f','喫茶 珈琲壺 〜コーヒーぽっと〜','ekimae','大手','gourmet','カフェ・スイーツ',''),
('s8b76fe09','Churrascaria ban(シュラスカリア バン) 福井店','ekimae','中央','gourmet','居酒屋',''),
('sb67ea96d','個室居酒屋 葵屋-あおいや- 福井駅前店','ekimae','中央','gourmet','居酒屋',''),
('s850722a5','おふくろの味こころ','ekimae','大手','gourmet','居酒屋',''),
('s67de7438','のんのん','ekimae','中央','gourmet','居酒屋',''),
('s65d5344b','のんべえよしき','ekimae','大手','gourmet','居酒屋',''),
('sf95c753b','まごころ','ekimae','中央','gourmet','居酒屋',''),
('s333dfc62','みなり','ekimae','大手','gourmet','居酒屋',''),
('s3cbdc57e','もみじ 福井駅前店','ekimae','中央','gourmet','居酒屋',''),
('sf1a7d4f6','ろ組 福井駅前店','ekimae','中央','gourmet','居酒屋',''),
('sdefd9b7f','ブラスリー河合','ekimae','中央','gourmet','居酒屋',''),
('sd3cdde76','三代目 鳥メロ 福井駅前店','ekimae','中央','gourmet','居酒屋',''),
('sd40f6f26','個室居酒屋 くいもの屋わん 福井駅前店','ekimae','中央','gourmet','居酒屋',''),
('s90c2ae57','六兵衛','ekimae','中央','gourmet','居酒屋',''),
('sd01dbf56','割烹 桝酒','ekimae','大手','gourmet','居酒屋',''),
('s098b101b','千本','ekimae','中央','gourmet','居酒屋',''),
('sa4f16f4c','味の王様ガレリア店','ekimae','中央','gourmet','居酒屋',''),
('safba9b18','土鍋ご飯《米と魚 たて涌》','ekimae','中央','gourmet','寿司・海鮮','tatewaki_kometosakana'),
('s847b5112','大衆とり酒場 とりいちず 福井駅前店','ekimae','中央','gourmet','居酒屋','toriichizu_mania'),
('s8cc017e9','安楽','ekimae','大手','gourmet','居酒屋',''),
('s13a09f65','寿司・地酒 はやし','ekimae','大手','gourmet','寿司・海鮮',''),
('s097c40a1','寿司和食処 わだつみ','ekimae','大手','gourmet','寿司・海鮮',''),
('s96ca45ee','小料理のむ喜 優','ekimae','中央','gourmet','居酒屋',''),
('sea741e8d','山がっちゃん家の台所','ekimae','大手','gourmet','居酒屋',''),
('s1853373d','横浜天下鳥 福井駅前店','ekimae','中央','gourmet','居酒屋',''),
('s333a28c2','然の家 味彩','ekimae','中央','gourmet','居酒屋',''),
('s47fbad00','焼肉 肉鍋 肉吟 福井駅前店','ekimae','中央','gourmet','焼肉・肉料理',''),
('se04557f5','玄達市場','ekimae','手寄','gourmet','居酒屋',''),
('s04b85b8e','目利きの銀次 福井西口駅前店','ekimae','大手','gourmet','居酒屋',''),
('sa73580d4','福井名物お刺身&豚骨おでん 酒処JET','ekimae','日之出','gourmet','居酒屋',''),
('s7cbf20df','菜香楼 くるふ福井駅店','ekimae','中央','gourmet','居酒屋',''),
('s21231265','越前地魚とおでん酒場 鮨とおでん','ekimae','中央','gourmet','寿司・海鮮',''),
('s583d78f9','越前若狭の旬と地酒 頂き枡 福井駅前東口店','ekimae','日之出','gourmet','居酒屋',''),
('s2298f9e8','越前魚酒 ほやほ家','ekimae','大手','gourmet','寿司・海鮮',''),
('s0000e279','酒菜夜','ekimae','中央','gourmet','居酒屋',''),
('sf2a68918','魚河岸直営 いけす海鮮 ろ組くるふ福井駅店','ekimae','中央','gourmet','寿司・海鮮',''),
('s3ff73c5b','日本料理 橘','ekimae','大手','gourmet','和食',''),
('sbfc0e5ca','とみや','ekimae','中央','gourmet','洋食',''),
('s6831efc4','キンイロキッチンアオッサ店','ekimae','手寄','gourmet','洋食',''),
('s0ff080c0','シュバルージュ','ekimae','手寄','gourmet','居酒屋',''),
('s177662fe','ムサシノ軒','ekimae','手寄','gourmet','洋食',''),
('sdeccc578','ラッキー食堂1階レストラン部','ekimae','中央','gourmet','洋食',''),
('s6b8af86d','名産工房・旬','ekimae','中央','gourmet','洋食',''),
('s1268ca15','日下部','ekimae','中央','gourmet','洋食',''),
('seb4666bd','福井ワシントンホテル 銀座','ekimae','大手','gourmet','洋食',''),
('s47640b37','福井厚生年金会館','ekimae','手寄','gourmet','洋食',''),
('s3faa3277','赤茄子亭','ekimae','日之出','gourmet','洋食',''),
('s7daaf531','鉄板料理 薫風','ekimae','日之出','gourmet','洋食',''),
('s1fb95026','Alfredo','ekimae','中央','gourmet','イタリアン・フレンチ','alfredo_fukui'),
('s4bd2d309','Ristorante CUCINA','ekimae','中央','gourmet','イタリアン・フレンチ','ristorante_cucina_1991'),
('s927e1e54','Sincere Lily','ekimae','中央','gourmet','イタリアン・フレンチ','sincerelily.fukui'),
('s21cb020b','イタリア食堂ITSUKI','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s52f71c78','サイゼリヤ 福井駅前店','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('s4af0766e','石窯食堂 Tsumugi(つむぎ)','ekimae','大手','gourmet','イタリアン・フレンチ','tsumugi_fukui'),
('s83ecf4d0','粟樹楼','ekimae','中央','gourmet','イタリアン・フレンチ',''),
('se32d8474','モンシェルトントンカトー','ekimae','中央','gourmet','焼肉・肉料理',''),
('s4b6df614','石窯焼 時ノ鐘','ekimae','中央','gourmet','焼肉・肉料理','tokinokane29'),
('s81e6bc1f','鉄板焼き 紡ぐ','ekimae','大手','gourmet','焼肉・肉料理','tsumug_1116'),
('sd0520d08','Bistro & Bar GLOUTONNE','ekimae','中央','night','バー',''),
('sfbc6d733','Brasserie Lou','ekimae','中央','gourmet','イタリアン・フレンチ','brasserie_lou'),
('s30474fd0','Fukui French Aujus(オージュ)','ekimae','中央','gourmet','イタリアン・フレンチ','aujus_fukui'),
('s8dd0e3c0','IRISER','ekimae','大手','gourmet','イタリアン・フレンチ','iriser.fukui'),
('s35ee8df9','RESTAURANT OTSUKA','ekimae','大手','gourmet','イタリアン・フレンチ','restaurantotsuka'),
('sf09a0dcd','Salon De Chef  NAKAO','ekimae','大手','gourmet','イタリアン・フレンチ',''),
('s628e432e','ULO','ekimae','中央','gourmet','イタリアン・フレンチ','ulo_fukui'),
('sfe2ad9a7','la table de Roche(ロッシュ)','ekimae','手寄','gourmet','イタリアン・フレンチ',''),
('s55478b75','グリル葵','ekimae','大手','gourmet','イタリアン・フレンチ',''),
('s76637454','サラマンジェフ','ekimae','中央','gourmet','イタリアン・フレンチ','salle_a_mangerf'),
('sdb8de789','シェ・サカイ','ekimae','日之出','gourmet','イタリアン・フレンチ',''),
('s57eb7bb2','ビストロ後藤','ekimae','中央','gourmet','イタリアン・フレンチ','bistro_goto_goto510'),
('sb5b3b483','フランス酒場 Antique','ekimae','中央','gourmet','居酒屋','antique__fukui'),
('s514108e2','Substance','ekimae','中央','gourmet','洋食','courtyard_by_marriott_fukui'),
('s90da58ca','キッチントリアージュ','ekimae','中央','gourmet','洋食',''),
('sa5d3f7cc','二ノ丸グリル','ekimae','大手','gourmet','洋食',''),
('s7d628105','吉野寿司','ekimae','中央','gourmet','寿司・海鮮','fukui_yoshinozushi'),
('sb5bcd9fa','焼肉ホルモン はらたん 福井駅前店','ekimae','中央','gourmet','焼肉・肉料理',''),
('sd63ab7c5','そば処 三国屋','ekimae','大手','gourmet','そば・うどん',''),
('sb68ff2b6','今庄そば 福井駅コンコース店','ekimae','中央','gourmet','そば・うどん',''),
('s71f5a2b3','あみだそば 福の井','ekimae','中央','gourmet','そば・うどん',''),
('s6a9c9e23','あみだそば 遊歩庵','ekimae','中央','gourmet','そば・うどん','amidasoba'),
('sb13e7aef','福そば','ekimae','中央','gourmet','そば・うどん',''),
('s9356b702','蕎麦Dining 一福','ekimae','中央','gourmet','そば・うどん','ippuku129'),
('sa2fb7beb','福井名物ずわい蟹料理 こまつや','ekimae','照手','gourmet','寿司・海鮮',''),
('sde46651d','御菓子司 あまとや','ekimae','つくも','gourmet','カフェ・スイーツ',''),
('sc83ffc72','御菓子司 森八大名閣','ekimae','大手','gourmet','カフェ・スイーツ',''),
('sb541e4f7','村中甘泉堂本店/パティスリーKANSENDO','ekimae','中央','gourmet','その他',''),
('sf217005b','羽二重餅總本舗 松岡軒','ekimae','中央','gourmet','その他','matsuokaken.habutaemochi'),
('s70885d63','KAKETUKE','ekimae','中央','gourmet','居酒屋','kaketuke_fukui'),
('se183111c','お酒とおばんざい ななと実','ekimae','大手','gourmet','居酒屋','nanatomi_sachiko'),
('sbc95f6c8','きはちらくはち 駅前店','ekimae','大手','gourmet','居酒屋','kihachirakuhachi'),
('s2ec1c847','ろばた焼 弥吉 駅前店','ekimae','大手','gourmet','居酒屋',''),
('sf5065559','名古屋コーチンの 翠翔 福井駅前店','ekimae','大手','gourmet','居酒屋','_suisyooo'),
('saadbc958','呑み処 たけうち','ekimae','大手','gourmet','居酒屋',''),
('sf60bef90','居酒屋 竜の髭','ekimae','大手','gourmet','居酒屋',''),
('s4c30b710','旬香逎燈 煙や','ekimae','大手','gourmet','居酒屋','kemuri_ya'),
('s473083b7','沖縄料理 南風 ぱいかじ','ekimae','中央','gourmet','居酒屋','okinawaryouripaikazi'),
('s34c551c2','炭火焼の店 織々屋','ekimae','中央','gourmet','居酒屋',''),
('sa671fcff','石田屋','ekimae','大手','gourmet','居酒屋',''),
('sfa8fce77','越前鮮魚と炭火焼 炭と魚 福井駅前店','ekimae','中央','gourmet','寿司・海鮮','sumi.to.sakana'),
('s8942d76e','酒場 丸子','ekimae','中央','gourmet','居酒屋','sakaba_maruko'),
('s568c1b8b','酒季織々 旨い肴と和み酒 錦輝','ekimae','大手','gourmet','居酒屋','nishikifukui'),
('s799a6b23','飲み喰い処 和楽路','ekimae','中央','gourmet','居酒屋',''),
('scc22d7b3','骨付鳥、からあげ、ハイボール がブリチキン。 福井駅前店','ekimae','中央','gourmet','居酒屋','gabukichi_gaburichicken'),
('s0e47f167','魚のうまい店 寿司居酒屋 かんきち 福井駅前店','ekimae','大手','gourmet','寿司・海鮮','kankichi_291'),
('sf2bd41d7','魚六(ウオロック)','ekimae','中央','gourmet','寿司・海鮮','uorock291'),
('seb2a4480','鶏屋 塚田農場 福井駅前店','ekimae','中央','gourmet','居酒屋','fukui_tsukadanojo'),
('sa9f71617','串カツ田中 福井駅前店','ekimae','大手','gourmet','焼鳥・串','kushikatsu_tanaka'),
('sde4a6298','串カツ酒場 ナニワ屋 福井駅前店','ekimae','中央','gourmet','焼鳥・串',''),
('se898d0cb','炭・串焼 べんがら屋','ekimae','中央','gourmet','焼鳥・串',''),
('s5a9ab9f2','焼き鳥 八穴','ekimae','大手','gourmet','焼鳥・串','hachinoana_yakitori'),
('sebc25d2d','スナックおすみ','ekimae','中央','night','スナック・ラウンジ',''),
('s2a51afb8','G’sBAR 0821','ekimae','中央','night','スナック・ラウンジ',''),
('sdd4a89da','Santana','ekimae','中央','night','スナック・ラウンジ',''),
('sefb719c7','あずま','ekimae','手寄','night','スナック・ラウンジ',''),
('sd09a9257','どんどん','ekimae','中央','night','スナック・ラウンジ',''),
('sc2625260','バレッタ','ekimae','中央','night','スナック・ラウンジ',''),
('s326db697','パリジェンヌ','ekimae','中央','night','スナック・ラウンジ',''),
('s38f5773f','ミュージックスペース シューハウス','ekimae','中央','night','スナック・ラウンジ',''),
('s8c4f966a','笑殿','ekimae','中央','night','スナック・ラウンジ',''),
('sabb6da8c','紫苑','ekimae','中央','night','スナック・ラウンジ',''),
('s263b15fb','BAR 月下(バーげっか)','ekimae','中央','night','バー','gekka_fukui'),
('s3b14b9c6','Bistro&Bar Bono(ボーノ)','ekimae','中央','night','バー','foop.entertainment.service'),
('sd259ece0','バーこうみんかん','ekimae','中央','night','バー','kominkan2.0'),
('s3322a85d','ダーツ&キッチン BAD BIRDY(バッド バーディ)','ekimae','大手','night','バー','bad_birdy_fukui'),
('s4c8c15d7','ミワンソン','ekimae','中央','night','バー','miwanseong.cafe'),
('sba771388','浜町安文酒店','ekimae','中央','night','バー',''),
('s5e344923','ハイボール ビール おもてなし OSPITALITA(オスピタリタ)','ekimae','中央','night','バー','ospitalita_fukui'),
('sc9e51efe','たこ焼きバー たこパ','ekimae','中央','night','バー','takopa_fukui'),
('s5301b782','炭と肉。','ekimae','中央','gourmet','焼肉・肉料理','sumitoniku'),
('s49d8ac83','旬ふく食彩 よしな','ekimae','大手','gourmet','和食','yoshina_624'),
('s51b90fcf','くずし割烹 ぼんた','ekimae','中央','gourmet','和食',''),
('s804d5364','釣り人しまちゃん','ekimae','中央','gourmet','寿司・海鮮','tsuribito_shimachan'),
('s0663cb88','日々','ekimae','中央','gourmet','和食','hamamachi.hibi'),
('s4c9fd68e','味処 おたん','ekimae','中央','gourmet','和食',''),
('s5e1e30c7','CAFE & BAR PRONTO 福井駅前店','ekimae','中央','night','バー','pronto___official'),
('se36ce584','GINCHIYO','ekimae','中央','night','バー','ginchiyo_fukui'),
('s69548fc0','OUR BREWING TAPROOM','ekimae','中央','night','バー','ourbrewing'),
('sbad2abeb','The best space BAR FUKU','ekimae','中央','night','バー','t.b.s.barfuku'),
('s1c709fa5','eclat(エクラ)','ekimae','大手','night','バー','eclat__2023'),
('s8962fe8f','なごとん','ekimae','中央','night','バー',''),
('s1b2f1de2','パブおいち・深夜食堂','ekimae','中央','night','スナック・ラウンジ','nishikou'),
('sedf01bb3','歌謡喫茶 ユミ','ekimae','中央','night','バー','kayoukissa_yumi'),
('s8b4f09e0','福井屋台村','ekimae','日之出','night','バー','fukui_yataimura'),
('sd22f874a','オステリア ダ シルバーノ','ekimae','中央','night','バー','osteria_da_silvano_fukui'),
('s93af7e23','肉はナカノ','ekimae','中央','gourmet','焼肉・肉料理','nikuhanakano_minie'),
('s5f15823c','兄ん家','ekimae','大手','night','バー','kaisen343'),
('s4d946582','八兆屋駅の蔵 福井駅店','ekimae','中央','night','バー',''),
('sad14b649','越前魚問屋 蟹ヱ門','ekimae','中央','night','バー','kaniemon_minie'),
('s4357786e','やきとりの名門 秋吉 福井駅前店','ekimae','大手','night','バー',''),
('s4bb1b7bd','炭火焼鳥 鶏次','ekimae','中央','night','バー','sumibiyakitori_keiji'),
('s443e8c43','SIERRA MADRE','ekimae','中央','night','バー',''),
('s88f82896','WINE食堂 TAMAMIN13','ekimae','大手','night','バー','tamamisongjing'),
('s9d1bff03','ちょい呑み処 ババズ','ekimae','中央','night','バー','ba__buzz'),
('sd5219586','BAR HIDING PLACE','ekimae','中央','night','バー','bar_hiding_place'),
('s2e74fe26','BAR 堀川','ekimae','中央','night','バー',''),
('scd433ac6','Bar & Restaurant Blue Light Cafe','ekimae','中央','night','バー',''),
('s0d5a9f96','Bar UNCLE(アンクル)','ekimae','大手','night','バー',''),
('sbe1f85f1','CINEMA "street theater"','ekimae','中央','night','バー','cinema_fukui'),
('se76e2581','Craft Beer Bar アワタチ','ekimae','中央','night','バー','beer_awatachi'),
('s680aa43b','GIORNO Fukui,','ekimae','中央','night','バー','giorno_fukui'),
('s2f13d702','GOLF & DARTS BAR TRUMP','ekimae','大手','night','バー','trump_golfanddarts_bar'),
('s41006851','ODDS POKER ROOM','ekimae','中央','night','バー','odds_poker'),
('sfaf58ccf','Rum Fire(ラムファイヤー)','ekimae','中央','night','バー','fumfirefukui'),
('s6b4b3c83','SHIMA(シマ)','ekimae','中央','night','バー','shima_coffee_sake'),
('s304392ca','THE BAR 灯火','ekimae','大手','night','バー','bar_tomoshibi_fukui'),
('se613d0f1','おさけとワイン みずもと','ekimae','中央','night','バー','mizumoto_sake'),
('s8e6ca65b','アイリッシュバー Shelbourne(シェルボーン)','ekimae','中央','night','バー','shelbourne.ib'),
('s3f5afeee','アジアンランチビュッフェ','ekimae','中央','night','バー','courtyard_by_marriott_fukui'),
('s59aa7397','ワインバル ヴェレゾン','ekimae','大手','night','バー',''),
('s678fdcab','屋上BAR BRIDGE','ekimae','中央','night','バー',''),
('s1652a223','日本酒BAR Room','ekimae','中央','night','バー','beer_awatachi'),
('s2db8deed','わらび 福井駅前店','ekimae','中央','gourmet','居酒屋','izakaya_warabi'),
('s7abd063e','味とら','ekimae','大手','gourmet','居酒屋',''),
('s3e27348c','味の王様','ekimae','大手','gourmet','居酒屋','aji_ou'),
('s4fecae1c','味処 庄屋','ekimae','中央','gourmet','居酒屋','ajidokoro_syoya'),
('s4b7cca49','松田屋','ekimae','日之出','gourmet','居酒屋',''),
('sc37eaa46','味の清八','ekimae','中央','gourmet','焼鳥・串',''),
('s3005c9ff','焼肉ほるもんサンマルコ','katamachi','順化','gourmet','焼肉・肉料理',''),
('sbd3dd6a4','金福','katamachi','順化','gourmet','その他',''),
('s43b636a5','ぼてじゃこ福井片町店','katamachi','順化','gourmet','その他',''),
('s2ee77113','よしな片町店','katamachi','順化','gourmet','その他',''),
('se99600ad','山中','katamachi','順化','gourmet','その他',''),
('s18e7a90b','&Room','katamachi','順化','gourmet','その他',''),
('sa4f29e79','BANBAN','katamachi','順化','gourmet','その他',''),
('s317ffbcb','CLUB・Queen’s','katamachi','順化','night','スナック・ラウンジ',''),
('saa9ac2b9','CREAM','katamachi','順化','gourmet','その他',''),
('s91eefd77','ELAN','katamachi','順化','gourmet','その他',''),
('sc90cd7da','JagBAR','katamachi','順化','gourmet','その他',''),
('s65c28a30','JuGo','katamachi','順化','gourmet','その他',''),
('s867c97ed','LeapDay','katamachi','順化','gourmet','その他',''),
('s9e448f01','NewYork・ニューヨーク','katamachi','順化','gourmet','その他',''),
('s325178f0','RoseRed','katamachi','順化','gourmet','その他',''),
('sb7f6f7c1','Startin’','katamachi','順化','gourmet','その他',''),
('s59952785','TOYSBOX','katamachi','順化','gourmet','その他',''),
('s13061b4a','Yダッシュ','katamachi','順化','gourmet','その他',''),
('s14a917ce','abuku','katamachi','順化','gourmet','その他',''),
('s69a04e29','きぶね','katamachi','順化','gourmet','その他',''),
('s3a58059c','さなえ','katamachi','順化','gourmet','その他',''),
('sc84a2afd','その字 弐','katamachi','順化','gourmet','その他',''),
('s8c934cc7','そば茶屋まつき','katamachi','順化','gourmet','そば・うどん',''),
('se63cf918','とび田','katamachi','順化','gourmet','その他',''),
('s8486f4ff','どん茶屋御食事処','katamachi','順化','gourmet','その他',''),
('sbce0670a','みやぎ(宮妓)','katamachi','順化','gourmet','その他',''),
('s428d8297','アフロディーテ','katamachi','順化','gourmet','その他',''),
('sb6c24e6d','アミーチ','katamachi','順化','gourmet','その他',''),
('s8b37d3b4','アリーズバー','katamachi','順化','night','バー',''),
('s129ac94d','オー・ド・ヴィー','katamachi','順化','gourmet','その他',''),
('sd1150155','キュキュキュ','katamachi','順化','gourmet','その他',''),
('s331e2db6','キンヤ人情下町店','katamachi','順化','gourmet','その他',''),
('se2538d93','ゴードン','katamachi','順化','gourmet','その他',''),
('s19a22213','サンクチュアリ','katamachi','順化','gourmet','その他',''),
('sa617f4a1','ジェイ‐グローブ(J-globe)','katamachi','順化','gourmet','その他',''),
('sa0653b5f','ジェイ・グローブ','katamachi','順化','gourmet','その他',''),
('s048f70e3','スピークイージー','katamachi','順化','gourmet','その他',''),
('s849179f9','スペイン酒場エル・スール','katamachi','順化','gourmet','居酒屋',''),
('sa22c4fea','セナラ ジュテイ','katamachi','順化','gourmet','その他',''),
('s7046b5ce','セント・ジェームズ','katamachi','順化','gourmet','その他',''),
('sd3549282','ゼット','katamachi','順化','gourmet','その他',''),
('sc753a6df','ナイトイン季節風','katamachi','順化','gourmet','その他',''),
('s18c1203f','ナフナフ','katamachi','順化','gourmet','その他',''),
('s942993d8','ニュー淀','katamachi','順化','gourmet','その他',''),
('s73a7aa97','バッカス(BACCHUS)','katamachi','順化','gourmet','その他',''),
('s529f286d','パインズ・バー','katamachi','順化','night','バー',''),
('s537a8bd8','パラダイス','katamachi','順化','gourmet','その他',''),
('s78ce1532','プラチナム(PLATINUM)','katamachi','順化','gourmet','その他',''),
('sbc48c481','プロペラ','katamachi','順化','gourmet','その他',''),
('s51a24057','ボギーズバー','katamachi','順化','night','バー',''),
('s1cb86e25','マリブ(MALIBU)','katamachi','順化','gourmet','その他',''),
('sb838dce9','マルシェ','katamachi','順化','gourmet','その他',''),
('sa15735b1','ミムロ','katamachi','順化','gourmet','その他',''),
('s3d8d843f','メリージェーン','katamachi','順化','gourmet','その他',''),
('s7783a4ce','レオン','katamachi','順化','gourmet','その他',''),
('s336d8d89','レディースマーケット','katamachi','順化','gourmet','その他',''),
('s88f1a01b','ヴァンテレーヌ','katamachi','順化','gourmet','その他',''),
('saef08cb2','上野屋','katamachi','順化','gourmet','その他',''),
('see5ef528','亜米利館カツレツ店','katamachi','順化','gourmet','その他',''),
('s093086ca','凛','katamachi','順化','gourmet','その他',''),
('s5cea63aa','十六夜','katamachi','順化','gourmet','その他',''),
('sa56c9cfc','女子寮/福井店','katamachi','順化','gourmet','その他',''),
('s75f6146a','始皇帝','katamachi','順化','gourmet','その他',''),
('s86a343d3','山根木','katamachi','順化','gourmet','その他',''),
('s1c0f2384','職人二人','katamachi','順化','gourmet','その他',''),
('sa118b8fa','花音','katamachi','順化','gourmet','その他',''),
('s0918ef91','香華堂','katamachi','順化','gourmet','その他',''),
('s3e2719c8','高島広幸','katamachi','順化','gourmet','その他',''),
('s8c75506c','ルアンタイ','katamachi','順化','gourmet','アジア・各国料理',''),
('s60b5526c','宗家','katamachi','順化','gourmet','アジア・各国料理',''),
('s3ae3fb1c','白頭山','katamachi','順化','gourmet','アジア・各国料理',''),
('s359b50a6','豚屋','katamachi','順化','gourmet','アジア・各国料理',''),
('sea1c91f9','韓国食堂mukuge','katamachi','順化','gourmet','アジア・各国料理',''),
('s2da5446a','なかだ','katamachi','順化','gourmet','イタリアン・フレンチ',''),
('s2a539d8e','26ice','katamachi','順化','gourmet','カフェ・スイーツ','26ice.fukui'),
('sf0cd82ef','ミルヒビカフェ','katamachi','順化','gourmet','カフェ・スイーツ',''),
('sb037cd70','YUKI LEIN','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s45b60eaa','アスワン','katamachi','順化','gourmet','カフェ・スイーツ',''),
('se3ea25db','ウィーン','katamachi','順化','gourmet','カフェ・スイーツ',''),
('saeef5c36','カフェ 点','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s773dd354','コーヒーハウスコナン','katamachi','順化','gourmet','カフェ・スイーツ',''),
('sb41499ea','パリス','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s067aec81','千恵','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s83175030','喫茶 カファ・ブンナ','katamachi','順化','gourmet','カフェ・スイーツ',''),
('sd65b6156','巴奈麻','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s2554e909','珈琲所','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s8909b195','道安','katamachi','順化','gourmet','カフェ・スイーツ',''),
('sb354a49f','カフェ アンパサンド','katamachi','順化','gourmet','カフェ・スイーツ','ampersand_tommy'),
('sd4136377','パティスリー オリヴィエール','katamachi','順化','gourmet','カフェ・スイーツ','oliviere_'),
('s621d80d0','喫茶 SEVEN’s(セブンズ)','katamachi','順化','gourmet','カフェ・スイーツ','sevens359'),
('s5c45398c','カラオケ ビッグエコー 片町店','katamachi','順化','gourmet','その他',''),
('s7349674b','おはぎや 小林','katamachi','順化','gourmet','カフェ・スイーツ','ohagiyakoba'),
('scf6e4f22','ティラミス専門店 トラットリア トマト','katamachi','順化','gourmet','イタリアン・フレンチ','trattoria.tomato'),
('s839626e6','soba 月山','katamachi','順化','gourmet','そば・うどん','sobagezan'),
('sd178765f','つるきそば 佐佳枝支店','katamachi','順化','gourmet','そば・うどん',''),
('sf213de58','手打ひと筋 さのや','katamachi','順化','gourmet','そば・うどん',''),
('s1bb93f7c','越前蕎麦dining 櫻庭(さくらば)','katamachi','順化','gourmet','そば・うどん','echizensoba.dining_sakuraba'),
('s95a2236e','天籠(てんかご)','katamachi','順化','gourmet','そば・うどん','tenkago.myo'),
('s3d5f6c4e','Mooma(モーマ)','katamachi','順化','gourmet','そば・うどん','mooma5745'),
('s839626e6','こんなパスタが食べたくて','katamachi','順化','gourmet','イタリアン・フレンチ','konpasu_291'),
('s46f9af51','夕炊屋 fudo(ゆうげや ふど)','katamachi','順化','gourmet','イタリアン・フレンチ','10nin10color'),
('sb77fbccd','GYOZA kitchen 信正(しんせい)','katamachi','順化','gourmet','ラーメン',''),
('s1133ed50','炭火焼き 赤身・じびえ・ほるもん どがいし','katamachi','順化','gourmet','洋食','dogaisi_291'),
('sb1e3455d','おばんざい家 たかはし','katamachi','順化','gourmet','洋食','obannzai.takahashi'),
('s4a5a5bd6','かき乃木','katamachi','順化','gourmet','洋食','kakinoki_fukui'),
('s1c2c0c33','陶酔 灯り','katamachi','順化','gourmet','洋食','tousui_akari'),
('s3e300401','めしや しの﨑','katamachi','順化','gourmet','居酒屋','meshiya.shinozaki'),
('s153fe11b','料理屋 みや﨑','katamachi','順化','gourmet','居酒屋',''),
('sfd765333','歳時鹿火(さいじろくか)','katamachi','順化','gourmet','洋食','saiji_rokuka_official'),
('s498b4096','四季ごはん おやびんHOUSE','katamachi','順化','gourmet','居酒屋',''),
('s3d95a6ec','晩酌 ちろり','katamachi','順化','gourmet','居酒屋',''),
('sa4c1eaa7','酒彩 雁ぐらし(かりぐらし)','katamachi','順化','gourmet','居酒屋','karigurasi.fukui'),
('sa9bfddef','鉄板焼肉酒場 まねき屋','katamachi','順化','gourmet','焼肉・肉料理','manekiya320'),
('sf098584a','鶏料理居酒屋 トリノトリコ','katamachi','順化','gourmet','居酒屋','tori_no_torico_fukui'),
('s578a39f9','GYUGYU焼肉 七福(しちふく)','katamachi','順化','gourmet','焼肉・肉料理','yakiniku_shichifuku'),
('s510f1923','OHAKO','katamachi','順化','gourmet','焼肉・肉料理','ohako_fukui'),
('s73376292','あぶり牧場 あん','katamachi','順化','gourmet','焼肉・肉料理',''),
('sdfb60a18','ジンギスカン鮮(せん)','katamachi','順化','gourmet','焼肉・肉料理','sen_hituji0411'),
('sf45ad5e8','和田○商店','katamachi','順化','gourmet','焼肉・肉料理','akamiwadamaru'),
('s6cdaa3b7','焼き肉家 山本','katamachi','順化','gourmet','焼肉・肉料理',''),
('scc8615a6','焼肉 うしのね','katamachi','順化','gourmet','焼肉・肉料理','yakiniku__usinone'),
('s8a365757','牛匠・人時(ぎゅうしょう・ひととき)','katamachi','順化','gourmet','焼肉・肉料理','gyuushou.hitotoki'),
('sc1b4dfb9','Yellow(イエロー)','katamachi','順化','gourmet','焼肉・肉料理','yellow_spice_labo'),
('sa9f5da48','遊留里楽酒場 みとん(ゆるりらさかば みとん)','katamachi','順化','gourmet','焼鳥・串','miton0521'),
('s6b32962a','暖らん酒場 八や(はちや)','katamachi','順化','gourmet','居酒屋','hachiya.fukui'),
('sd99cb14d','華汀園','katamachi','順化','gourmet','中華',''),
('se8ff9864','いちろくらーめん 片町本通り店','katamachi','順化','gourmet','ラーメン','ichiroku_ramen'),
('sed22126a','がんこ2代目ラーメン','katamachi','順化','gourmet','ラーメン',''),
('s1b9f88a4','上海亭','katamachi','順化','gourmet','ラーメン',''),
('sc5f60290','多弐家','katamachi','順化','gourmet','ラーメン',''),
('s7ae7c6d4','拉麺家 とんとん','katamachi','順化','gourmet','ラーメン',''),
('sc3eb5591','長宝亭','katamachi','順化','gourmet','ラーメン',''),
('sb1f352b6','きのこしゃぶしゃぶ料理 栄福祥','katamachi','順化','gourmet','中華',''),
('sc97f1ff9','ギョウザ・ラーメン 彩菜','katamachi','順化','gourmet','ラーメン',''),
('s185970a0','中国本場料理 福井源','katamachi','順化','gourmet','中華',''),
('s3cc39b54','タコスのある人生 La Vida Tacos','katamachi','順化','gourmet','アジア・各国料理','la_vida_tacos'),
('s7dfb67d8','五味五色 じゅじゅむむ','katamachi','順化','gourmet','アジア・各国料理',''),
('sa4e65b58','地中海バル OTTO','katamachi','順化','gourmet','居酒屋',''),
('s9a4c9676','韓国料理 ペゴパ','katamachi','順化','gourmet','アジア・各国料理','pegopa1115'),
('se272263a','韓国風鉄板焼・鍋工房 鉄鍋屋','katamachi','順化','gourmet','アジア・各国料理','tetunabeya'),
('s15dd4dc1','にく家 うましか','katamachi','順化','gourmet','焼肉・肉料理','nikuya.umashika'),
('s1afd7ae6','炭火焼肉 春来','katamachi','順化','gourmet','焼肉・肉料理','cut_haluku'),
('sa7747358','焼き肉 豊 -YUTAKA-','katamachi','順化','gourmet','焼肉・肉料理','yakinikuyutaka5296'),
('sc037c175','焼肉 うし牛','katamachi','順化','gourmet','焼肉・肉料理',''),
('sab38c052','焼肉かわだ','katamachi','順化','gourmet','焼肉・肉料理','yakiniku_kawada'),
('s9e7b72ab','福昌園','katamachi','順化','gourmet','焼肉・肉料理',''),
('sd6aef52a','若狭牛と個室焼肉 和田○商店','katamachi','順化','gourmet','焼肉・肉料理','wadamaru_shouten'),
('saad46e0a','あげます','katamachi','順化','gourmet','和食',''),
('sae2000ca','あらかわ','katamachi','順化','gourmet','和食',''),
('s48972b45','いっすんぼうし','katamachi','順化','gourmet','和食',''),
('s8dc35a91','おきな','katamachi','順化','gourmet','和食',''),
('saeacb1d2','お柳','katamachi','順化','gourmet','和食',''),
('s66fca2f8','かっちゃん','katamachi','順化','gourmet','和食',''),
('s554ec16c','じん','katamachi','順化','gourmet','和食',''),
('saa7a0452','すし善','katamachi','順化','gourmet','寿司・海鮮',''),
('s456938cd','だるま鮨','katamachi','順化','gourmet','寿司・海鮮',''),
('s5eff3ef1','ちか','katamachi','順化','gourmet','和食',''),
('s669c8e05','でん助','katamachi','順化','gourmet','和食',''),
('s75e833a5','ときわ','katamachi','順化','gourmet','和食',''),
('s0f000893','とり新','katamachi','順化','gourmet','和食',''),
('sc17c8de0','みよしの','katamachi','順化','gourmet','和食',''),
('sf2d60390','やました','katamachi','順化','gourmet','和食',''),
('s2b34ab87','ゆずりは','katamachi','順化','gourmet','和食',''),
('sd54c2e62','佳納','katamachi','順化','gourmet','和食',''),
('sb1475d1a','初味寿司呉服町店','katamachi','順化','gourmet','寿司・海鮮',''),
('s68b63729','吉田寿司本店','katamachi','順化','gourmet','寿司・海鮮',''),
('sd83b39aa','味とまごころ 八勢','katamachi','順化','gourmet','和食',''),
('s0509d1dd','咲咲','katamachi','順化','gourmet','和食',''),
('s3d24ec22','咲良・味工房','katamachi','順化','gourmet','和食',''),
('sf168fd4c','大仏そば','katamachi','順化','gourmet','そば・うどん',''),
('s8a743fa5','大番','katamachi','順化','gourmet','和食',''),
('sbde5e1bd','大西','katamachi','順化','gourmet','和食',''),
('s431e6f4f','寿し保','katamachi','順化','gourmet','和食',''),
('scabe4132','寿ゞ屋','katamachi','順化','gourmet','和食',''),
('s17d70843','寿司道楽','katamachi','順化','gourmet','寿司・海鮮',''),
('s24f4e4d6','文ちん','katamachi','順化','gourmet','和食',''),
('sb8320adf','文室','katamachi','順化','gourmet','和食',''),
('saae6d4a1','桜寿し本店','katamachi','順化','gourmet','和食',''),
('sa73bcf7b','楽','katamachi','順化','gourmet','和食',''),
('sd62d598c','波の華','katamachi','順化','gourmet','和食',''),
('sd27993d8','焼鳥大将片町店','katamachi','順化','gourmet','焼鳥・串',''),
('s776b5062','田畑清正','katamachi','順化','gourmet','和食',''),
('s4ff26fa9','番晩亭','katamachi','順化','gourmet','和食',''),
('sacfc6c86','磯季節料理店','katamachi','順化','gourmet','和食',''),
('s9b859a1a','粂ちゃん','katamachi','順化','gourmet','和食',''),
('s3ab92ad1','紫川','katamachi','順化','gourmet','和食',''),
('sd10debe6','細庵','katamachi','順化','gourmet','和食',''),
('sf2924ed3','茶がま','katamachi','順化','gourmet','和食',''),
('s36895a99','茶太片町分店','katamachi','順化','gourmet','和食',''),
('s0160358d','葉月','katamachi','順化','gourmet','和食',''),
('s7b889572','金龍','katamachi','順化','gourmet','和食',''),
('s76f1c89a','釜めし 煮込うどん 王将','katamachi','順化','gourmet','そば・うどん',''),
('se0f1621a','そば重','katamachi','順化','gourmet','そば・うどん',''),
('sa7e97ff0','ポポー軒','katamachi','順化','gourmet','そば・うどん',''),
('s8a5e585e','佐佳枝亭','katamachi','順化','gourmet','そば・うどん',''),
('s7069add9','越前そば 片桐','katamachi','順化','gourmet','そば・うどん',''),
('s786a51b5','お好み焼き 富士美','katamachi','順化','gourmet','和食',''),
('sbe378692','くくる','katamachi','順化','gourmet','和食',''),
('sdb3613c2','とんかつ割烹 一えい','katamachi','順化','gourmet','焼肉・肉料理',''),
('sbbbe1e11','とんかつ割烹 谷口や','katamachi','順化','gourmet','焼肉・肉料理',''),
('sd1a4261a','ヨーロッパ軒総本店','katamachi','順化','gourmet','焼肉・肉料理','yoroppakensouhonten'),
('s891aae82','しゃぶ玄','katamachi','順化','gourmet','和食',''),
('s8f165711','TSUGI(ツギ)','katamachi','順化','gourmet','和食','tsugi_19h'),
('s217fefa2','ご馳走 純','katamachi','順化','gourmet','和食','gochisou_jun'),
('sb3c17def','はちまん','katamachi','順化','gourmet','和食','hach.imann'),
('s70a7f9ac','まちの都 machi no miyaco','katamachi','順化','gourmet','和食','machino_miyaco'),
('s71d8b75b','割烹 木屋町 Kiyamachi','katamachi','順化','gourmet','和食',''),
('s2c63e16c','創作小鉢 あけると','katamachi','順化','gourmet','和食','_akeruto'),
('sda2640e6','味処 源太','katamachi','順化','gourmet','和食','genta_0924'),
('se7bea929','和食ダイニング 柳月亭','katamachi','順化','gourmet','和食','ryugetsutei'),
('se4d8d95e','和食処 山海','katamachi','順化','gourmet','和食',''),
('sceb510ce','御料理 味真乃','katamachi','順化','gourmet','和食',''),
('sdd37cf56','旬彩家 樹','katamachi','順化','gourmet','和食',''),
('s7852adf3','鮮','katamachi','順化','gourmet','和食','sen_hituji0411'),
('s2f101f89','天ぷら 天春','katamachi','順化','gourmet','和食',''),
('s868ded4e','天菊','katamachi','順化','gourmet','和食',''),
('s5621c2d4','魚菜園','katamachi','順化','gourmet','寿司・海鮮',''),
('s9831a6a8','すし吉正','katamachi','順化','gourmet','寿司・海鮮','sushi_yoshimasa'),
('s1a3398e9','寿し吉田','katamachi','順化','gourmet','寿司・海鮮','sushi_yoshida'),
('sde6ccd42','寿司・割烹・ふぐ料理 鮨長','katamachi','順化','gourmet','寿司・海鮮','sushicho2018'),
('sb9193d58','鮨 凌','katamachi','順化','gourmet','寿司・海鮮','sushi__ryo'),
('sa95302ef','鮨 吉幸','katamachi','順化','gourmet','寿司・海鮮','sushi_kiccou'),
('s786ae940','鮨光','katamachi','順化','gourmet','寿司・海鮮','sushimitsu_fukui'),
('sff834a3d','鮨処 海月','katamachi','順化','gourmet','寿司・海鮮','kurage.666'),
('saac1d3c0','お料理 いわし屋','katamachi','順化','gourmet','和食','iwashiya_'),
('s9c10f23f','のちのち','katamachi','順化','gourmet','和食',''),
('s1a97bd84','日本料理 やなぎ町','katamachi','順化','gourmet','和食','yanagimachi_honten'),
('sb7abccd5','燻鮎 KUNTEN','katamachi','順化','gourmet','和食',''),
('s4fe7e7c6','田中マネの食堂','katamachi','順化','gourmet','和食',''),
('se5018641','CREPE BON','katamachi','順化','gourmet','カフェ・スイーツ','crepe.bon'),
('se5af507c','Spice Bar QUILT HOUSE(キルトハウス)','katamachi','順化','night','バー','spicebarquilthouse'),
('s3f80db21','THREE TIMES COFFEE','katamachi','順化','gourmet','カフェ・スイーツ','threetimescoffee_fukui'),
('s6da86f0c','flat kitchen','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s55741195','カフェと雑貨 古民家35','katamachi','順化','gourmet','カフェ・スイーツ','kominka35'),
('s8e705810','京町Y・Yカフェ','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s3c4c6f9b','CIGAR&CAFE 臼井煙草倶楽部','katamachi','順化','gourmet','カフェ・スイーツ',''),
('sd90895ec','異邦人倶楽部','katamachi','順化','gourmet','カフェ・スイーツ',''),
('sbe6b898a','yokoyama別亭','katamachi','順化','gourmet','居酒屋',''),
('s307bfba9','炭火串焼千串屋','katamachi','順化','gourmet','焼鳥・串',''),
('s367eb072','あげはら','katamachi','順化','gourmet','居酒屋',''),
('s9663f919','あんぶん春','katamachi','順化','gourmet','居酒屋',''),
('s069fd0ed','うまいもの屋敷 忍者','katamachi','順化','gourmet','居酒屋',''),
('sead7d63c','かっぱ','katamachi','順化','gourmet','居酒屋',''),
('s3a654b14','かんちゃん','katamachi','順化','gourmet','居酒屋',''),
('s639da5a4','ききょう','katamachi','順化','gourmet','居酒屋',''),
('scff2bc52','しまだ','katamachi','順化','gourmet','居酒屋',''),
('s7f29a26a','てらや','katamachi','順化','gourmet','居酒屋',''),
('s73927a00','とも貴','katamachi','順化','gourmet','居酒屋',''),
('s4d5c82b7','のむ喜','katamachi','順化','gourmet','居酒屋',''),
('s2e041204','はせじ','katamachi','順化','gourmet','居酒屋',''),
('s0880190e','ひいきや','katamachi','順化','gourmet','居酒屋',''),
('s551ea6ef','ひろちゃん','katamachi','順化','gourmet','居酒屋',''),
('se937e33f','まき','katamachi','順化','gourmet','居酒屋',''),
('s5ba59f5d','まんぼう','katamachi','順化','gourmet','居酒屋',''),
('s67514f4c','やきとり 八や','katamachi','順化','gourmet','焼鳥・串',''),
('s13adad43','やき屋','katamachi','順化','gourmet','居酒屋',''),
('s6b9c1233','よしむら 割烹 鍋物','katamachi','順化','gourmet','居酒屋',''),
('s0862e47a','ろばた焼 弥吉 片町店','katamachi','順化','gourmet','居酒屋',''),
('s74ee4314','シェ・シーマ(CHEZCIMA)','katamachi','順化','gourmet','居酒屋',''),
('s6a580b5b','ソウル','katamachi','順化','gourmet','居酒屋',''),
('scc2be637','プーケット','katamachi','順化','gourmet','居酒屋',''),
('s5d767b0d','ムッ酒','katamachi','順化','gourmet','居酒屋',''),
('sfde442cb','丸駒','katamachi','順化','gourmet','居酒屋',''),
('sf41e4a08','八州屋','katamachi','順化','gourmet','居酒屋',''),
('s748ae3f8','友膳','katamachi','順化','gourmet','居酒屋',''),
('s39d888e4','吟遊','katamachi','順化','gourmet','居酒屋',''),
('s2cb6061a','呑むきんちゃん','katamachi','順化','gourmet','居酒屋',''),
('sc9ebaa56','和ぼうず','katamachi','順化','gourmet','居酒屋',''),
('s0fe72c15','寿し割烹 八重','katamachi','順化','gourmet','居酒屋',''),
('sb18e43e4','居酒屋いちべえ','katamachi','順化','gourmet','居酒屋',''),
('s74e6c803','居酒屋とっさん','katamachi','順化','gourmet','居酒屋',''),
('s2dc17270','居酒屋花や','katamachi','順化','gourmet','居酒屋',''),
('sb0239e11','市','katamachi','順化','gourmet','居酒屋',''),
('sd0bcb41c','平八','katamachi','順化','gourmet','居酒屋',''),
('sfed117ef','春月','katamachi','順化','gourmet','居酒屋',''),
('s689532b4','来神','katamachi','順化','gourmet','居酒屋',''),
('s940f2085','武','katamachi','順化','gourmet','居酒屋',''),
('s93d5500a','民俗村','katamachi','順化','gourmet','居酒屋',''),
('s1cb2f135','汐彩','katamachi','順化','gourmet','居酒屋',''),
('s33a2d7c3','洋食居酒屋クオーレ','katamachi','順化','gourmet','居酒屋',''),
('s96659a24','直','katamachi','順化','gourmet','居酒屋',''),
('sf451c6fc','福義','katamachi','順化','gourmet','居酒屋',''),
('s30aec0c7','福菜福酒 師門','katamachi','順化','gourmet','居酒屋',''),
('sd6b4db8b','竹生','katamachi','順化','gourmet','居酒屋',''),
('sac848a19','美ちゃん','katamachi','順化','gourmet','居酒屋',''),
('s4f6e9220','翠翔 片町店','katamachi','順化','gourmet','居酒屋',''),
('scbb2582c','花や片町店','katamachi','順化','gourmet','居酒屋',''),
('se8215640','菜彩亭','katamachi','順化','gourmet','居酒屋',''),
('s3295a40a','菜遊季','katamachi','順化','gourmet','居酒屋',''),
('s34a51090','越の国つた屋','katamachi','順化','gourmet','居酒屋',''),
('sed552032','遊月家','katamachi','順化','gourmet','居酒屋',''),
('s11b4c972','遊月家参百圓食堂','katamachi','順化','gourmet','居酒屋',''),
('s0cead092','錦','katamachi','順化','gourmet','居酒屋',''),
('s0c35cc80','食・酒野尻','katamachi','順化','gourmet','居酒屋',''),
('s600531b2','魚義','katamachi','順化','gourmet','寿司・海鮮',''),
('s74326fb5','ペントラ・ベーネ(Pentola・Bene)','katamachi','順化','gourmet','洋食',''),
('s10ab3b3c','レストランル・ラパン','katamachi','順化','gourmet','カフェ・スイーツ',''),
('s41a13a27','和洋創菜 豆や','katamachi','順化','gourmet','洋食',''),
('s3c52bf29','Spuntino (スプンティーノ)','katamachi','順化','gourmet','イタリアン・フレンチ','spuntino_italiano'),
('s048a4b39','伊食堂 Arancia','katamachi','順化','gourmet','イタリアン・フレンチ','arancia_2008'),
('s411e7792','オニク☆パラダイス','katamachi','順化','gourmet','焼肉・肉料理','nikupara29'),
('scd7e2e2c','ステーキ 鐵船','katamachi','順化','gourmet','焼肉・肉料理',''),
('s2000f203','ステーキハウス アオヤマ','katamachi','順化','gourmet','焼肉・肉料理',''),
('sc3b983cf','ステーキハウス キタジマ','katamachi','順化','gourmet','焼肉・肉料理',''),
('s0e593b77','レストラン バンボッシュ・ド・ヤマ','katamachi','順化','gourmet','イタリアン・フレンチ',''),
('s07d1f1b5','ワインと旬の料理の店 ミスター・デ・ヴ','katamachi','順化','gourmet','イタリアン・フレンチ',''),
('s19cddc39','欧風割烹 北欧','katamachi','順化','gourmet','イタリアン・フレンチ',''),
('s4bb210af','洋食堂 yousyokudou','katamachi','順化','gourmet','イタリアン・フレンチ','yoshoku_do114'),
('s1ab1d3c7','VIP Amon','katamachi','順化','gourmet','洋食',''),
('s43f04cd5','レストラン クレドール','katamachi','順化','gourmet','洋食',''),
('se336a944','寿司政','katamachi','順化','gourmet','寿司・海鮮','sushimasa_fukui'),
('s19b5bd45','しらさきホルモン','katamachi','順化','gourmet','焼肉・肉料理',''),
('s3b892d5d','ひばち','katamachi','順化','gourmet','焼肉・肉料理',''),
('sc0f46936','イガネ','katamachi','順化','gourmet','焼肉・肉料理',''),
('sd1e97e3c','焼肉星香園','katamachi','順化','gourmet','焼肉・肉料理',''),
('s3112b1c6','牛牛','katamachi','順化','gourmet','焼肉・肉料理',''),
('s9d3e8d07','てがるそば','katamachi','順化','gourmet','そば・うどん',''),
('s3ad2c6e9','越前そば 見吉屋','katamachi','順化','gourmet','そば・うどん',''),
('s6b5dd69d','割烹間海','katamachi','順化','gourmet','寿司・海鮮',''),
('s803c1518','親玉菓舗の碌寶焼','katamachi','順化','gourmet','その他','oyadama32028'),
('s6aaab873','錦梅堂','katamachi','順化','gourmet','その他',''),
('s6af60179','のんちゃん','katamachi','順化','gourmet','居酒屋',''),
('s4eda15bf','和食と地酒 本伊勢','katamachi','順化','gourmet','居酒屋',''),
('s2c32a5fc','居酒屋 えんの樹','katamachi','順化','gourmet','居酒屋',''),
('s19cda020','居酒屋 ひっぱり凧','katamachi','順化','gourmet','居酒屋',''),
('s9b01884b','想作居酒屋 一ふじ','katamachi','順化','gourmet','居酒屋',''),
('s072e3506','越前の幸と喜びの酒 前田屋いちりん','katamachi','順化','gourmet','居酒屋',''),
('sa72bd449','越前中華 花ひなたに咲く','katamachi','順化','gourmet','居酒屋','hanahinatanisaku'),
('s5e600582','酒肴 コブ','katamachi','順化','gourmet','居酒屋',''),
('sab1e5a39','食彩DINING 神無月 想い出','katamachi','順化','gourmet','居酒屋',''),
('sedc2651c','食彩酒楽 いち陽','katamachi','順化','gourmet','居酒屋',''),
('sdf3329c1','やきとり ごとう','katamachi','順化','gourmet','焼鳥・串',''),
('s6d6116f8','串揚げ処 㐂寿','katamachi','順化','gourmet','焼鳥・串',''),
('s0d8defce','鳥匠 あさぎり','katamachi','順化','gourmet','焼鳥・串','asagirifukui'),
('sd4174d96','CLUB Risel','katamachi','順化','night','スナック・ラウンジ',''),
('s47fedf50','EAST','katamachi','順化','night','スナック・ラウンジ',''),
('sa1f6802f','Rui','katamachi','順化','night','スナック・ラウンジ',''),
('s45a75088','club cherir','katamachi','順化','night','スナック・ラウンジ',''),
('se06c2d52','club 蓮','katamachi','順化','night','スナック・ラウンジ',''),
('s446a7e60','ひな乃','katamachi','順化','night','スナック・ラウンジ',''),
('sf8bc563c','スナックJm','katamachi','順化','night','スナック・ラウンジ','snack_jm_1124_'),
('sfb9bf709','スナックKARA','katamachi','順化','night','スナック・ラウンジ',''),
('sf560f241','スナックあれから','katamachi','順化','night','スナック・ラウンジ',''),
('s558ff87c','スナック・ロシア','katamachi','順化','night','スナック・ラウンジ',''),
('sbd388289','ナイトラウンジ恋華片町','katamachi','順化','night','スナック・ラウンジ',''),
('s323a99e4','ラウンジステラ','katamachi','順化','night','スナック・ラウンジ',''),
('sb255c48c','リッカー(Riccar)','katamachi','順化','night','スナック・ラウンジ',''),
('s8e8bde68','Anri','katamachi','順化','night','スナック・ラウンジ',''),
('s90e9520e','Belle vie~ベルヴィー~','katamachi','順化','night','スナック・ラウンジ','bellevie62288'),
('sf7255b5d','FRIEND BAR CURIOUS','katamachi','順化','night','スナック・ラウンジ',''),
('sb100728b','I♡DABAO','katamachi','順化','night','スナック・ラウンジ',''),
('s97591a2d','JIGURO','katamachi','順化','night','スナック・ラウンジ',''),
('s8360d520','KARAOKE BAR NOAH','katamachi','順化','night','スナック・ラウンジ','noah_keirin'),
('s0f2c64c6','KOBAR','katamachi','順化','night','スナック・ラウンジ',''),
('s6f213bdc','LesoUrIre','katamachi','順化','night','スナック・ラウンジ',''),
('sfff10c76','Lounge Connection','katamachi','順化','night','スナック・ラウンジ',''),
('s10174fda','Luxe','katamachi','順化','night','スナック・ラウンジ',''),
('s44f5407f','More~モア~','katamachi','順化','night','スナック・ラウンジ',''),
('sbe58fd4d','NEGUS.','katamachi','順化','night','スナック・ラウンジ',''),
('s50cf4f21','OG-ChinaTown','katamachi','順化','night','スナック・ラウンジ',''),
('s74c77dce','SMILeeeS~スマイリーズ~','katamachi','順化','night','スナック・ラウンジ',''),
('s517a1da8','cafe&bar NABO','katamachi','順化','night','スナック・ラウンジ',''),
('sb85bc640','momo','katamachi','順化','night','スナック・ラウンジ',''),
('s3223ff06','musa','katamachi','順化','night','スナック・ラウンジ',''),
('s28f504d9','mystere','katamachi','順化','night','スナック・ラウンジ',''),
('s03ef00a4','vivian. (ビビアンドット)','katamachi','順化','night','スナック・ラウンジ',''),
('sb31dd628','はてな','katamachi','順化','night','スナック・ラウンジ',''),
('sf9344bdf','やすらぎ','katamachi','順化','night','スナック・ラウンジ',''),
('sbfb74d02','アプリコット','katamachi','順化','night','スナック・ラウンジ',''),
('s2cc7c925','カラオケスナック あざみ','katamachi','順化','night','スナック・ラウンジ',''),
('s237f50b1','カラオケバー LP','katamachi','順化','night','スナック・ラウンジ','karaoke_bar_lp'),
('sb7a58119','スナック さくら','katamachi','順化','night','スナック・ラウンジ',''),
('s23a91273','スナック せせらぎ','katamachi','順化','night','スナック・ラウンジ',''),
('s77c70ced','スナック なつこ','katamachi','順化','night','スナック・ラウンジ',''),
('saa4af146','スナック ぴーち','katamachi','順化','night','スナック・ラウンジ',''),
('sf5fcc1f6','スナック みやま','katamachi','順化','night','スナック・ラウンジ',''),
('sc491f560','スナック アーバン','katamachi','順化','night','スナック・ラウンジ',''),
('s95a14250','スナック ニューりんご','katamachi','順化','night','スナック・ラウンジ',''),
('sc03920e5','スナック ラクシャリィ','katamachi','順化','night','スナック・ラウンジ',''),
('sca529f69','スナック 五十八','katamachi','順化','night','スナック・ラウンジ',''),
('s3d6b9ac6','スナック 女帝','katamachi','順化','night','スナック・ラウンジ',''),
('s0d4c2b03','スナック 真利倫','katamachi','順化','night','スナック・ラウンジ',''),
('sdc8ff442','スナック 華','katamachi','順化','night','スナック・ラウンジ',''),
('s5ac214f1','ナイトイン アップルハウス','katamachi','順化','night','スナック・ラウンジ',''),
('sa0f6fc15','マリリン','katamachi','順化','night','スナック・ラウンジ',''),
('s94c8b70c','ラウンジ たちばな','katamachi','順化','night','スナック・ラウンジ',''),
('s5f5f7aae','ラブ','katamachi','順化','night','スナック・ラウンジ',''),
('s13b3be9b','大連','katamachi','順化','night','スナック・ラウンジ',''),
('s64ce2ef3','妖かし','katamachi','順化','night','スナック・ラウンジ',''),
('s3aee8f03','燻(いぶし)','katamachi','順化','night','スナック・ラウンジ','eves.fukui'),
('sb89f1b9d','紗羅','katamachi','順化','night','スナック・ラウンジ',''),
('s89f5ddc6','旬菜美酒 サスケ','katamachi','順化','night','バー',''),
('s75b204ce','BAR 222','katamachi','順化','night','バー',''),
('s580b39a6','BAR GROWP.','katamachi','順化','night','バー',''),
('s3dcde339','BAR Rainbow st.','katamachi','順化','night','バー',''),
('s7f821ec7','BAR Z','katamachi','順化','night','バー',''),
('se6fde3e7','BAR primo','katamachi','順化','night','バー',''),
('se5d55e8b','BAR ぐーちょきぱー','katamachi','順化','night','バー',''),
('sa49785fb','BAR・SEA','katamachi','順化','night','バー',''),
('sa9990c09','Bar 018','katamachi','順化','night','バー',''),
('sd05db204','Bar STELA','katamachi','順化','night','バー',''),
('s45688cec','DON','katamachi','順化','night','バー',''),
('s4d2b9604','EIGHT~Infinity Room~','katamachi','順化','night','バー',''),
('s09b193a2','Giorno','katamachi','順化','night','バー',''),
('sf4df3742','LC','katamachi','順化','night','バー',''),
('s2116ea95','Lounge BIDEN','katamachi','順化','night','スナック・ラウンジ',''),
('s8368bd33','PAPILLON','katamachi','順化','night','バー',''),
('s4e39d3e7','Party`s Bar BeReTTa','katamachi','順化','night','バー',''),
('s2d4af826','dining cafe ヴィアーレ・ナフ','katamachi','順化','night','バー',''),
('s53db608a','ゆる八','katamachi','順化','night','バー',''),
('sad7bee81','ホリチャン','katamachi','順化','night','バー',''),
('s0f74b085','メリエンダ・バール DESPERADO','katamachi','順化','night','バー',''),
('sdaebc4f2','suits AMUSEMENT BAR(スーツアミューズメントバー)福井店','katamachi','順化','night','バー','suits__bar'),
('s4899be09','ARTIST BAR B(アーティストバービー)','katamachi','順化','night','バー','artist.bar.b'),
('s8eb58b22','BAR 7六歩(バー・ナナロクフ)','katamachi','順化','night','バー',''),
('s94c3c3ec','JAZZ BAR SHIRAI HOUSE(シライハウス)','katamachi','順化','night','バー',''),
('scd7c8548','PICK UP BAR&CAFE (ピックアップバー&カフェ)','katamachi','順化','night','バー',''),
('s27530b44','SOMEN BAR白線屋','katamachi','順化','night','バー','hakusenya'),
('s19d452cc','十人十色koya','katamachi','順化','night','バー','10nin10color_koya'),
('s8f270ba2','手品家 福井店','katamachi','順化','night','バー','tejinaya.fukui'),
('s32a38885','Beer Stand Pivo(ビールスタンド ピヴォ)','katamachi','順化','night','バー','pivo_beerstand'),
('se20b01ba','Bar Someday','katamachi','順化','night','バー',''),
('s8c3cc9d1','Vestito Bar','katamachi','順化','night','バー',''),
('saeb1e8e6','CLUB CHOCOLAT','katamachi','順化','night','スナック・ラウンジ',''),
('s479c1a94','CLUB Kai','katamachi','順化','night','スナック・ラウンジ',''),
('s16a3484e','CLUB NAGISA','katamachi','順化','night','スナック・ラウンジ',''),
('s79d60569','CLUB NAGISA','katamachi','順化','night','スナック・ラウンジ',''),
('sd0993f8d','CLUB ROCHER','katamachi','順化','night','スナック・ラウンジ',''),
('s0d9ca646','CLUB Rapha','katamachi','順化','night','スナック・ラウンジ',''),
('s1f968c13','Club ゆず','katamachi','順化','night','スナック・ラウンジ',''),
('sfcf7b292','KOMACHI','katamachi','順化','night','スナック・ラウンジ',''),
('s74523afd','L and Heart','katamachi','順化','night','スナック・ラウンジ',''),
('sdf882d51','LA PAIX','katamachi','順化','night','スナック・ラウンジ',''),
('sb18877d9','LOUNGE 姫','katamachi','順化','night','スナック・ラウンジ',''),
('sfc318514','LUMINE','katamachi','順化','night','スナック・ラウンジ',''),
('s62364e3d','Lounge Crystal','katamachi','順化','night','スナック・ラウンジ',''),
('s25eafb21','Lounge K','katamachi','順化','night','スナック・ラウンジ',''),
('s2b61279f','Lounge LA Coo','katamachi','順化','night','スナック・ラウンジ',''),
('s50a7260e','Lounge ete','katamachi','順化','night','スナック・ラウンジ',''),
('s2f5ae9f8','Pretty May','katamachi','順化','night','スナック・ラウンジ',''),
('s045b5231','RETENTIR','katamachi','順化','night','スナック・ラウンジ',''),
('s382df82a','Richebourg','katamachi','順化','night','スナック・ラウンジ',''),
('s459aae16','SOHMA CLUB','katamachi','順化','night','スナック・ラウンジ',''),
('s63514fd4','Shampoo','katamachi','順化','night','スナック・ラウンジ',''),
('s367ecf02','club 奏鳴曲sonata','katamachi','順化','night','スナック・ラウンジ',''),
('s7c14a02c','lounge Salon','katamachi','順化','night','スナック・ラウンジ',''),
('sbeffbd40','おいない','katamachi','順化','night','スナック・ラウンジ',''),
('saeea5f27','ラウンジ 晴','katamachi','順化','night','スナック・ラウンジ',''),
('s933eb384','京','katamachi','順化','night','スナック・ラウンジ',''),
('s3ca85da3','呼詩','katamachi','順化','night','スナック・ラウンジ',''),
('sfb8404a0','小春日和','katamachi','順化','night','スナック・ラウンジ',''),
('s533e1c4f','小春日和','katamachi','順化','night','スナック・ラウンジ',''),
('sfc46a89d','彩 sayaka','katamachi','順化','night','スナック・ラウンジ',''),
('s8e85acec','心','katamachi','順化','night','スナック・ラウンジ',''),
('sbf085ba4','紗音','katamachi','順化','night','スナック・ラウンジ',''),
('s07f44bbf','藤','katamachi','順化','night','スナック・ラウンジ',''),
('sfcef8253','銀夏','katamachi','順化','night','スナック・ラウンジ',''),
('sb3173cc7','離宮','katamachi','順化','night','スナック・ラウンジ',''),
('se4c065aa','迦毘羅','katamachi','順化','gourmet','アジア・各国料理',''),
('sa83be97a','まるさん屋 福井片町店','katamachi','順化','gourmet','和食','marusanya_fukuikatamachi'),
('s75bc6b2f','KRAFT','katamachi','順化','night','バー','kraft_fukui'),
('s8237af5d','Woody','katamachi','順化','night','バー',''),
('sd16a99f6','snow drop','katamachi','順化','night','バー','snow.drop.mama'),
('s2bbf9c2a','ケネディ・クラブ','katamachi','順化','night','スナック・ラウンジ',''),
('s9d1d911a','パブ浪江','katamachi','順化','night','スナック・ラウンジ',''),
('s6a7f984b','猿の盃','katamachi','順化','night','バー',''),
('s8641430b','HAMBURG STEAK 亜米利館','katamachi','順化','gourmet','焼肉・肉料理','hamburg_american'),
('sffc04f28','les quatre hommes','katamachi','順化','gourmet','イタリアン・フレンチ','les.quatre.hommes'),
('s67e514d8','わらび 片町店','katamachi','順化','night','バー',''),
('s1effb8f7','やきとりの名門 秋吉 福井片町店','katamachi','順化','night','バー',''),
('s20c94c25','やきとり治郎吉 片町店','katamachi','順化','night','バー',''),
('sc9403682','㐂鶏屋(きどりや)','katamachi','順化','night','バー',''),
('s13659418','ACE.ATRIUM','katamachi','順化','night','スナック・ラウンジ',''),
('s8b15a371','Acclaim','katamachi','順化','night','スナック・ラウンジ',''),
('s74a5a434','Aries trois','katamachi','順化','night','スナック・ラウンジ',''),
('scd30cc66','Believe','katamachi','順化','night','スナック・ラウンジ',''),
('sd896e76d','C Collection','katamachi','順化','night','スナック・ラウンジ',''),
('scf57e8cf','CAMELLIA','katamachi','順化','night','スナック・ラウンジ','camellia20071206'),
('s14ccb856','CAVERNA AZZURRA','katamachi','順化','night','スナック・ラウンジ',''),
('s8652d2be','Diamond','katamachi','順化','night','スナック・ラウンジ',''),
('s72f2ff38','Girl''s Bar rerain','katamachi','順化','night','スナック・ラウンジ','rerain.com0810'),
('s206ce020','Imari','katamachi','順化','night','スナック・ラウンジ','imari_1221'),
('se715d19f','J’ADORE','katamachi','順化','night','スナック・ラウンジ','jadore_fukui.lounge'),
('s5dcf0a7e','LOUNGE GLITTER','katamachi','順化','night','スナック・ラウンジ','glitter.lounge'),
('sf3deac55','LOUNGE Refuge','katamachi','順化','night','スナック・ラウンジ',''),
('sf0ae02de','Lounge ACE','katamachi','順化','night','スナック・ラウンジ',''),
('s7897de60','Lounge BR','katamachi','順化','night','スナック・ラウンジ',''),
('sd6f31ced','Lounge el','katamachi','順化','night','スナック・ラウンジ','lounge_el_ocg'),
('sff1f8564','Lounge 凛','katamachi','順化','night','スナック・ラウンジ','lounge.rin'),
('sd7670334','MIZUKI','katamachi','順化','night','スナック・ラウンジ',''),
('s7093e6e6','MOGA MODERN GIRL','katamachi','順化','night','スナック・ラウンジ',''),
('s217715f4','OPUS ONE','katamachi','順化','night','スナック・ラウンジ',''),
('s86208ee6','SAYA','katamachi','順化','night','スナック・ラウンジ',''),
('sd357eb91','THE Moon.','katamachi','順化','night','スナック・ラウンジ','the_moon.102'),
('s774bab97','club 蒼','katamachi','順化','night','スナック・ラウンジ','club_ao_fukui'),
('sa523f63f','ラウンジ Yuka','katamachi','順化','night','スナック・ラウンジ',''),
('sbcdeae46','ラウンジ 阿吽','katamachi','順化','night','スナック・ラウンジ',''),
('sfef16d72','楚々 -soso-','katamachi','順化','night','スナック・ラウンジ','soso_fukui'),
('s4178b9d7','篠','katamachi','順化','night','スナック・ラウンジ',''),
('se1936e87','良玄 RYOGEN','katamachi','順化','night','スナック・ラウンジ',''),
('sf693ab32','麻衣','katamachi','順化','night','スナック・ラウンジ',''),
('s0a007fe7','黄色いハンカチ','katamachi','順化','night','スナック・ラウンジ',''),
('s3d6abb7e','Agit(アジト)','katamachi','順化','night','バー','agit19961220'),
('se8494126','Bistro Salice','katamachi','順化','night','バー','salicefukui_pr'),
('s20f30845','ばあー くろぽん','katamachi','順化','night','バー','kanekohideaki'),
('sefe7247a','パブ&レストラン樽','katamachi','順化','night','スナック・ラウンジ',''),
('s82b13c27','煉瓦館','katamachi','順化','night','バー','rengakan'),
('sfa7d871b','Amusemet Bar DOOR','katamachi','順化','night','バー','bar.door'),
('s9d27ed13','BAR FLOW(フロー)','katamachi','順化','night','バー',''),
('s2fd277f4','BAR RADIO','katamachi','順化','night','バー',''),
('s430f7a01','BAR UTa','katamachi','順化','night','バー',''),
('sd6e4569f','BAR くろひげ','katamachi','順化','night','バー',''),
('sa4207224','BAR 九龍(クーロン)','katamachi','順化','night','バー',''),
('s61116b31','BAR 浪漫','katamachi','順化','night','バー','bar_roman_fukui'),
('sa6c87222','BIRTH','katamachi','順化','night','バー',''),
('sf7bfd3ec','Bar jake','katamachi','順化','night','バー',''),
('s88c7c8d2','Bar レッツゴーヤング','katamachi','順化','night','バー','lets_go_young'),
('sa41d8a45','DUFFTOWN','katamachi','順化','night','バー',''),
('s8b4e803f','K''z Bar(ケーズ・バー)','katamachi','順化','night','バー',''),
('sb0eea03d','Musica Y BAR SOMBRERO','katamachi','順化','night','バー',''),
('s406971a8','ORIGINAL SOUND mix cafe CREME','katamachi','順化','night','バー','mix_cafe_creme'),
('sd0742f1e','SECRET CLASSICAL','katamachi','順化','night','バー',''),
('s5cf909b9','THE BAR LOTUS','katamachi','順化','night','バー',''),
('sf9e86472','THE BAR [i:st](イースト)','katamachi','順化','night','バー',''),
('sa1233ddd','gri-gri','katamachi','順化','night','バー',''),
('s6f9d5eee','ブラッセリー&クラシックバー Very Good','katamachi','順化','night','バー','verygoodbar'),
('scfaffe0c','レストバー season(シーズン)','katamachi','順化','night','バー',''),
('sd7e77550','ワインバル フォンデン','katamachi','順化','night','バー','fonden_winebar'),
('s2859042f','和食海鮮ダイニング 柳庵','katamachi','順化','gourmet','寿司・海鮮','yanagimachi_ryuan')
on conflict (slug) do update set name=excluded.name, zone=excluded.zone, town=excluded.town,
  category=excluded.category, genre=excluded.genre,
  instagram=case when public.shops.instagram_from='research' then excluded.instagram else public.shops.instagram end;
